- groovy/src/main/java/cucumber/api/groovy/Hooks.java
- groovy/src/main/java/cucumber/runtime/groovy/GroovyBackend.java
- groovy/src/main/java/cucumber/runtime/groovy/GroovyHookDefinition.java
Since the original method was accepting varargs (```Object... args```) as parameter, there was almost no way to add new method with proper parameters, without breaking backward compatibility.
> added support for execution order for "Before" and "After" hook. closes #807

- core/src/main/java/cucumber/runtime/io/ZipResourceIteratorFactory.java
- core/src/test/java/cucumber/runtime/io/ZipResourceIteratorFactoryTest.java
Here is a patch for #808. Unit tests included to ensure it works properly with zip and wsjar protocols (for weblogic and websphere support, respectively)
> Handles zip and wsjar protocols properly (fixes #808)

- core/src/main/java/cucumber/runtime/Utils.java
- core/src/test/java/cucumber/runtime/UtilsTest.java
Currently an IllegalArgumentException is thrown when an implementation of the ObjectFactory interface (from cucumber-java) creates an instance of a class that is loaded by another class loader:
java.lang.IllegalArgumentException: object is not an instance of declaring class
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at cucumber.runtime.Utils$1.call(Utils.java:34)
... 52 more
This happens in my case where I implemented an ObjectFactory that creates an instance in an OSGi context. The OSGi framework requires the class to be loaded by a bundle's class …
> Allow invoking methods on an instance which is loaded by a different class loader

- core/src/main/java/cucumber/runtime/model/CucumberExamples.java
- core/src/main/java/cucumber/runtime/model/CucumberScenarioOutline.java
- core/src/test/java/cucumber/runtime/model/CucumberExamplesTest.java
- core/src/test/java/cucumber/runtime/model/CucumberScenarioOutlineTest.java
Currently the description of an example scenario created from a Scenario Outline is empty. Both Scenario Outlines and Examples tables can have a description. This PR sets the description for an example scenario created from a Scenario Outline to:
* the concatenation of these description - if they both exists,
* the one that to exist - if only one of them exists,
* the empty string - if none of them exists.
Fixes #837.
> Set a description for Scenario Outline scenarios.

- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/java/cucumber/runtime/model/CucumberScenario.java
- core/src/test/java/cucumber/runtime/RuntimeOptionsTest.java
The IntelliJ's internal formatter does not implement the startOfScenarioLifeCycle and the endOfScenarioLifeCycle methods. The current handling of this has the side effect, that all other formatters (after the IntelliJ one in the plugin list), will not receive calls to these methods, see #803.
This PR changes the handling of exceptions from the the startOfScenarioLifeCycle and the endOfScenarioLifeCycle methods of formatters, so that also in this case all formatters will receive calls to these methods.
Fixes #803.
> Call all formatters, also when using the IntelliJ's internal formatter.

- core/src/main/java/cucumber/api/SummaryPrinter.java
- core/src/main/java/cucumber/runtime/DefaultSummaryPrinter.java
- core/src/main/java/cucumber/runtime/NullSummaryPrinter.java
- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptionsFactory.java
- core/src/main/java/cucumber/runtime/Stats.java
- core/src/main/java/cucumber/runtime/formatter/PluginFactory.java
- core/src/main/java/cucumber/runtime/model/CucumberScenario.java
- core/src/main/resources/cucumber/api/cli/USAGE.txt
- core/src/test/java/cucumber/runtime/RuntimeOptionsFactoryTest.java
- core/src/test/java/cucumber/runtime/RuntimeOptionsTest.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
- core/src/test/java/cucumber/runtime/StatsTest.java
- core/src/test/java/cucumber/runtime/formatter/AnyStepDefinitionReporter.java
- jython/bin/cucumber-jvm.py
This PR turns the summary printing into a plugin, [as discussed on the mailing list](https://groups.google.com/forum/#!searchin/cukes/[JVM]$20Control$20over$20the$20error$20summary$20printing./cukes/BZaKvrmdH9c/CnMPzWHAnKQJ). Two built-in summary printer plugins are created,
- `default_summary` which basically gives the same summary output as today, and 
- `null_summary` which gives no output at al
Inspired by Cucumber-Ruby, the `default_summary` is extended (compared to the current behaviour), with the listing of failed scenarios. Or to be precise the listing of the scenarios that makes the exit code non-zero, that is in strict mode also undefined and pending scenarios are listed.
The different supported plugin types are separated into different categories internally, to be able to …
> Make the Summary Printer into a plugin

- clojure/README.md
As highlighted in https://github.com/cucumber/cucumber-jvm/issues/780 there is a lack of documentation for cucumber-clojure. 
This is my attempt to start addressing that. I am neither a Cucumber nor Clojure expert; so this is based on my current working knowledge.
Feedback and corrections are welcome.
> Adding some documentation for Cucumber-Clojure

- java8/src/test/resources/cucumber/runtime/java8/test/java8.feature
Tiny, but annoying bug in the Java 8 test feature
> Fix spelling of "isolated"

- core/pom.xml
- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/test/java/cucumber/runtime/RuntimeOptionsTest.java
- examples/pax-exam/calculator-api/pom.xml
- examples/pax-exam/calculator-api/src/main/java/cucumber/examples/java/paxexam/CalculatorService.java
- examples/pax-exam/calculator-service/pom.xml
- examples/pax-exam/calculator-service/src/main/java/cucumber/examples/java/paxexam/service/Activator.java
- examples/pax-exam/calculator-service/src/main/java/cucumber/examples/java/paxexam/service/CalculatorServiceImpl.java
- examples/pax-exam/calculator-test/features/calculator.feature
- examples/pax-exam/calculator-test/pom.xml
- examples/pax-exam/calculator-test/src/test/java/cucumber/examples/java/paxexam/test/CalculatorSteps.java
- examples/pax-exam/calculator-test/src/test/java/cucumber/examples/java/paxexam/test/CalculatorTest.java
- examples/pax-exam/pom.xml
- java/pom.xml
- junit/pom.xml
- osgi/pom.xml
- osgi/src/main/java/cucumber/api/osgi/Filter.java
- osgi/src/main/java/cucumber/api/osgi/ServiceNotFoundException.java
- osgi/src/main/java/cucumber/api/osgi/TimeoutException.java
- osgi/src/main/java/cucumber/java/runtime/osgi/OsgiClassFinder.java
- osgi/src/main/java/cucumber/java/runtime/osgi/OsgiObjectFactory.java
- osgi/src/main/java/cucumber/java/runtime/osgi/OsgiObjectFactoryBase.java
- osgi/src/main/java/cucumber/java/runtime/osgi/PaxExamObjectFactory.java
- pom.xml
This is an upgraded version of pull request of #799 
My changes include:
* Adds OSGi headers to core, java and JUnit bundles.
* Changed loading of the USAGE.txt in RuntimeOptions, because due to OSGi class loading cause problems. I wrote more details in the commit message.
* Pax Exam example is included.
*NOTE*: Please release cucumber-jvm-deps with my other pull request (see https://github.com/cucumber/cucumber-jvm-deps/pull/3), because this changes make only sense when the jvm-deps bundle has also OSGi headers.
Thank you!
> Cucumber is ready to run in OSGi containers

- examples/clojure_cukes/project.clj
- examples/clojure_cukes/test/clojure_cukes/test/core.clj
- examples/clojure_cukes/test/features/cukes.feature
Fixed core.clj and associated deps in project to allow (run-cukes) to execute from repl and 'lein test' to succeed.
> Fix to allow lein test to to run successfully

- CONTRIBUTING.md
- pom.xml
Currently only some of the examples modules get their versions updated during a release. This will eventually make the openjdk7 job on Travis start to fail (when the snaphot versions for the latest release is no longer available from sonatype). To me it looks like it is the example modules that are in the release-sign-artifacts profile that get their versions updated during a release, therefore add all example modules are in the profile release-sign-artifacts.
The android module is removed from the profile release-sign-artifacts, I think that was only necessary when the android module was in a separate android profile.
Also add reminder in Contributing.md to update to the files in the example modules that specify the latest released version.
> Make sure that example versions are updated during release

- testng/src/main/java/cucumber/api/testng/AbstractTestNGCucumberTests.java
- testng/src/test/java/cucumber/api/testng/AbstractTestNGCucumberTestsTest.java
- testng/src/test/java/cucumber/api/testng/InvokedConfigurationMethodListener.java
This ensures that TestNGCucumberRunner.finish() will always be invoked.
Fixes cucumber/cucumber-jvm#955
> Always tear down TestNG cucumber tests.

- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
JUnit 4.12 uses a different class for the `AssumptionViolatedException` than older versions.
> Support assume feature with JUnit 4.12.

- pom.xml
"All Codehaus services will be terminated progressively until May 31st 2015" and repository.codehaus.org is no longer a usable maven repository.
> remove reference to decommissioned repository.codehaus.org repository

- core/src/main/java/cucumber/runtime/HookComparator.java
- core/src/test/java/cucumber/runtime/HookOrderTest.java
> Use Integer.compare() in HookComparator in order to guard against possible underflow

- groovy/src/main/java/cucumber/runtime/groovy/GroovyStepDefinition.java
- groovy/src/test/groovy/cucumber/runtime/groovy/compiled_stepdefs.groovy
- groovy/src/test/resources/cucumber/runtime/groovy/a_feature.feature
To reproduce:
The following code caused a NullPointerException because ParameterInfo was initialized without default delimiter:
```
Given(~'^this should be converted to a list:(.+)$') { List list ->
assertEquals(3, list.size())
assertEquals("Cucumber-JVM", list.get(0))
assertEquals("Cucumber", list.get(1))
}
```
The pull request contains the fix and the corresponding test.
> Groovy: Fixed NPE when using List as parameter type in step definitions

- osgi/pom.xml
cucumber-osgi can be used without pax-exam, just a small change to the manifest removes the necessity to need pax-exam bundles to be installed in the container running the tests.
> The package org.ops4j.pax.exam.util is optional for cucumber-osgi

- core/src/main/java/cucumber/runtime/Reflections.java
- core/src/main/java/cucumber/runtime/RuntimeGlue.java
- core/src/main/java/cucumber/runtime/formatter/RerunFormatter.java
- core/src/main/java/cucumber/runtime/table/TableConverter.java
- core/src/main/java/cucumber/runtime/table/TableDiffer.java
- core/src/main/java/cucumber/runtime/xstream/ConverterWithFormat.java
- core/src/test/java/cucumber/runtime/TestHelper.java
- guice/src/test/java/cucumber/runtime/java/guice/collection/CollectionUtil.java
- testng/src/test/java/cucumber/api/testng/TestNGCucumberRunnerTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - Collection.isEmpty() should be used to test for emptiness
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1155
Please let me know if you have any questions.
Kirill Vlasov
> Collection.isEmpty() should be used to test for emptiness

- android/src/test/java/com/vladium/emma/rt/RT.java
- core/src/main/java/cucumber/runtime/Shellwords.java
- core/src/main/java/cucumber/runtime/Timeout.java
- core/src/main/java/cucumber/runtime/Utils.java
- core/src/main/java/cucumber/runtime/io/Helpers.java
- core/src/test/java/cucumber/runtime/TestHelper.java
- core/src/test/java/cucumber/runtime/formatter/TempDir.java
- core/src/test/java/cucumber/runtime/table/TableParser.java
- guice/src/test/java/cucumber/runtime/java/guice/collection/CollectionUtil.java
- java/src/main/java/cucumber/runtime/java/ObjectFactoryLoader.java
- junit/src/main/java/cucumber/runtime/junit/Assertions.java
- junit/src/test/java/cucumber/runtime/junit/TestFeatureBuilder.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118
Please let me know if you have any questions.
Kirill Vlasov
> Utility classes should not have public constructors

- core/src/main/java/cucumber/api/CucumberOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptionsFactory.java
- core/src/main/resources/cucumber/api/cli/USAGE.txt
- core/src/test/java/cucumber/runtime/RuntimeOptionsFactoryTest.java
- core/src/test/java/cucumber/runtime/RuntimeOptionsTest.java
- junit/src/main/java/cucumber/api/junit/Cucumber.java
- junit/src/main/java/cucumber/runtime/junit/ExecutionUnitRunner.java
- junit/src/main/java/cucumber/runtime/junit/JUnitOptions.java
- junit/src/main/java/cucumber/runtime/junit/JUnitReporter.java
- junit/src/main/resources/cucumber/api/junit/OPTIONS.txt
- junit/src/test/java/cucumber/runtime/junit/ExecutionUnitRunnerTest.java
- junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java
- junit/src/test/java/cucumber/runtime/junit/JUnitReporterTest.java
The PR adds the mechanisms to have options for the JUnit module. To avoid that the Core module need to know about every option of the JUnit module, the JUnit options is passed through the Core module classes the same way that GCC passes option through to the pre-processor, linker etc. A JUnit option on the command line:
```
--junit,<option>
```
and in `@CucumberOptions`:
```
@CucumberOptions(junit = { <option> })
``` 
Two JUnit options are added:
- `--allow-started-ignored`
- `--filename-compatible-names`
The `--allow-started-ignored` makes the JUnit module fire the test started notification before each test step is executed. The current behaviour is to wait to fire the test started notification until after the test step has executed. This is done to be able to not fire the test started …
> Add options to the JUnit module

- .travis.yml
The benefits are that only if the test for all modules passes are the modules deployed, and that the tests for all modules are also executed on Java8.
> Move the deployment to the after_success phase on Travis

- core/src/test/java/cucumber/runtime/io/HelpersTest.java
* File#getAbsolutePath produced different result in each platform,
which caused failed test case, particularly in Windows
* File#equals does test the path for equality with the given object
> Change filePath test to be platform independent

- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/resources/cucumber/api/cli/USAGE.txt
- core/src/test/java/cucumber/runtime/RuntimeOptionsTest.java
When using --plugin the plugins of that type defined from a different source is clobbered. Using -Dcucumber.options="--plugin pretty" would clobber the formatter/reporter plugins defined in `@CucumberOptions`. --add-plugin does not clobber any plugins defined from a different
source.
The rational for this PR is both consistency, other list type options do clobber, and it enables some use cases not possible today:
* forcing one specific formatter to write to stdout on the CI system even when the users have specified another formatter to write to stdout in the `@CucumberOptions` ([mailing list post](https://groups.google.com/d/msg/cukes/8bZd6dWnSwc/9nF0st9bkmYJ))
> Add --add-plugin option and clobber when --plugin is used

- core/src/main/java/cucumber/runtime/io/URLOutputStream.java
- core/src/test/java/cucumber/runtime/io/URLOutputStreamTest.java
Hi.
I have several JUnit runners which runs cucumber tests in parallel at the same time. Each runner generate JSON file with test results to the one directory, e.g. ./target/json-files/
```
@CucumberOptions(
plugin = {"json:target/json-files/Test1.json"}, ...)
```
Sometimes I have an issue when one of runner is unable to create reports directory because another runner already done this. And it fails with error "Failed to create directory".
I think there is a make sense to double-check if reports directory is already exists (method cucumber.runtime.io.URLOutputStream#ensureParentDirExists).
> Double-check for directory exists in the ensureParentDirExists(File)

- junit/src/main/java/cucumber/runtime/junit/ExecutionUnitRunner.java
- junit/src/main/java/cucumber/runtime/junit/FeatureRunner.java
- junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java
Improve surefire integration.
Rerunning failed tests with Surefire requires a method to identify the tests.
Surefire currently uses a tuple of (Class, Method) to identify failed tests.
Cucumber-jvm uses test suites which do not consist of Classes or methods.
Therefore another method is needed.
JUnit provides the option to select tests that match a Description.
Descriptions are compared using  a unique Id. To identify tests between
different runs we should provide Descriptions with a predictable unique
id.
The current implementation did not suffice. While the provided cucumber
elements are unique, they are not predictable between runs making it
impossible to use their descriptions to rerun a failed test.
After this change it will be possible to update Surefire to use
descriptions to rerun …
> Use deterministic unique ids in Descriptions

- History.md
- java/src/main/java/cucumber/api/java8/HookBody.java
- java/src/main/java/cucumber/api/java8/HookNoArgsBody.java
- java/src/main/java/cucumber/api/java8/StepdefBody.java
- java/src/test/java/cucumber/runtime/java/java8test/AnonInnerClassStepdefs.java
- java8/src/test/java/cucumber/runtime/java8/test/LambdaStepdefs.java
- java8/src/test/resources/cucumber/runtime/java8/test/java8.feature
Allow Java8 lambda steps to throw checked Exceptions
Implemented requested changes on PR https://github.com/cucumber/cucumber-jvm/pull/1110.
- https://github.com/cucumber/cucumber-jvm/issues/1001
> [Java8] Allow lambda steps to throw checked Exceptions

- core/src/main/java/cucumber/runtime/snippets/ArgumentPattern.java
- core/src/main/java/cucumber/runtime/snippets/SnippetGenerator.java
- java/src/test/java/cucumber/runtime/java/JavaSnippetTest.java
SnippetGenerator recognises outline step parameters
SnippetGenerator - added pattern for \<param\>
ArgumentPattern - added possibility to provide custom replacement string
JavaSnippetTest - test
SnippetGenerator should suggest correct step definition for Scenario Outline Steps. At the moment cucumber-jvm creates step definition like this:
```
@Given("^Given a step with <param> from Scenario Outline$")
public void given_a_step() {
...
}
```
Fix makes the following step definition: 
```
@Given("^Given a step with (.*) from Scenario Outline$")
public void given_a_step(String arg0) {
...
}
```
We have related issue in tracker of IntelliJ IDEA: https://youtrack.jetbrains.com/issue/IDEA-160330
Fix tested like tested all other patterns for step parameters. See JavaSnippetTest
> SnippetGenerator recognises parameters from Scenario Outline (<param>)

- scala/sources/src/main/scala/cucumber/api/scala/package.html
Tested that http://cucumber.github.io/api/cucumber/jvm/scaladoc/ works
> Fix broken link to scaladoc

- core/src/main/java/cucumber/runtime/table/CamelCaseStringConverter.java
- core/src/test/java/cucumber/runtime/table/CamelCaseStringConverterTest.java
- core/src/test/java/cucumber/runtime/table/ToDataTableTest.java
instead of a `StringIndexOutOfBoundsException`:
``` java
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:658)
at cucumber.runtime.table.CamelCaseStringConverter.uncapitalize(CamelCaseStringConverter.java:37)
at cucumber.runtime.table.CamelCaseStringConverter.map(CamelCaseStringConverter.java:13)
at cucumber.runtime.table.TableConverter$1.map(TableConverter.java:284)
at cucumber.runtime.table.TableConverter$1.map(TableConverter.java:281)
at gherkin.util.FixJava.map(FixJava.java:28)
at cucumber.runtime.table.TableConverter.convertTopCellsToFieldNames(TableConverter.java:281)
at cucumber.runtime.table.TableConverter.toListOfComplexType(TableConverter.java:101)
at cucumber.runtime.table.TableConverter.convert(TableConverter.java:91 …
```
> Show explicit error message when field name missed in table header

- core/src/main/java/cucumber/api/TestStep.java
- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- core/src/test/java/cucumber/api/TestStepTest.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
- core/src/test/java/cucumber/runtime/TestHelper.java
- core/src/test/java/cucumber/runtime/formatter/JUnitFormatterTest.java
- junit/src/main/java/cucumber/runtime/junit/JUnitReporter.java
- junit/src/test/java/cucumber/runtime/junit/JUnitReporterTest.java
Map AssumptionViolatedException to Skipped status, so that the exit code is zero in presence of them also in strict mode.
AssumptionViolatedExceptions are used in JUnit to signal after the test has started that it is not meaningful given the current conditions. Currently these exceptions are mapped to the Pending status, but it is a better match to map them to the Skipped status, so that the exit code is zero in the presence of them also in the strict mode.
Fixes #1007.
The automatic tests has been updated accordingly.
> Map AssumptionViolatedException to Skipped status.

- junit/src/main/java/cucumber/runtime/junit/JUnitOptions.java
- junit/src/main/java/cucumber/runtime/junit/JUnitReporter.java
- junit/src/main/java/cucumber/runtime/junit/NotificationLevel.java
- junit/src/main/java/cucumber/runtime/junit/PickleRunners.java
- junit/src/main/java/cucumber/runtime/junit/SkippedThrowable.java
- junit/src/main/java/cucumber/runtime/junit/UndefinedThrowable.java
- junit/src/main/resources/cucumber/api/junit/OPTIONS.txt
- junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java
- junit/src/test/java/cucumber/runtime/junit/JUnitReporterTest.java
Send TestAssumptionFailed notifications instead of TestIgnored notifications to mark scenarios/steps as skipped. 
Since it is only after a step or scenario has been executed we can tell if it should be considered skipped in JUnit terms, TestAssumptionFailed notifications suits better than TestIgnored notifications.
By using TestAssumptionFailed to mark scenarios/steps as skipped, TestStarted can always be fired before the scenario/step is executed, therefore the option `--allow-stared-ignored` is not longer needed.
By using TestIgnored notifications, the passing of the TestStarted had to be delayed until after the step has executed, which is both unexpected and an unnecessary complex solution. It also caused the need for the `--allow-stared-ignored` option (which adds more complexity).
In …
> [JUnit] Use AssumptionFailed to mark scenarios/steps as skipped

- examples/java-webbit-websockets-selenium/src/test/java/cucumber/examples/java/websockets/SharedDriver.java
The shutdown hook should really *quit* the driver.
WebDriver#close would only "close the current window, quitting the browser if it's the last window currently open"
https://static.javadoc.io/org.seleniumhq.selenium/selenium-api/2.52.0/org/openqa/selenium/WebDriver.html#close--
> java-webbit-websockets-selenium example: fix SharedDriver

- .editorconfig
- CONTRIBUTING.md
Use EditorConfig for some editor styles
[EditorConfig](http://editorconfig.org/) is a simple config file that sets various editor settings like line-feed and encoding automatically. It's supported by several editors and IDEs.
EditorConfig makes some of the more general style guides automatically enforceable and it's wide adoption and support make it highly likely it's configuration will take hold for many users. It simplifies setup since users don't have to update their editor settings. There's a chance that a user either overrides the settings or doesn't use an editor that supports it, but that was an existing problem anyway.
Opened code in IntelliJ & Atom and verified changes to the `.editorconfig` file caused expected changes when adding/modifying lines in files.
> Use EditorConfig

- core/src/main/java/cucumber/runtime/Runtime.java
This is a minor change to the Runtime.java class to use Glue.java interface instead of RuntimeGlue.java for the parameters to the Runtime.java's constructors.
See Effective Java 52
Specifically, I'm trying to create a custom Runtime for the Cucumber JVM to better meet my company's business needs. It would be more useful to provide the Glue type as the parameter to the Runtime rather than RuntimeGlue. Currently, I have to extend the RuntimeGlue and override all of the interface methods, effectively ignoring the RuntimeGlue implementation.
These changes should already be covered by existing tests. They have essentially no effect on existing code.
> Change constructor parameter type to interface

- History.md
- java8/pom.xml
- java8/src/main/java/cucumber/runtime/java8/ConstantPoolTypeIntrospector.java
- java8/src/test/java/cucumber/runtime/java8/test/LambdaStepdefs.java
- java8/src/test/resources/cucumber/runtime/java8/test/java8.feature
- kotlin-java8/README.md
- kotlin-java8/pom.xml
- kotlin-java8/src/test/kotlin/cucumber/runtime/kotlin/test/LambdaStepdefs.kt
- kotlin-java8/src/test/kotlin/cucumber/runtime/kotlin/test/RunCukesTest.kt
- kotlin-java8/src/test/resources/cucumber/runtime/kotlin/test/kotlin.feature
- pom.xml
The ConstantPoolTypeIntrospector did not know how to handle references to an instance method of an arbitrary object of a particular type and Kotlin lambda expression without arguments or closure variables. This lead to issues:
- https://github.com/cucumber/cucumber-jvm/issues/1123
- https://github.com/cucumber/cucumber-jvm/issues/1126
Updated the ConstantPoolTypeIntrospector to check for instance methods by counting the parameters expected by the interface and those bound to the anonymous class. Only iff this is an instance method the result will come up one short.
Resolved Kotlin specific problems by checking if the reference method equals the magic constant "INSTANCE".
Extended examples in features to include kotlin and all 4 types of method references.
Still awaiting confirmation from: …
> [Java8, Kotlin Java8] Support java 8 method references

- History.md
- spring/src/main/java/cucumber/runtime/java/spring/GlueCodeContext.java
- spring/src/main/java/cucumber/runtime/java/spring/GlueCodeScope.java
- spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java
- spring/src/test/java/cucumber/runtime/java/spring/threading/RunParallelCukesTest.java
- spring/src/test/java/cucumber/runtime/java/spring/threading/ThreadingStepDefs.java
- spring/src/test/resources/cucumber/runtime/java/spring/threadingCukes.feature
When running in parallel the dependency injection context was shared between
scenarios. This made it impossible to run cucumber test with spring without
forking the JVM.
To reduce the resources required to execute a test each thread now will
have its own dependency injection context allowing tests to be executed in
parallel threads.
- https://github.com/cucumber/cucumber-jvm/issues/1106
This fixes #1106
Created a unit tests that executes the same cucumber scenario in parallel. The scenario knows it is being executed in parallel and checks if it has not been re-used by any other threads.
> [Spring] Support multithreaded execution of scenarios

- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptionsFactory.java
- core/src/main/java/cucumber/runtime/xstream/LocalizedXStreams.java
- core/src/test/java/cucumber/runtime/DummyConverter.java
- core/src/test/java/cucumber/runtime/RuntimeOptionsFactoryTest.java
- core/src/test/java/cucumber/runtime/xstream/ExternalConverterTest.java
This lets us provide converters for any classes that we cannot annotate directly with `@XStreamConverter`. For example,
```
@XStreamConverters(
@XStreamConverter(MyConverter.class),
@XStreamConverter(MyOtherConverter.class)
)
@CucumberOptions(...)
@RunWith(Cucumber.class)
public class RunCukesTest {
}
```
The existing `@XStreamConverter` annotations are being reused for consistency. The `RuntimeOptionsFactory` will check for these annotations on the same class that has the `@CucumberOptions` annotation, which keeps this change nicely internal to `cucumber-core`.
> Allow global registration of custom XStream converters.

- History.md
- spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java
- spring/src/main/java/org/springframework/test/context/FixBootstrapUtils.java
The `TestContextManager(Class<?>)` uses a static ContextCache. This meant
that step definitions from different threads could be registered in
same context multiple times when running in parallel.
This is resolved by creating a ThreadLocal ContextCache for each
SpringFactory.
- https://travis-ci.org/cucumber/cucumber-jvm/jobs/244215644
- https://github.com/cucumber/cucumber-jvm/pull/1148
> [Spring] Do not share ContextCache between threads

- core/src/main/java/cucumber/runtime/table/PascalCaseStringConverter.java
- core/src/main/java/cucumber/runtime/xstream/ComplexTypeWriter.java
- core/src/test/java/cucumber/runtime/table/TableConverterTest.java
- core/src/test/java/cucumber/runtime/table/ToDataTableTest.java
It can happen that in ComplexTypeWriter "startNode" is called more often than "setValue". In our case this happened when one of the fields was an empty Set, but perhaps there are other cases too.
In this case, startNode is called, but setValue is not. This causes the fieldNames and fieldValues lists to go out of alignment which causes all sorts of havoc when creating the DataTable.
This fix simply replaces the two separate lists with a Map, so that they are always aligned. One caveat of this approach is that if the same field name is serialized more than once, the previous value would be overwritten. However, seeing how the Writer is used, this does not seem like something that the current DataTables can handle anyway.
All existing tests pass.
> Fix issue in ComplexTypeWriter

- .editorconfig
- .travis.yml
- examples/android/cukeulator-test/pom.xml
- examples/android/pom.xml
- examples/clojure_cukes/pom.xml
- examples/groovy-calculator/pom.xml
- examples/java-calculator-testng/pom.xml
- examples/java-calculator/pom.xml
- examples/java-webbit-websockets-selenium/.gitignore
- examples/java-webbit-websockets-selenium/pom.xml
- examples/java-webbit-websockets-selenium/src/main/java/cucumber/examples/java/websockets/TemperatureServer.java
- examples/java-webbit-websockets-selenium/src/test/java/cucumber/examples/java/websockets/NavigationStepdefs.java
- examples/java-webbit-websockets-selenium/src/test/java/cucumber/examples/java/websockets/ServerHooks.java
- examples/java-webbit-websockets-selenium/src/test/java/cucumber/examples/java/websockets/SharedDriver.java
- examples/java-webbit-websockets-selenium/src/test/java/cucumber/examples/java/websockets/TemperatureStepdefs.java
- examples/java-webbit-websockets-selenium/src/test/java/cucumber/examples/java/websockets/WebDriverFactory.java
- examples/java-wicket/java-wicket-main/src/main/java/cucumber/examples/java/wicket/view/Available.java
- examples/java-wicket/java-wicket-main/src/main/java/cucumber/examples/java/wicket/view/Create.java
- examples/java-wicket/java-wicket-main/src/main/java/cucumber/examples/java/wicket/view/Rent.java
- examples/java-wicket/pom.xml
- examples/pax-exam/pom.xml
- examples/pom.xml
- examples/spring-txn/pom.xml
- kotlin-java8/pom.xml
- pom.xml
- scala/scala_2.12/pom.xml
Updated dependencies and added spiffy new webdriver factory that  in
combination with the driver-binary-downloader-maven-plugin just works.
- #1033
This fixes #1033
> [Examples] Fix java webbit websockets selenium

- History.md
- gosu/pom.xml
- gosu/src/main/java/cucumber/runtime/gosu/GlueSource.java
- gosu/src/main/java/cucumber/runtime/gosu/GosuBackend.java
- gosu/src/main/java/cucumber/runtime/gosu/GosuStepDefinition.java
- gosu/src/test/java/cucumber/runtime/gosu/GosuSnippetTest.java
- pom.xml
Re-enable Gosu!
This PR updates Gosu support and re-enables the cucumber-gosu module.
Gosu has been broken for a while now, see #874, #1086
Existing tests are passing again.
> [Gosu] Fix and re-enable Gosu for 2.0.0

- junit/src/main/java/cucumber/runtime/junit/JUnitOptions.java
- junit/src/main/resources/cucumber/api/junit/OPTIONS.txt
- junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java
- junit/src/test/java/cucumber/runtime/junit/JUnitReporterTest.java
Make the default for the JUnit module not to issue step notifications.
Make the default for the JUnit module not to issue step notifications. Step notifications can be turn on with the `--step-notification` option to the Junit module.
This aligns test case in the Cucumber-JVM domain (Scenarios) with the test cases in the JUnit domain (the leafs in the description tree).
The automated test suite has been updated to verify this behaviour.
It depends on ones perspective if this is a bug fix or a breaking change.
> [JUnit] Make no step notifications the default.

- core/src/main/java/cucumber/api/Scenario.java
- core/src/main/java/cucumber/api/TestCase.java
- core/src/main/java/cucumber/runtime/ScenarioImpl.java
- core/src/test/java/cucumber/api/ScenarioTest.java
- core/src/test/java/cucumber/api/TestCaseTest.java
- core/src/test/java/cucumber/runtime/ScenarioResultTest.java
- scala/sources/src/test/scala/cucumber/api/scala/ScalaDslTest.scala
Provide a unique id of the current scenario to the hooks. Fixes #1158.
Provide methods to access the uri of the feature file of the current executing scenario and the line(s) where the scenario is defined in the feature file. If the scenario is created from a scenario outline both the line of the example row and the scenario outline is provided.
In addition also put back the getId() method, returning `<uri>:<line>` (in case of scenarios from a scenario outline it is `<example row line>`). Even though it is not possible to provide the same id string as when using Gherkin v2.12.2 (`<featrue name>:<scenario name>`), hooks using Scenario.getId() sill still compile and still get a unique id for the scenario through that method.
The automated test suite updated to cover this functionality.
> [Core] Provide a unique id of the current scenario to the hooks.

- android/src/main/java/cucumber/runtime/android/CucumberExecutor.java
- core/src/main/java/cucumber/runner/TimeService.java
- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- core/src/test/java/cucumber/api/TestStepTest.java
- core/src/test/java/cucumber/runner/EventBusTest.java
- core/src/test/java/cucumber/runner/StepDurationTimeService.java
- core/src/test/java/cucumber/runner/TimeServiceStub.java
- core/src/test/java/cucumber/runner/TimeServiceTest.java
- core/src/test/java/cucumber/runtime/TestHelper.java
- core/src/test/java/cucumber/runtime/UndefinedStepsTrackerTest.java
- core/src/test/java/cucumber/runtime/formatter/JSONFormatterTest.java
- core/src/test/java/cucumber/runtime/formatter/JUnitFormatterTest.java
- core/src/test/java/cucumber/runtime/formatter/PluginFactoryTest.java
- junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java
Let the JUnit Formatter use the duration of the test case result.
Let the JUnit Formatter use the duration of the test case result instead of summing up the durations of the test step results.
Also refactor the TimeService to have the methods startTime(), currentTime(), and finishTime(). These methods actually do the same thing but having them all enables/simplifies the mocking of time in tests. For example when executing a test case with two test steps the following calls to the TimeService will be issued:
```
startTime()  - for the time stamp of the TestCaseStarted Event
startTime()  - for the time stamp of the first TestStepStarted Event
finishTime() - for the time stamp of the first TestStepFinished Event
startTime()  - for the time stamp of the second TestStepStarted Event …
```
> [Core] Use the test case duration in the JUnit Formatter.

- pom.xml
- weld/src/main/java/cucumber/runtime/java/weld/WeldFactory.java
- weld/src/test/resources/cucumber/runtime/java/weld/cukes.feature
I mainly changed the `WeldFactory` to create a single WeldContainer instance per factory, using the Weld builder.
The WeldFactory is no longer a subclass of the Weld builder class. It uses now a private member of type WeldContainer to hold a single weld container instance per factory (scenario).
The instance is created in the start method by using the weld builder method initialize and released in the stop method with the close method.
The resolving of class types in the getInstance method is also simplified, because it can use the select method directly on the container instance.
I've come to develop this change as described in issue #1165. See this issue for details.
The fix uses the scenario tests in cukes.feature as well as the WeldFactoryTest within the cucumber-weld module to prove …
> Use Weld SE 2.4.4.Final

- core/src/main/java/cucumber/api/Result.java
- core/src/main/java/cucumber/api/TestStep.java
- core/src/main/java/cucumber/api/event/SnippetsSuggestedEvent.java
- core/src/main/java/cucumber/runner/Runner.java
- core/src/main/java/cucumber/runtime/DefinitionMatch.java
- core/src/main/java/cucumber/runtime/HookDefinitionMatch.java
- core/src/main/java/cucumber/runtime/StepDefinitionMatch.java
- core/src/main/java/cucumber/runtime/UndefinedStepDefinitionMatch.java
- core/src/main/java/cucumber/runtime/UndefinedStepsTracker.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
- core/src/test/java/cucumber/runtime/UndefinedStepDefinitionMatchTest.java
- core/src/test/java/cucumber/runtime/UndefinedStepsTrackerTest.java
Add the SnippetsSuggestedEvent and remove the snippets from the undefined results.
Generate the snippets directly when not match is found for a step and communication them in a separate event, instead of pass them on the result object with the TestStepFinished event.
Better separation of concerns.
The automated test suite is updated to verify this behaviour.
> [Core] Add the SnippetsSuggestedEvent.

- android/src/main/java/cucumber/runtime/android/AndroidInstrumentationReporter.java
- android/src/main/java/cucumber/runtime/android/CucumberExecutor.java
- android/src/test/java/cucumber/runtime/android/AndroidInstrumentationReporterTest.java
- core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java
- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- core/src/main/java/cucumber/runtime/formatter/PrettyFormatter.java
- core/src/main/java/cucumber/runtime/formatter/TestSourcesModel.java
- core/src/test/java/cucumber/runtime/formatter/JUnitFormatterTest.java
- core/src/test/resources/cucumber/runtime/formatter/JUnitFormatterTest_1.report.xml
- core/src/test/resources/cucumber/runtime/formatter/JUnitFormatterTest_1_strict.report.xml
- core/src/test/resources/cucumber/runtime/formatter/JUnitFormatterTest_2.report.xml
- core/src/test/resources/cucumber/runtime/formatter/JUnitFormatterTest_3.report.xml
Change both the JUnit Formatter and the Android Instrumentation Reporter to use the feature name as the class name in the reports.
Change both the JUnit Formatter and the Android Instrumentation Reporter to use the feature name as the class name reports. This is the behaviour in v1.2.5, but to avoid having to extract the feature name from the TestSourceRead event it was changed in the upgrade to Gherkin v4.
To avoid a regression between v1.2.5 and v2.0.0.
The automated test suite has been update to verify this behaviour.
> Use the feature name as class name in reports.

- android/src/main/java/cucumber/runtime/android/AndroidInstrumentationReporter.java
- core/src/main/java/cucumber/api/Result.java
- core/src/main/java/cucumber/api/TestStep.java
- core/src/main/java/cucumber/runner/Runner.java
- core/src/main/java/cucumber/runtime/AmbiguousStepDefinitionsMatch.java
- core/src/main/java/cucumber/runtime/ScenarioImpl.java
- core/src/main/java/cucumber/runtime/Stats.java
- core/src/main/java/cucumber/runtime/formatter/AnsiFormats.java
- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- core/src/main/java/cucumber/runtime/formatter/ProgressFormatter.java
- core/src/main/java/cucumber/runtime/formatter/TestNGFormatter.java
- core/src/test/java/cucumber/runtime/AmbiguousStepDefinitionMatchsTest.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
- core/src/test/java/cucumber/runtime/StatsTest.java
- core/src/test/java/cucumber/runtime/TestHelper.java
- junit/src/main/java/cucumber/runtime/junit/JUnitReporter.java
- testng/src/main/java/cucumber/api/testng/FeatureResultListener.java
- testng/src/main/java/cucumber/api/testng/TestNgReporter.java
Report ambiguous steps as a separate result type, instead of reporting them as failed.
Report ambiguous steps as a separate result type, instead of reporting them as failed. The new ambiguous result type will make the exit code non-zero (the same as the failed result type currently used when ambiguous step matches are found).
Cucumber-JS already has a separate result type for [ambiguous step matches](https://github.com/cucumber/cucumber-js/blob/a45574104647b6340f4218b942f00280e44174e1/features/ambiguous_step.feature#L33-L34). In Cucumber-Ruby there is an [initiative to introduce them](https://github.com/cucumber/cucumber-ruby/pull/1132#issuecomment-311181056)
The automated test suite has been updated to verify this behaviour.
I have manually introduces ambiguous step matches in the …
> [Core, JUnit, Android] Add the ambiguous result type.

- core/src/main/java/cucumber/api/event/TestRunStarted.java
- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/java/cucumber/runtime/Stats.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
- core/src/test/java/cucumber/runtime/StatsTest.java
Add TestRunStarted event, move the exit code handling to the Stats class.
Add the TestRunStarted event and present the duration between the TestRunStarted and TestRunFinished events in the summary print out.
Move the handling of exit code and errors to the summary print out to the Stats class.
The duration of a test step is the duration between the TestStepStarted and TestStepFinished events. The duration of a test case is the duration between the TestCaseStarted and TestCaseFinished events. 
Therefore it is natural that the duration of the test run (presented in the summary print out) is the duration between the TestRunStarted and TestRunFinished events
The automated test suite has been updated to verify this behaviour.
> [Core] Add TestRunStarted event, let Stats handle the exit code

- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/main/java/cucumber/runtime/RuntimeGlue.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
- core/src/test/java/cucumber/runtime/TestHelper.java
- junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java
Passed RuntimeGlue and it's tracker is not connected with Runtime and it's tracker.
> [Core] Use UndefinedStepsTracker from provided RuntimeGlue 

- History.md
- core/src/main/java/cucumber/runtime/Glue.java
- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/main/java/cucumber/runtime/RuntimeGlue.java
- core/src/main/java/cucumber/runtime/UndefinedStepsTracker.java
- core/src/test/java/cucumber/runtime/RuntimeGlueTest.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
- core/src/test/java/cucumber/runtime/TestHelper.java
- java/src/test/java/cucumber/runtime/java/JavaHookTest.java
- junit/src/test/java/cucumber/runtime/junit/FeatureRunnerTest.java
Glue only served to pass the UndefinedStepsTracker between Runtime and
Runtime. Decoupling this removes some pointless complexity.
The constructor `RuntimeGlue(UndefinedStepsTracker, LocalizedXStreams)`
has been deprecated to avoid breaking existing implementations.
The Runtime will not use the provided UndefinedStepsTracker but this is
consistent with the behaviour prior to  #1019.
Third parties interested in undefined steps can use the subscribe their own
UndefinedStepsTracker to the event bus.
> [Core] Decouple UndefinedStepsTracker from Glue

- core/src/main/java/cucumber/api/formatter/NiceAppendable.java
- core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java
- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- core/src/main/java/cucumber/runtime/formatter/TestNGFormatter.java
- testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java
Refactored the code around streams so it follows these rules:
- Streams should be closed by their owners
- A stream is owned by its creator or when provided as a constructor argument
- Stream ownership should be the smallest possible unit. The method, class, process, system.
- System.out and System.error may never be closed
Fixes #1108 
Checked the code for all occurrences of ` .close()`,`System.out`, `System.error`, `new NiceAppendable`, `new .*OutputStream` and `new .*Writer`in non-test code.
Automated tests should be passing.
>  [Core, TestNg] Clean up stream closing

- History.md
- examples/pom.xml
- examples/scala-calculator/pom.xml
- examples/scala-calculator/src/main/scala/cucumber/examples/scalacalculator/RpnCalculator.scala
- pom.xml
- scala/pom.xml
- scala/scala_2.10/pom.xml
- scala/scala_2.11/pom.xml
- scala/scala_2.12/pom.xml
- scala/sources/gen.scala
- scala/sources/src/main/scala/cucumber/api/scala/ScalaDsl.scala
- scala/sources/src/main/scala/cucumber/runtime/scala/ScalaBackend.scala
- scala/sources/src/main/scala/cucumber/runtime/scala/ScalaHookDefinition.scala
- scala/sources/src/main/scala/cucumber/runtime/scala/ScalaSnippetGenerator.scala
- scala/sources/src/main/scala/cucumber/runtime/scala/ScalaStepDefinition.scala
- scala/sources/src/test/resources/cucumber/runtime/scala/test/cukes.feature
- scala/sources/src/test/scala/cucumber/runtime/scala/test/StepDefs.scala
Fix cucumber-scala_2.12 compatibility with Scala 2.12.
* cucumber-scala_2.12 is compiled as Java 8 bytecode, along with scala-calculator
* Scala versions have been upgraded 
- `2.12.0-M1` to `2.12.2` 
- `2.11.8` to `2.11.11`
* Use `Manifest` instead of Java reflection to provide type information
Issue #1087, #1091
Existing tests and Scala example passing.
Manually tested against [szarnyasg/cucumber-scala-2-12](https://github.com/szarnyasg/cucumber-scala-2-12). 
The expected result is that the test runs but fails.
> [Scala] Compile cucumber-scala_2.12 against Java 8

- core/src/main/java/cucumber/runtime/formatter/RerunFormatter.java
- core/src/main/java/cucumber/runtime/model/CucumberFeature.java
- core/src/test/java/cucumber/runtime/formatter/RerunFormatterTest.java
- core/src/test/java/cucumber/runtime/model/CucumberFeatureTest.java
Separating features by whitespace may cause issues when the path contains
whitespace characters. E.g:
```
/home/users/mpkorstanje/My Documents/tests/bar.feature
```
Separating features to be rerun by a new line avoids this problem and creates
a  more readable format. E.g:
```
/home/users/mpkorstanje/My Documents/tests/bar01.feature:12:14:15
/home/users/mpkorstanje/My Documents/tests/bar02.feature:1
/home/users/mpkorstanje/My Documents/tests/bar03.feature:14
/home/users/mpkorstanje/My Documents/tests/bar04.feature:15
```
- #1059
> [Core] Separate rerun paths by a new line character

- android/src/main/java/cucumber/runtime/android/AndroidInstrumentationReporter.java
- android/src/test/java/cucumber/runtime/android/AndroidInstrumentationReporterTest.java
- core/src/main/java/cucumber/api/CucumberOptions.java
- core/src/main/java/cucumber/api/TestCase.java
- core/src/main/java/cucumber/api/event/TestSourceRead.java
- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/main/java/cucumber/runtime/UndefinedStepsTracker.java
- core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java
- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- core/src/main/java/cucumber/runtime/formatter/PrettyFormatter.java
- core/src/main/java/cucumber/runtime/formatter/RerunFormatter.java
- core/src/main/java/cucumber/runtime/formatter/TestNGFormatter.java
- core/src/main/java/cucumber/runtime/model/CucumberFeature.java
- core/src/test/java/cucumber/runtime/FeatureBuilderTest.java
- junit/src/main/java/cucumber/runtime/junit/FeatureRunner.java
- junit/src/test/java/cucumber/runtime/junit/PickleRunnerWithStepDescriptionsTest.java
- junit/src/test/java/cucumber/runtime/junit/TestPickleBuilder.java
- testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java
Use "uri" instead of "path" to reference feature files, especially in public methods of classes in the api packages.
"uri" is used in the Gherkin library to refer to feature files, and has also the advantage of that uri:s use the [same separator, "/", on all platforms](https://stackoverflow.com/a/1589958), whereas path:s use different separators, "/" on Unix/Linux and MacOS, but "\" in Windows.
Technically we are abusing the uri concept by also using "uri"s defined relative the "current directory", an correct uri always define the scheme (`file`, `http(s)` etc), and are in case of the file scheme the absolute path on the host in question.
Consistency with the Gherkin library, enabling using the same output regardless of the platform.
For several releases Cucumber-JVM has regardless of …
> Use "uri" instead of "path" to reference feature files.

- needle/src/main/java/cucumber/runtime/java/needle/NeedleFactory.java
- needle/src/test/java/cucumber/runtime/java/needle/test/AtmWithdrawalSteps.java
- needle/src/test/java/cucumber/runtime/java/needle/test/MoreSteps.java
The problem is best shown by the changes in the test files. Depending on the order in which objects are instantiated by the factory (which seems to be arbitrary), the @NeedleInjectionProvider annotation may work for other classes or not.
> [Needle] Handle circular dependencies

- clojure/pom.xml
- core/pom.xml
- examples/clojure_cukes/pom.xml
- examples/groovy-calculator/pom.xml
- examples/java-calculator-testng/pom.xml
- examples/java-calculator/pom.xml
- examples/pax-exam/calculator-test/src/test/java/cucumber/examples/java/paxexam/test/CalculatorTest.java
- examples/scala-calculator/pom.xml
- examples/spring-txn/pom.xml
- groovy/pom.xml
- guice/pom.xml
- java/pom.xml
- jruby/pom.xml
- junit/pom.xml
- jython/pom.xml
- needle/pom.xml
- openejb/pom.xml
- osgi/pom.xml
- picocontainer/pom.xml
- pom.xml
- rhino/pom.xml
- scala/pom.xml
- spring/pom.xml
- weld/pom.xml
To make cucumber-android work out of the box, update the cucumber-jvm-deps dependency to a version which includes non Java8 classes (using bytecode major version 52).
This RP depends on a new cucumber-jvm-deps release which includes the [downgrading of the xstream version to v1.4.7](https://github.com/cucumber/cucumber-jvm-deps/commit/669ae21ddceac7a31e3804bb5c44cd02bd95fb75). xstream > v1.4.7 includes Java8 classes (using bytecode major version 52), which are used on Jdk8 but cannot be used in an Android dex file. 
The cucumber-jvm-deps dependency is updated to v1.0.6 (not released yet).
Also exclude the gherkin-jvm-deps from the gherkin dependency. Since classes from gherkin-jvm-deps is repackaged in the gherkin jar, this is needed to avoid to add the same class twice when creating the …
> Update the version of the cucumber-jvm-deps dependency

- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/java/cucumber/runtime/model/CucumberFeature.java
- core/src/test/java/cucumber/runtime/model/CucumberFeatureTest.java
Implemented the rerun file specification from cucumber ruby[1]. It
handles spaces, new lines as a separator as well as no separator at all.
References:
[1] https://github.com/cucumber/cucumber-ruby/blame/master/lib/cucumber/cli/rerun_file.rb
> [Core] Use cucumber-ruby rerun file specification

- core/src/main/java/cucumber/runtime/io/FileResource.java
- core/src/main/java/cucumber/runtime/io/FileResourceIterable.java
- core/src/main/java/cucumber/runtime/io/FileResourceIterator.java
- core/src/main/java/cucumber/runtime/io/FileResourceIteratorFactory.java
- core/src/test/java/cucumber/runtime/io/FileResourceTest.java
When a features argument does not uses the classpath, use the whole feature file path as the uri of the feature file.
Current behaviour:
Given the following folder structure:
```
features
| - subdir
|- test1.feature
```
Using the features argument `features/subdir/test1.feature` 
-> the uri becomes `features/subdir/test1.feature`
Using the features argument `features` 
-> the uri becomes `subdir/test1.feature`
Apart from being inconsistent and confusing this also makes the rerun feature not working when loading feature file from the file system directly, instead of loading them using the classpath.
The new behaviour:
Given the same folder structure
Using the features argument `features/subdir/test1.feature` 
-> the uri becomes `features/subdir/test1.feature`
Using the features argument …
> Use whole path for uri:s for file system feature files.

- junit/src/main/java/cucumber/api/junit/Cucumber.java
Junit invokes several framework methods around the test execution.
The cucumber runner should finish its whole execution inside these.
To be precises these two should be equivalent:
```
@BeforeClass
public static void before {
// Do stuff
}
@Test
public void test(){
cucumber.api.cli.Main.main(some arguments....)
}
@AfterClass
public static void after {
// Do stuff
}
```
```
@RunWith(Cucumber.class)
public class Test {
@BeforeClass
public static void before {
// Do stuff
}
@AfterClass
public static void after {
// Do stuff
}
}
```
By firing the TestRunFinished event and printing the summary directly
after invoking the children rather then after the completion of the
whole test run these are made equivalent again.
Firing the TestRunFinished event before the JUnit execution 
is done might …
> [JUnit] Invoke (Before|After)Class and TestRules around Cucumber execution

- android/pom.xml
- clojure/pom.xml
- core/pom.xml
- examples/android/cukeulator/pom.xml
- examples/pax-exam/calculator-api/pom.xml
- examples/pax-exam/calculator-service/pom.xml
- examples/pax-exam/calculator-test/pom.xml
- gosu/pom.xml
- groovy/pom.xml
- guice/pom.xml
- java8/pom.xml
- jruby/pom.xml
- junit/pom.xml
- jython/pom.xml
- kotlin-java8/pom.xml
- needle/pom.xml
- openejb/pom.xml
- osgi/pom.xml
- picocontainer/pom.xml
- rhino/pom.xml
- scala/pom.xml
- scala/scala_2.10/pom.xml
- scala/scala_2.11/pom.xml
- scala/scala_2.12/pom.xml
- spring/pom.xml
- testng/pom.xml
- weld/pom.xml
Maven relies on convention over configuration. By convention the
`relativePath` is `../pom.xml` and can be ommited from the pom file[1].
References:
1. https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Project_Inheritance
> Remove relative path to parent pom

- core/src/main/java/cucumber/runtime/formatter/PrettyFormatter.java
- core/src/test/java/cucumber/runtime/formatter/PrettyFormatterTest.java
Do not throw StringIndexoutOfBoundsException in PrettyFormatter for nested capture groups.
Format nested arguments as part of already formatted enclosing argument.
Reproduced issue #619 with (now removed) test that expects a StringIndexOutOfBoundsException.
Added 2 tests to verify formatting of nested capture groups and added some checks on variables passed to substring() to prevent StringIndexOutOfBoundsException.
Additionally, minor refactor (renamed these variables) for clarity.
(Additionally, fixed a typo in PrettyFormatterTest)
Nested capture groups could not be handled by the PrettyFormatter. Since each capture groups maps to an argument, this sort of gives an argument in an argument. A nested argument starts before the enclosing argument ends, throwing a …
> Fix PrettyFormatter Exception for nested capture groups

- core/src/main/java/cucumber/runtime/formatter/PrettyFormatter.java
- core/src/test/java/cucumber/runtime/JdkPatternArgumentMatcherTest.java
- core/src/test/java/cucumber/runtime/formatter/PrettyFormatterTest.java
Fixed to ignore formatting for nested capture groups (arguments), as they are already formatted as an argument as part of the enclosing capture group (argument), thus no longer throwing StringIndexOutOfBoundsException which prevented additional scenarios/ features from running (#619).
Added 2 tests to verify formatting of nested capture groups
Added 2 checks on variables passed to substring() to prevent StringIndexOutOfBoundsException (see more below).
Also did a minor refactor (=renamed these variables) for clarity.
Additionally, fixed a typo in PrettyFormatterTest
Nested capture groups could not be handled by the PrettyFormatter. Since each capture groups maps to an argument, this sort of gives an argument in an argument. A nested argument starts before the enclosing argument ends, …
> [Core] Fix PrettyFormatter exception on nested arguments

- CHANGELOG.md
In line with https://github.com/cucumber/cucumber/issues/251: At the top of each CHANGELOG.md, please include a link to the monorepo's CONTRIBUTING.md.
> Update CHANGELOG.md with link to CONTRIBUTING.md (cucumber/cucumber#251)

- CHANGELOG.md
- java/src/main/java/cucumber/runtime/java/JavaSnippet.java
- java/src/test/java/cucumber/runtime/java/JavaSnippetTest.java
Tests are allowed to fail by throwing an(y) exception. As such #318
added `throws Throwable` to the JavaSnippet. Aside from being a bad
practice this results in unnecessary checkstyle warnings. As such the
generated snippet should not explicitly declare `Throwable`.
Reducing `Throwable` to `Exception` should be sufficient.
Fixes #1207
Updated the Unit Tests.
> Reduce Throwable to Exception in JavaSnippet

- .travis.yml
- core/src/main/java/cucumber/api/Result.java
- core/src/main/java/cucumber/api/event/EventListener.java
- core/src/main/java/cucumber/api/event/EventPublisher.java
- testng/src/main/java/cucumber/api/testng/AbstractTestNGCucumberTests.java
Generating javadoc using command 'mvn javadoc:aggregate' under java 8
fails if the javadoc tags are incomplete. To ensure the javadoc remains
complete we include it in the build.
Fixes #1209
> Include javadoc in the build

- core/src/main/java/cucumber/runtime/ScenarioImpl.java
- core/src/test/java/cucumber/runtime/ScenarioResultTest.java
Adapt `Scenario.isFailed()` to change in `Scenario.getStatus()`.
Fixes #1215.
> Fix Scenario.isFailed

- core/src/test/java/cucumber/runtime/formatter/HTMLFormatterTest.java
Rename and add test for HTMLFormatter
Trying to duplicate / fix https://github.com/cucumber/cucumber-jvm/issues/729 
Cannot reproduce this bug by setting Locale for my laptop, or running the test with VM options: -Duser.language=fr (or nl, for that matter). Only by explicitly setting the Locale in the test (see previous PR).
The original test does not validate that report.js is valid; it validates that an empty report throws a particular exception. I've renamed this test.
As suggested, I've added a test that does check for valid Javascript. I'm not sure this adds a lot of value, as other tests are also checking for valid js.
'mvn clean install' => Build Success
N/A
> Rename and add test for  HTMLFormatter

- java8/src/main/java/cucumber/runtime/java8/Java8StepDefinition.java
The api allows `StackTraceElement.getFileName()`[1] to return null. We
were not able to reproduce this problem reliably but it occurred in
production environments anyway.
Fixes #1217
References:
1. docs.oracle.com/javase/7/docs/api/java/lang/StackTraceElement.html#getFileName()
> Fix NullPointerException at Java8StepDefinition.isDefinedAt

- core/src/main/java/cucumber/api/TestCase.java
- core/src/main/java/cucumber/runner/Runner.java
- core/src/test/java/cucumber/api/TestCaseTest.java
- core/src/test/java/cucumber/runner/RunnerTest.java
> Skip test step execution if --dry-run is specified

- core/src/main/java/cucumber/api/DataTable.java
- core/src/main/java/cucumber/api/TableConverter.java
- core/src/main/java/cucumber/api/TestCase.java
- core/src/main/java/cucumber/api/TestStep.java
- core/src/main/java/cucumber/runtime/StepDefinitionMatch.java
- core/src/main/java/cucumber/runtime/table/DataTableDiff.java
- core/src/main/java/cucumber/runtime/table/TableConverter.java
Deprecate constructors and run methods of TestCase and TestStep and extract an interface for DataTable.
Test(Case|Step) is exposed because it is part of the event bus protocol. However its constructors and run method have no general public use. As such they should not be part of the public api. In the long run Test(Case|Step) should be replaced with an interface.
TableConverter is not part of the public api but is used by DataTable.
By extracting the interface we can hide the details of how a data table
converts its data.
This will also be usefull once we start moving away from xstream as we
can introduce an XStreamTableConverter and SomeOtherTableConverter.
Keeping the public API neat, focused and clean will make it easier to maintain it in the future.
> Clean up public API

- examples/android/android-studio/Cukeulator/README.md
- examples/android/android-studio/Cukeulator/app/build.gradle
The Gradle dependencies group is outdated on the Android Studio sample
I updated it following the @mpkorstanje feedback
This sample project does not compile today. This fixes the problem
Tested on Mac with the current project's configuration. The host platform should not imply a different behaviour.
> Fix the gradle dependencies group

- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/test/java/cucumber/runtime/formatter/JSONFormatterTest.java
JSON formatter outputs the embeddings node as "embedding". Version 1.2.5 and earlier had this node as "embeddings"
`embedding` node changed to `embeddings` in JSONFormatter.java
Fixes #1235.
This is required for `cucumber-reporting` plugin
Existing tests have been updated
> Correct the name of the Json Formatter embeddings node

- core/pom.xml
- gosu/pom.xml
- groovy/pom.xml
- guice/pom.xml
- java/pom.xml
- junit/pom.xml
- jython/pom.xml
- needle/pom.xml
- osgi/pom.xml
- pom.xml
- rhino/pom.xml
- spring/pom.xml
- spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java
- spring/src/test/java/cucumber/runtime/java/spring/SpringFactoryTest.java
- spring/src/test/java/cucumber/runtime/java/spring/componentannotation/WithComponentAnnotation.java
- spring/src/test/java/cucumber/runtime/java/spring/componentannotation/WithControllerAnnotation.java
- testng/pom.xml
When step definitions are annotated with `@Component` or other related
annotations they can be picked up by springs class path scanning. This
conflicts with cucumbers class path scanning and may result in
multiple bean definitions for the same class.
This problem is hard to understand and hard to trace. By making the
problem explicit and providing a clear instruction on how to resolve
this we can hopefully avoid future confusion.
The current implementation only checks the a subset of all annotations.
This will hopefully be sufficient.
Closes #1225
> [Spring] Throw when step definitions have the Component stereotype

- java/src/main/java/cucumber/runtime/java/MethodScanner.java
Optimized MethodScanner.scan method to not unnecessarily check for all cucumber annotations
MethodScanner scans each method for existence of cucumber annotation (there are many). It is redundant and slow because only methods with Before/After or StepDefAnnotation are added to backend. 
On Android < 7.0 it is extremely slow, and starting with debugger is almost impossible. I've measured it and optimized method is about 150 times faster on Android <7.0 and about 10 times faster on Android >=7.0
MethodScannerTest passes. 
I've also tested it on my Android project and it works (and it is much more faster)
> [Core] Optimize MethodScanner

- core/src/test/java/cucumber/runtime/formatter/JUnitFormatterTest.java
- pom.xml
Use gherkin 5.0.0
Gherkin 5.0.0 will create an empty pickle for an empty scenario. See: https://github.com/cucumber/gherkin-java/commit/f9a0ef04e109b5afd30436b579896e2e8558ba72 However a feature without scenario's still doesn't run any thing. The JUnit test has been updated accordingly.
With the release of gherkin 5.0.0 the build broke. Due to some black magic in pax-exam the osgi maven bundles will always try to resolve the latest version unless specific version numbers are used. Upgrading gherkin was the easiest way out.
Ran the tests. Fixed the tests.
> Use gherkin 5.0.0

- core/src/main/java/cucumber/runtime/Timeout.java
- core/src/test/java/cucumber/runtime/TimeoutTest.java
We need to ensure a happens before relation exists between these events;
a. the timer setting the interrupt flag on the execution thread.
b. terminating and cleaning up the timer
To do this we synchronize on monitor. The atomic boolean is merely a
convenient container.
Additionally Timeout did not throw any exceptions when the callback
was busy waiting but did set the interrupted flag. To resolve this
we check and throw after the completion of the callback.
This fixes #1241
> [Core] Fix race condition in Timeout

- java/src/main/java/cucumber/runtime/java/JavaBackend.java
- java/src/main/java/cucumber/runtime/java/LambdaGlueRegistry.java
- java8/src/main/code_generator/I18n.java8.txt
- java8/src/main/java/cucumber/runtime/java8/Java8StepDefinition.java
- java8/src/test/java/cucumber/runtime/java8/Java8LambdaStepDefinitionMarksCorrectStackElementTest.java
- java8/src/test/java/cucumber/runtime/java8/SomeLambdaStepDefs.java
Fixes Java8StepDefinition.isDefinedAt as reported in #1254.
While replacing ConstantPoolTypeIntrospector with TypeResolver in 657ce3a49304e226da406fe4aa0413898d28747f the creation of the Java8StepDefinition was moved from the JavaBackend to the generated step definition.
This removed one stack element between the invocation of the Lambda (e.g. `Given(....)`) and the creation of the Java8StepDefinition.
Extracted LambdaGlueRegistry to make a unit test possible.
>  Fix Java8StepDefinition.isDefinedAt

- spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java
- spring/src/test/java/cucumber/runtime/java/spring/SpringFactoryTest.java
Deprecate Spring context configuration by more than one class
Print a warning if more than one glue class that attempts to configure the Spring context is found (that is have a `@ContextConfiguration` or `@ContextHierarcy` annotation.
We have decided to only allow one glue class to configure the Spring context, as this is a non-backward compatible change, it will be introduced in v3.0.0 (#1246). Until then a deprecation warning should be printed.
The automated test suite has been updated to verify this behavior.
> Deprecate Spring context configuration by more than one class

- spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java
Fixes #1242
Fixes #1061
Spring annotations are hierarchical and can be customized. This
requires that the entire graph is scanned to determine if one of
the supported annotations is present.
> [Spring] Support BootstrapWith annotation

- core/src/main/java/cucumber/runner/Runner.java
- core/src/main/java/cucumber/runtime/ScenarioImpl.java
- core/src/test/java/cucumber/runner/RunnerTest.java
- core/src/test/java/cucumber/runtime/HookOrderTest.java
- core/src/test/java/cucumber/runtime/HookTest.java
- core/src/test/java/cucumber/runtime/ScenarioResultTest.java
Running empty Pickles should yield the result undefined.
Gherkin v5 does create empty Pickles for Scenarios with no steps. Running these empty Pickles should yield the result undefined, and no test steps should be executed.
See cucumber/cucumber#249 and https://github.com/cucumber/cucumber-ruby-core/pull/144#issuecomment-323510760 for background
The automated test suite has been updated to verify this behavior.
I have also manually/locally added an empty scenario to the Java calculator example to check that it indeed yielded an undefined scenario in the summary count.
> [Core] Running empty Pickles should yield the result undefined.

- core/src/main/java/cucumber/api/Plugin.java
- core/src/main/java/cucumber/api/SummaryPrinter.java
- core/src/main/java/cucumber/api/formatter/ColorAware.java
- core/src/main/java/cucumber/api/formatter/Formatter.java
- core/src/main/java/cucumber/api/formatter/StrictAware.java
- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/main/java/cucumber/runtime/formatter/PluginFactory.java
- core/src/main/java/cucumber/runtime/formatter/PrettyFormatter.java
- core/src/main/java/cucumber/runtime/formatter/ProgressFormatter.java
- core/src/main/java/cucumber/runtime/formatter/RerunFormatter.java
- core/src/main/java/cucumber/runtime/formatter/TestNGFormatter.java
- core/src/main/java/cucumber/runtime/formatter/UsageFormatter.java
Update Plugin documentation
Moved the Plugin specifications from the PluginFactory to the interface. Requirements imposed on a class should be documented on its interface rather then the factory that creates it.
> Update Plugin documentation

- CHANGELOG.md
- testng/src/main/java/cucumber/api/testng/AbstractTestNGCucumberTests.java
Using invalid options through `cucumber.option` would cause the
creation of `testNGCucumberRunner` to fail with an exception. However
this exception does not terminate TestNGs execution. This caused
additional exceptions in the data provider and tear down methods. The
additional exceptions were mistaken for the root cause, creating some
confusion.
Output when using some invalid options
```
[TestNG] Running:
/home/mpkorstanje/.IntelliJIdea2017.2/system/temp-testng-customsuite.xml
Usage: java cucumber.api.cli.Main [options] [[[FILE|DIR][:LINE[:LINE]*] ]+ | @FILE ]
Options:
-g, --glue PATH                        Where glue code (step definitions, hooks
and plugins) are loaded from.
-p, --[add-]plugin PLUGIN[:PATH_OR_URL]
Register a plugin.
Built-in formatter PLUGIN types: junit,
html, …
```
> Fix null pointer exception in TestNG when invalid options are used

- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/test/java/cucumber/runtime/formatter/JSONFormatterTest.java
- core/src/test/resources/cucumber/runtime/formatter/JSONPrettyFormatterTest.json
Add feature tags in the JSON result of the JSON Formatter
New JSON field named "tags" in feature section
Cucumber 1.x JSON reports contain feature tags.
We use feature tags to keep our features organized.
Updated JSON Formatter unit tests
> Add feature tags in the JSON output

- core/src/main/java/cucumber/runtime/RuntimeGlue.java
- core/src/main/java/cucumber/runtime/StepDefinitionMatch.java
- core/src/test/java/cucumber/runtime/RuntimeGlueTest.java
This is a performance improvement in `RuntimeGlue.stepDefinitionMatches` method which is very slow on Android < 8.0 and with large test base
`stepDefinitionMatches` iterates through all steps definitions to find all definitions that match current `PickleStep` (by testing if step text matches regular expression of step definition) - lots of steps doesn't have arguments or have only table argument or are used with same arguments - this implies that matching `StepDefinition` for them can be safely cached to avoid repeating of iteration through all definitions and receiving the same results.
I've added simple cache where step text is a key and `StepDefinition` and `List<Argument>` are value. When a step with the same text is being processed then its definition is taken from cache.
E.g. in my …
> cache matched steps definitions in RuntimeGlue

- core/src/main/java/cucumber/api/CucumberOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptionsFactory.java
- core/src/main/resources/cucumber/api/cli/USAGE.txt
- examples/java-calculator-testng/src/test/java/cucumber/examples/java/calculator/RunCukesByCompositionTest.java
Remove the deprecated `-f`/`--format` option.
Remove the deprecated `-f`/`--format` option.
The `-f`/`--format` option has been deprecated in favor of the `-p`/`--plugin` option since v1.2.0. Since it was not removed in v2.0.0, it should be removed in v3.0.0.
Manually tested that `-Dcucumber.options="-f pretty"` to the Java calculator example resulted in expected error message.
> Remove the deprecated -f/--format option

- core/src/main/java/cucumber/runtime/RuntimeGlue.java
- core/src/test/java/cucumber/runtime/RuntimeGlueTest.java
- examples/java-calculator-testng/pom.xml
- examples/java-calculator/pom.xml
- examples/java8-calculator/pom.xml
- examples/java8-calculator/src/main/java/cucumber/examples/java/calculator/RpnCalculator.java
- examples/java8-calculator/src/test/java/cucumber/examples/java/calculator/RpnCalculatorStepdefs.java
- examples/java8-calculator/src/test/java/cucumber/examples/java/calculator/RunCukesTest.java
- examples/java8-calculator/src/test/java/cucumber/examples/java/calculator/ShoppingStepdefs.java
- examples/java8-calculator/src/test/resources/cucumber/examples/java/calculator/basic_arithmetic.feature
- examples/java8-calculator/src/test/resources/cucumber/examples/java/calculator/shopping.feature
- examples/pom.xml
- java8/pom.xml
Remove scenario scoped step definitions from step definition cache This fixes a bug in cucumber 2.3.0 where the cache would serve up a lambda step definition from a previous step.
Added a unit test and java8 examples. Features used by cucumber-java8, specifically glue coded step
definitions, were not used in integration tests. Adding these should allow us to discover java8 related problems quicker.
> Remove scenario scoped step definitions from step definition cache

- junit/README.md
- junit/src/main/java/cucumber/api/junit/Cucumber.java
> Add readme to cucumber-junit

- java/src/main/java/cucumber/runtime/java/JavaSnippet.java
- java/src/test/java/cucumber/runtime/java/JavaSnippetTest.java
Remove 'throws Exception' from JavaSnippet method signature's `throws` clause.
Remove 'throws Exception' from JavaSnippet method signature's `throws` clause.
Update corresponding Unit Tests.
As discussed on Slack #help-cucumber-jvm channel Nov 8th, 2017 (summarized): 
Autogenerated step definition snippets usually contain “throws Throwable”, although in most cases IDEA shows them as unused (exception is never thrown by this method). They were added to avoid people to add try catch like wrap their stepdef bodies in try-catch, which is why it was made to throw liberally.
By running 'mvn clean install' and verifying that the build is successful.
> Remove 'throws Exception' from JavaSnippet method signature

- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/test/java/cucumber/runtime/formatter/JSONFormatterTest.java
Include the content type of a doc string in the Json Formatter output (if the content type of the doc string is defined in the feature file).
The content type of the doc strings (if defined in the feature file) is not defined in the Pickles, so the Json Formatter need to fetch in based on the feature file AST.
In Cucumber-JVM v1.x.x the content type of doc strings were included in the Json Formatter output (if defined in the feature file).
The automated test suite has been updated to verify this behavior.
> [Core] Json Formatter: include the content type of doc strings

- core/src/main/java/cucumber/runtime/HookComparator.java
- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- examples/spring-txn/pom.xml
- guice/src/test/java/cucumber/runtime/java/guice/impl/GuiceFactoryTest.java
- pom.xml
This is a partial fix for #1311 and addresses a few minor issues that occur when trying to build and run with Java 9.
Don't use wildcard imports
The wildcard import of `com.google.inject.Module` clashes with `java.lang.Module` in Java 9.
Inline `@since 1.7` methods
JDK9 strictly checks if the byte code target and api usage are consistent. `Integer.compare` and `System.lineSeperator()` are not available at 1.6.
Add explicit dependency on `jaxb-api`
Java 9 added the Jigsaw module system and moved java.xml.bind into a module. This module is not active by default. It can be be activated by running with --add-modules java.xml.bind however as it is scheduled to be removed in Java 10 it is prudent to migrate away from it now.
> Partial Java 9 clean up

- examples/README.md
- examples/java-helloworld/README.md
Remove helloworld example and point straight to skeleton project
Current situation: the README in examples folder points to the java-helloworld example, which in turn points to the cucumber-java-skeleton.
New: Point straight to skeleton project from the examples README
Makes it easier & faster to get to the easiest example project.
Text change only.
Visual check on the README locally, including verifying that the link to skeleton project works.
> Remove helloworld example and point straight to skeleton project

- core/src/main/java/cucumber/runtime/formatter/RerunFormatter.java
Fixed typo in cucumber.runtime.formatter.RerunFormatter: missing 'l' in  handeTestCaseFinished 
Just don't want to see warnings in IDE
I just checked that all test are still green
> Fix a small typo: handeTestCaseFinished -> handleTestCaseFinished

- examples/pom.xml
- pom.xml
Use RevApi to check api changes in `cucumber.api.*`. This should make it
easier to determine if the next release includes breaking api changes.
Introducing API changes that are not in line with the semantic version 
difference will break the build.
> [Build] Automate api change checking

- core/src/main/java/cucumber/api/CucumberOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptionsFactory.java
- core/src/main/resources/cucumber/api/cli/USAGE.txt
- examples/java-calculator-testng/src/test/java/cucumber/examples/java/calculator/RunCukesByCompositionTest.java
Remove the deprecated `-f`/`--format` option.
Remove the deprecated `-f`/`--format` option.
The `-f`/`--format` option has been deprecated in favor of the `-p`/`--plugin` option since v1.2.0. Since it was not removed in v2.0.0, it should be removed in v3.0.0.
Manually tested that `-Dcucumber.options="-f pretty"` to the Java calculator example resulted in expected error message.
> [Core] Remove the deprecated -f/--format option.

- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- core/src/test/java/cucumber/runtime/formatter/JUnitFormatterTest.java
https://github.com/cucumber/cucumber-jvm/issues/1326
> [Core] Remove 'dummy' results from junit formatter

- junit/src/main/java/cucumber/api/junit/Cucumber.java
Neither the runtime nor the backend or any of the classes involved in
their construction are part of the public API. As such they should not
be  exposed.
The recommended way to observe the cucumber process is to listen to
events by using a plugin. For example the JSONFormatter.
> [JUnit] Remove Cucumber.createRuntime method

- core/src/main/java/cucumber/api/TestStep.java
- testng/src/main/java/cucumber/api/testng/TestCaseResultListener.java
- testng/src/test/java/cucumber/api/testng/TestCaseResultListenerTest.java
Let a `org.testng.SkipException` thrown from a test step make the result of that test step skipped.
Let a `org.testng.SkipException` thrown from a test step make the result of that test step skipped.
Also use the `SkipException` to signal to the TestNG runner that the test should be considered as skipped, for instance Pending and Undefined test cases in non-strict-mode.
The JUnit exception (`org.junit.AssumptionViolatedException`) has been supported by Cucumber-JVM for some time. Cucumber-JVM should also support the corresponding TestNG exception ([`org.testng.SkipException`](https://jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/SkipException.html)).
In addition to the updated in the automated test suite, the changes has been manually tested using the …
> [Core, TestNG] Support the TestNG SkipException

- junit/README.md
- testng/README.md
Update testng and junit readme with information from #1338 and #1339
> [TestNG, JUnit] Update testng and junit readme

- core/src/main/java/cucumber/runtime/Stats.java
- core/src/main/resources/cucumber/api/cli/USAGE.txt
- core/src/test/java/cucumber/runtime/RuntimeTest.java
Fixed an issue where a successful runtime **exit status (0x0)** is returned for ambiguous scenarios when runtime option '**strict**' is set to true.
When using the Cucumber CLI and an **AmbiguousStepDefinitionsException** is raised, the runtime exit status is **0x0** even though runtime option '**strict**' is set to true.
The runtime exit status should be **0x1** when **isStrict**
Yes - 2 new tests added.
> [Core Bug Fix] Fixed runtime exit status for ambiguous scenarios

- core/src/main/java/cucumber/api/Plugin.java
- core/src/main/java/cucumber/api/Transpose.java
- core/src/main/java/cucumber/api/event/TestStepFinished.java
- core/src/main/java/cucumber/runtime/NoStepDefinition.java
- core/src/main/java/cucumber/runtime/StepDefinition.java
- core/src/test/java/cucumber/runtime/StubStepDefinition.java
- java/src/main/java/cucumber/runtime/java/JavaStepDefinition.java
- java/src/main/java/cucumber/runtime/java/ParameterInfo.java
- java8/src/main/java/cucumber/runtime/java8/Java8StepDefinition.java
- java8/src/main/java/cucumber/runtime/java8/ParameterInfo.java
- junit/src/main/java/cucumber/api/junit/Cucumber.java
- pom.xml
Clean up unused methods in step definition. Split up parameter type determination into java and java8 specific parts and fix java documentation related to `@Transpose`.
> [Core] Clean up step definition

- examples/android/android-studio/Cukeulator/app/build.gradle
There is a missing closing quote in cucumber-jvm/examples/android/android-studio/Cukeulator/app/build.gradle file
I had added the missing quote to avoid the following error message when I run tests:
```
Task :app:deleteExistingCucumberReports
/system/bin/sh: no closing quote
/system/bin/sh: no closing quote
/system/bin/sh: no closing quote
```
Run tests and there is no more **no closing quote** error
- [X ] Bug fix (non-breaking change which fixes an issue).
> Add missing closing quote

- openejb/pom.xml
- pom.xml
Cucumber-jvm is using some library features that were introduced in Java 7.
Setting the compilation explicitly to Java 7 should avoid any unexpected
surprises.
Java 6 has reached its end of life a while ago and we no longer run our tests against it. Supporting it has become impractical.
Check if the automated tests were still passing. 
Check manually if the Android studio example works
> [Build] Use 1.7 as the source and target level for compilation

- examples/java-gradle/README.md
- examples/java-gradle/build.gradle
Remove Gradle code that does not bring any benefit
- remove unused dependency configuration
cucumberRuntime was declared but no dependencies were put into it
- proper dependencies for cucumber task
testCompile processes all main and test sources, not only Java
The example did not look like well-formed Gradle build script.
`gradle test` and `gradle cucumber` still work
> [Examples] Simplify Gradle example

- weld/src/test/java/cucumber/runtime/java/weld/BellyStepdefs.java
For injecting classes from `src/main/java` into glue code in `src/test/java`, two `beans.xml` files are required.
This is not trivial and should be documented in order to avoid confusion.
This PR adds documentation about where to place the `beans.xml` for selected injection scenarios.
> [Weld] Document the need for a beans.xml per source root

- core/src/main/java/cucumber/api/Plugin.java
Update Plugin docs to reflect that all other interfaces are optional
> [Core] Update Plugin docs

- core/src/main/java/cucumber/api/CucumberOptions.java
- core/src/main/java/cucumber/runtime/RuntimeOptionsFactory.java
- core/src/test/java/cucumber/runtime/RuntimeOptionsFactoryTest.java
Added extraGlue option to @CucumberOptions
This option works similarly to glue, specifing packages in which to search for steps and hooks, but the default search path (the current package) is included in the list of glue packages, whereas glue includes only the explicitly listed packages.
Closes #1438.
I've added tests to RuntimeOptionsFactoryTest.java.
`mvn clean install` is successful.
The only documentation I've found is JavaDocs in CucumberOptions.java; the new option is documented there.
> Added extraGlue option to @CucumberOptions

- core/src/main/java/cucumber/runner/Runner.java
- core/src/main/java/cucumber/runtime/Backend.java
- core/src/main/java/cucumber/runtime/snippets/SnippetGenerator.java
- core/src/test/java/cucumber/runner/TestBackendSupplier.java
- core/src/test/java/cucumber/runner/TestRunnerSupplier.java
- core/src/test/java/cucumber/runtime/StubBackend.java
- core/src/test/java/cucumber/runtime/formatter/JSONFormatterTest.java
- java/src/main/java/cucumber/runtime/java/JavaBackend.java
- java/src/test/java/cucumber/runtime/java/Java8SnippetTest.java
- java/src/test/java/cucumber/runtime/java/JavaSnippetTest.java
- java/src/test/java/cucumber/runtime/java/StringJoiner.java
- junit/src/test/java/cucumber/runtime/stub/StubBackend.java
- testng/src/test/java/cucumber/runtime/stub/StubBackend.java
Use all generated snippets
Fixes #1433
> [Core] Use all generated snippets

- examples/java-calculator-testng/src/test/java/cucumber/examples/java/calculator/RunCukesTest.java
- examples/java-calculator/pom.xml
- junit/README.md
- testng/README.md
Document how to enable parallel execution for JUnit and TestNG
> [JUnit,TestNG] Update documentation

- core/src/main/java/cucumber/runtime/Shellwords.java
- core/src/test/java/cucumber/runtime/ShellwordsTest.java
Found `@Ignore("TODO: fixme")` so thought I would solve it.
Shellwords takes the program arguments and splits them into separate strings but still groups words bound by `"` or `'`
What to help, was looking at helping test code coverage.
`mvn clean install` still passes
458 tests within code pass but now it doesn't have 3 ignored
> [Core] Parse qouted strings from cucumber.options

- core/pom.xml
- core/src/test/java/io/cucumber/core/options/RuntimeOptionsFactoryTest.java
- core/src/test/java/io/cucumber/core/runner/FailedStepInstantiationMatchTest.java
- core/src/test/java/io/cucumber/core/runner/UndefinedStepDefinitionMatchTest.java
- core/src/test/java/io/cucumber/core/runtime/InvokerTest.java
- core/src/test/java/io/cucumber/core/snippets/FunctionNameGeneratorTest.java
- guice/pom.xml
- guice/src/test/java/io/cucumber/guice/collection/CollectionUtilTest.java
- java/pom.xml
- java/src/test/java/io/cucumber/java/JavaBackendTest.java
- java/src/test/java/io/cucumber/java/JavaStepDefinitionTest.java
- junit/pom.xml
- junit/src/test/java/io/cucumber/junit/AssertionsTest.java
- junit/src/test/java/io/cucumber/junit/CucumberTest.java
- needle/pom.xml
- needle/src/test/java/io/cucumber/needle/config/CreateInstanceByDefaultConstructorTest.java
- needle/src/test/java/io/cucumber/needle/config/LoadCucumberNeedleResourceBundleTest.java
- pom.xml
Upgrade to Junit 5 and use assertThrows for tests checking exception, now branch using Java 8.
Checked test count before matches test count after.
Checked test all still pass
> Upgrade to Junit 5 and use assertThrows

- java/src/main/groovy/annotation.java.gsp
- java/src/main/groovy/lambda.java.gsp
- java/src/main/java/io/cucumber/java/Function.java
- java/src/main/java/io/cucumber/java/GlueBase.java
- java/src/main/java/io/cucumber/java/JavaBackend.java
- java/src/main/java/io/cucumber/java/LambdaGlue.java
- java/src/main/java/io/cucumber/java/LambdaGlueRegistry.java
- java/src/main/java/io/cucumber/java/MethodScanner.java
- java/src/main/java/io/cucumber/java/StepDefAnnotations.java
- java/src/test/java/io/cucumber/java/Java8LambdaStepDefinitionMarksCorrectStackElementTest.java
- java/src/test/java/io/cucumber/java/JavaBackendTest.java
- java/src/test/java/io/cucumber/java/lambda/AnonInnerClassStepdefs.java
- java/src/test/java/io/cucumber/java/repeatable/Stepdefs.java
Adds the support for repeatable step definition annotations to
the `JavaBackend` e.g.:
```java
@When("the customer opens his account")
@When("the account is opened by the customer")
public void open_account() {
}
```
Resolves part of #1447.
> [Java] Add repeatable annotations

- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/test/java/cucumber/runtime/formatter/JSONFormatterTest.java
Docstring content type is currently not carried down into the json formatter. 
This worked in 1.2.5.
PickleString did not have the corresponding field, so I added that in:
https://github.com/cucumber/cucumber/pull/292
(*The mono repo PR is required for this one to compile, so this will fail CI*). 
https://github.com/cucumber/cucumber-jvm/issues/1263
Fixing this bug. 
Passes the contentType field down into the map that gets json serialized.
Uses the content_type name to match 1.2.5 and other language reports.
https://github.com/cucumber/cucumber-jvm/issues/1263
Unit test added. 
All tests run, Pax Exam Calculator Test appears to be broken before this change, due to a deployment issue?
I do not know if any docs need changing. I expect not as this is a regression from 1.2.5
> cucumber-core: Use the docstring content type in the json formatter.

- CHANGELOG.md
- core/src/main/java/io/cucumber/stepexpression/StepExpressionFactory.java
- core/src/main/java/io/cucumber/stepexpression/TypeResolver.java
- core/src/test/java/io/cucumber/stepexpression/StepExpressionFactoryTest.java
- java8/src/main/java/cucumber/runtime/java8/Java8StepDefinition.java
- java8/src/main/java/cucumber/runtime/java8/ParameterInfo.java
- java8/src/test/java/cucumber/runtime/java8/Java8LambdaStepDefinitionTest.java
Apply identity transform when target type is unknown 
When using groovy in combination with `cucumber-java8` there is no type information available at all because:
```groovy
public class Stepdefs implements En {
Stepdefs() {
Given(/^this docstring:$/, { String s ->
println s
} as A1)
}
}
```
is compiled into:
```java
public class Stepdefs implements En, GroovyObject {
public Stepdefs() {
CallSite[] var1 = $getCallSiteArray();
super();
MetaClass var2 = this.$getStaticMetaClass();
this.metaClass = var2;
var1[0].callCurrent(this, "^this docstring:$", ScriptBytecodeAdapter.createPojoWrapper((A1)ScriptBytecodeAdapter.asType(new Stepdefs._closure1(this, this), A1.class), A1.class));
}
public final class _closure1 extends Closure implements GeneratedClosure {
public _closure1(Object …
```
> [Java8] Apply identity transform when target type is unknown 

- CHANGELOG.md
- core/src/main/java/io/cucumber/stepexpression/StepExpressionFactory.java
- core/src/main/java/io/cucumber/stepexpression/TypeResolver.java
- core/src/test/java/io/cucumber/stepexpression/StepExpressionFactoryTest.java
- java8/src/main/java/cucumber/runtime/java8/Java8StepDefinition.java
```java
@Given("a doc string:")
public void given_a_doc_string(Object docString){
}
@Given("a data table:")
public void given_a_data_table(Object table){
}
```
Results in an error telling us that Cucumber doesn't know how to transform an instance of `String` or `Datatable` to `Object`. This is a bit silly.
> [Core] Apply identity transform to Argument when type is Object

- core/src/main/java/cucumber/api/HookType.java
- core/src/main/java/cucumber/api/Result.java
- core/src/main/java/cucumber/runtime/Env.java
- core/src/main/java/cucumber/util/Encoding.java
- junit/src/main/java/cucumber/runtime/junit/NotificationLevel.java
Several plugins use lowercased string representations of enum
values. Doing this without an explicit locale results in the
default locale being used. This may lead to surprising errors.
Fixes: https://github.com/cucumber/cucumber-java-skeleton/issues/33
> [Core] Use Locale.ROOT when transforming case of identifiers

- guice/src/main/java/cucumber/api/guice/CucumberModules.java
- guice/src/main/java/cucumber/api/guice/CucumberScopes.java
- guice/src/main/java/cucumber/api/guice/package.html
- guice/src/test/java/cucumber/runtime/java/guice/impl/GuiceFactoryTest.java
- guice/src/test/java/cucumber/runtime/java/guice/integration/YourInjectorSource.java
- guice/src/test/java/cucumber/runtime/java/guice/integration/YourModule.java
Updating SequentialScenarioScope to use a threadlocal. This is to prevent issues when running cucumber in parallel mode.
Fixes: https://github.com/cucumber/cucumber-jvm/issues/1485
Have updated SequentialScenarioScope.class to use ThreadLocal to prevent it from thinking a scoping block is already in progress when running test from surefire with the parallel settings enabled.
This was preventing us from running our test suites with the new parallel running functionality of Cucumber4
Have tested this by using the new scope within our project.
I have also added tests which can be used to reproduce the exception and also prove the change.
Not sure if this is the best solution or has other implications, hoping somebody here can review and let me know if there is a better way.
> [Guice] Replace CucumberModules.SCENARIO with threadsafe factory method

- CHANGELOG.md
In line with mention of removal of Android from the project, let's make sure to explicitly mention when Scala, Groovy, Clojure, Jython, JRuby, Rhino, Gosu were moved to their own repos.
> Mention removal of Scala, Groovy, Clojure, Jython, JRuby, Rhino, Gosu

- core/src/main/java/cucumber/runner/Glue.java
- core/src/main/java/cucumber/runtime/MethodFormat.java
- core/src/test/java/cucumber/runner/GlueTest.java
- java/src/main/java/cucumber/runtime/java/JavaStepDefinition.java
Performance improvements in step definitions searching
- Allow caching of step definitions with arguments. It was previously disabled because of DocString and Table arguments. I've change it in such way to always create new arguments list from PickleStep but do not search for definition if step text is the same
- create some objects once in `JavaStepDefinition`
Improve performance of most often executed operations - `Glue.stepDefinitionMatches` is executed `step_definitions_count * average_steps_count_per_scenario * scenarios_count`
Tested on my Android project with 800 scenarios
> [Core] Cache all matched step defintions 

- core/src/test/java/cucumber/runner/TestHelper.java
- junit/src/test/java/cucumber/runtime/junit/PickleRunnerWithNoStepDescriptionsTest.java
- junit/src/test/java/cucumber/runtime/junit/TestPickleBuilder.java
- weld/src/main/java/cucumber/runtime/java/weld/WeldFactory.java
- weld/src/test/java/cucumber/runtime/java/weld/WeldFactoryTest.java
This PR fixes build on Windows machines #1551  when JVM is started with non-UTF8 as default charset and windows line endings.
Fixed wrong byte extraction in TestHelper, 
Fixed wrong byte extraction in TestPickleBulder plus added test that covers the change.
Fixed system-independent line ending in WeldFactory + WeldFactoryTest
Fixes: https://github.com/cucumber/cucumber-jvm/issues/1551
Build was run on a local machine.
> [Build] Fix windows build

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Updated the issue template to draw more attention to the fact that there are instructions written in it. This will hopefully reduce the frequency of questions and redirect people to the google groups.
Updated the readme to include a section about questions and where to ask them. Also changed the getting started section to be less verbose. Removed most of the guidance on creating an issue. It's already in the issue template and the contributing guidelines.
Added a line about discussing major changes first to the contribution guide.
Also formatted everything at 80 width.
> Update contribution guidlines

- core/src/main/resources/cucumber/api/cli/USAGE.txt
White space changes
Added blank lines between each option the make it easier to read the description for that particular option.
Indented the descriptions so they form a straight column.
Indented the options with two leading dashes so they are all in the same column.
When looking at the usage.txt when running the command line implementation with `--help` I was irritated about the indentation. It wasn't nice and unnecessary hard to read.
I reformatted the file and hope that it became easier to read.
Nope, it is a formatting change of the help text.
- [ x] I have updated the documentation accordingly.
> Reformatted usage.txt for easier readability

- core/src/main/java/io/cucumber/core/model/FeaturePath.java
- core/src/test/java/io/cucumber/core/model/FeaturePathTest.java
Added windows case where path is being passed with standard file separator in the file location passed.
Fixes: #1564 
Update for path in case it is being passed in Windows with the standard file separator, as Intellij appears to do.
> [Core] Disambiguate between drive letter and uri scheme

- core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java
- core/src/main/java/cucumber/runtime/formatter/TestNGFormatter.java
Fix concurrent access issues in JUnit and TestNG formatters
Both TestNGFormatter and JUnitFormatter use static fields internally to track the current state of the test. When parallel execution was introduced we accounted for this by storing all events until the end of the test run. This however doesn't work when there two tests running concurrently.
Removing the static fields resolves this.
Fixes: #1575
> [Core] Fix concurrent access issues in JUnit and TestNG formatters

- junit/pom.xml
- junit/src/main/java/cucumber/api/junit/Cucumber.java
- junit/src/test/java/cucumber/runtime/junit/CucumberTest.java
- junit/src/test/java/cucumber/runtime/junit/InvokeMethodsAroundEventsTest.java
Invoke @BeforeClass before TestRunStarted event
JUnit is running Cucumber so the expectation is that JUnit's
`@BeforeClass` and `@AfterClass` methods are invoked respectively before
and after all events emitted by Cucumber. However because the
`TestRunStarted` event was emitted in the constructor of `Cucumber` it
would precede the the invocation of `@BeforeClass`.
In older versions of Cucumber sending the `TestSourceRead` events was
coupled to reading the test sources. This made it impossible to read the
features ahead of time -required to to create the test description
tree and fail on lexer errors- and send `TestRunStarted` after
`@BeforeClass`.
This is no longer case since #1367 and so this problem can be resolved.
> [JUnit] Invoke @BeforeClass before TestRunStarted event

- core/src/main/java/cucumber/runtime/model/FeatureParser.java
- junit/src/test/java/cucumber/runtime/junit/CucumberTest.java
Adding the path to the resource for easier investigation during parsing exceptions in cucumber.
Added resource path to the exception thrown under `FeatureParser.parseResource()` method to allow user to see which file failed to parse.
Better user experience. It is useful to know which file caused the parser exception. Refer slack conversation 
> Nicolas   [Mar 30th at 3:03 AM]
> Hello! I'm starting off with cucumber-jvm and I've noticed that the Parser errors don't specify which `.feature` file is broken. Is there any way to enable this behavior? We're looking at adding multiple feature files at a time in a medium sized QA team and this would help out quite a bit. Thanks!
> 
> mpkorstanje   [8 days ago]
> And if you're willing to invest a little time you could probably submit a patch too: …
> [Core] Add more details to ParserException

- core/src/main/java/cucumber/runtime/model/FeatureBuilder.java
Between #165 and #259 cucumber would start to ignore duplicate features
by taking their MD5 sum and comparing newly parsed features. Replacing
the set of MD5 sums with a map of source to features simplifies the code
and allows duplicates to be logged as warnings.
I couldn't discover any good reason to use an MD5 hash over javas
`hashCode` and `equals`.
1) Memory consumption doesn't seem to be a problem. `CucumberFeature`
already keeps a reference the original source.
2) Collision doesn't appear to be a problem. `hashCode` produces a 32
bit hash. So by the birth-day paradox math we'd need approximately 9000
feature files for a 1% chance of collision.
> [Core] Simplify duplicate feature detection

- core/src/main/java/cucumber/runtime/io/ZipResource.java
Don't add an extra slash after the `classpath:` scheme
Changed the `ZipResource` to preserve the original path of the zipped entity.
I am running cucumber tests with features loaded from `classpath:`, like this:
```
java -cp fatjar.jar cucumber.api.cli.Main "classpath:features/FeatureWithExamples.feature:64"
```
However, when cucumber parses this path and creates a `ZipResource` from it, it adds an extra slash:
And the url becomes `classpath:/features/FeatureWithExamples.feature:64`
This becomes a problem down the line, when `LinePredicate` tries to filter out the pickles:
This if does't pass (because the key is not the one in the map) and instead of filtering the pickles out, it just lets all of the though the filter.
I tried changing the path to be …
> [Core] Fix filtering scenarios loaded from jar

- core/src/main/java/cucumber/runtime/Runtime.java
When running with --threads, give the the pool threads some meaningful names
Before it was using the standard threadfactory, which was naming threads like 'pool-x-thread-y'
Now it is 'cucumber-runner-thread-x'
It's better for logging to see which threads belong to cucumber and which are unrelated background threads
> [Core] Use meaningful thread names

- core/pom.xml
- core/src/main/java/cucumber/runtime/TooManyInstancesException.java
- core/src/main/java/io/cucumber/core/backend/ObjectFactory.java
- examples/java-calculator-testng/pom.xml
- examples/java-calculator/pom.xml
- examples/java-wicket/java-wicket-main/pom.xml
- examples/java-wicket/java-wicket-test/pom.xml
- examples/java-wicket/pom.xml
- examples/java8-calculator/pom.xml
- examples/pom.xml
- examples/spring-txn/pom.xml
- guice/pom.xml
- java/pom.xml
- java/src/main/java/cucumber/api/java/ObjectFactory.java
- java/src/main/java/cucumber/runtime/java/ObjectFactoryLoader.java
- java8/pom.xml
- junit/pom.xml
- kotlin-java8/pom.xml
- needle/pom.xml
- openejb/pom.xml
- picocontainer/pom.xml
- pom.xml
- spring/pom.xml
- testng/pom.xml
- weld/pom.xml
backport of commit a03dd01 for cucumber 4.x
Backport ServiceLoader for ObjectFactory to 4.x.
So it is possible to use ServciceLoader for ObjectFactory also with 4.x and must not be change when changed to 5.x. Easier migration to next major-version.
Difficult to test, have not found any test in develop-v5 for it .. and not sure how to provide a usefull test. Had test it with my own ObjectFactory (not public :( )
> [Java] Use ServiceLoader for ObjectFactory

- core/src/main/java/cucumber/runtime/CompositeCucumberException.java
- core/src/main/java/cucumber/runtime/Runtime.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
See https://github.com/cucumber/cucumber-jvm/issues/1628
That should fix the mentioned issue sufficiently.
There would be some nice-to-have improvements IMO, e.g. reporting all the exceptions if multiple threads failed and failing as early as possible instead of waiting for the termination of all the callables, but that would increase the complexity.
> [Core] Handle parallel execution exceptions

- core/src/main/java/cucumber/runtime/io/ZipResource.java
- core/src/test/java/cucumber/runtime/io/ZipResourceTest.java
Fix for error parsing feature file from jar when there is a space in path
Fixes: #1632
Unit test has been added. Also tested manually ;)
> [Core] Escape spaces in ZipResource path

- core/src/main/java/cucumber/runtime/RuntimeOptions.java
- core/src/test/java/cucumber/runtime/RuntimeOptionsTest.java
Fixes: #1630
Unit tests and a test run on my laptop
> [Core] Clear RuntimeOptions.featurePaths if rerun was used

- core/src/main/java/cucumber/api/StepDefinitionReporter.java
- core/src/main/java/cucumber/api/event/CanonicalEventOrder.java
- core/src/main/java/cucumber/api/event/EventPublisher.java
- core/src/main/java/cucumber/api/event/StepDefinedEvent.java
- core/src/main/java/cucumber/runner/Glue.java
- core/src/main/java/cucumber/runner/Runner.java
- core/src/main/java/cucumber/runtime/HookDefinition.java
- core/src/main/java/cucumber/runtime/ScenarioScoped.java
- core/src/main/java/cucumber/runtime/StepDefinition.java
- core/src/test/java/cucumber/runner/GlueTest.java
- core/src/test/java/cucumber/runtime/RuntimeTest.java
- java/src/main/java/cucumber/runtime/java/JavaBackend.java
- java8/src/main/java/cucumber/runtime/java8/Java8HookDefinition.java
- java8/src/main/java/cucumber/runtime/java8/Java8StepDefinition.java
Adds a `StepDefinedEvent` to replace the `StepDefinitionReporter` plugin interface.
Publish an event from `Glue.addStepDefinition`, as `Runner.reportStepDefinitions` is called before step definition classes are instantiated, which fails to pick up on lambda based steps.
Provide an event to listen for steps being registered, so all steps registrations are available, instead of only the annotation based step definitions.
https://github.com/cucumber/cucumber-jvm/issues/1633
Not yet; Change seems small.
> [Core] Add StepDefinedEvent

- core/src/main/java/cucumber/api/CucumberOptions.java
- core/src/main/java/cucumber/api/Result.java
- core/src/main/java/cucumber/runtime/formatter/AnsiFormats.java
- core/src/main/java/cucumber/runtime/formatter/PluginFactory.java
- core/src/main/java/cucumber/runtime/formatter/UnusedStepsSummaryPrinter.java
- core/src/main/resources/cucumber/api/cli/USAGE.txt
- core/src/test/java/cucumber/runtime/formatter/UnusedStepsSummaryPrinterTest.java
Adds a plugin to find and report on unused steps.
As discussed in https://github.com/cucumber/cucumber-jvm/pull/1634 it uses the new StepDefinedEvent to locate all registered steps, and prints a summary of unused steps to the argument file.
Allows to easily find unused steps, which might be indicative of removed functionality or missed test coverage.
Not yet; as @mpkorstanje indicated some hesitation on whether this would warrant adoption. This PR is to record that discussion, and will be updated depending on the outcome. Same goes for the current Java8 baseline, so it might need to target a future version rather than the next.
> [Core] Add UnusedStepsSummaryPrinter

- core/src/main/java/cucumber/api/formatter/NiceAppendable.java
- core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java
- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/main/java/cucumber/runtime/formatter/TimelineFormatter.java
- core/src/main/java/cucumber/runtime/formatter/UsageFormatter.java
Replaces `Gson.toJson(Object)` with `Gson.toJson(Object, Appendable)`.
This avoids the intermediate memory consuming string representation
of the json output.
Fixes: #1661
> [Core] Efficiently write JSON to output

- spring/README.md
- spring/src/main/java/io/cucumber/spring/GlueCodeScope.java
- spring/src/main/java/io/cucumber/spring/SpringFactory.java
- spring/src/main/java/io/cucumber/spring/api/CucumberTestContext.java
- spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
- spring/src/test/java/io/cucumber/spring/beans/GlueScopedComponent.java
Public constant for the glue scope.
The `io.cucumber.spring.api.CucumberTestContext` has the `SCOPE_CUCUMBER_GLUE` constant which holds the scope's name. The old private constant was deleted and the references were updated to the new one.
This fixes the #1660 as discussed there.
The `SpringFactoryTest#shouldGlueScopedSpringBeanBehaveLikeGlueLifecycle` tests the proper string name is made public by using it in `@Scope` and checking its lifecycle.
> [Spring] Add public constant for glue scope.

- CHANGELOG.md
Added missing deprecated for AbstractTestNGCucumberTests to changelog for version 4.5.0
* [TestNG] Deprecate `cucumber.api.testng.AbstractTestNGCucumberTests`
- Use `io.cucumber.testng.AbstractTestNGCucumberTests` instead.
> [Changelog] Added missing deprecated in 4.5.0

- CHANGELOG.md
Added missing deprecated for cucumber.api.Scenario to changelog for version 4.5.0
* [Core] Deprecate `cucumber.api.Scenario`
- Use `io.cucumber.core.api.Scenario` instead
Keeping changelog as precise as possible.
Nope, just changelog modification
> [Changelog] Added missing deprecated api.Scenario to 4.5.0 changelog

- core/src/main/java/io/cucumber/core/api/Scenario.java
- java/src/main/java/cucumber/runtime/java/JavaHookDefinition.java
- java8/src/main/java/cucumber/runtime/java8/Java8HookDefinition.java
Restore `Scenario#getSourceTagNames()` as people are using it in their hooks.
People are using hooks for variant settings, case insensitivity, posting information about tests execution into issue trackers using tags similar to [described in docs](https://cucumber.io/docs/cucumber/api/#link-to-other-documents). it would be nice to still have the ability to that.
> [Core] Restore Scenario#getSourceTagNames()

- core/src/main/java/cucumber/api/Scenario.java
- core/src/main/java/cucumber/api/event/EmbedEvent.java
- core/src/main/java/cucumber/runner/Scenario.java
- core/src/main/java/cucumber/runtime/formatter/HTMLFormatter.java
- core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java
- core/src/main/java/io/cucumber/core/api/Scenario.java
- core/src/main/resources/io/cucumber/formatter/html/formatter.js
- core/src/test/java/cucumber/runner/TestHelper.java
- core/src/test/java/cucumber/runtime/formatter/HTMLFormatterTest.java
- core/src/test/java/cucumber/runtime/formatter/JSONFormatterTest.java
- java/src/main/java/cucumber/runtime/java/JavaHookDefinition.java
- java8/src/main/java/cucumber/runtime/java8/Java8HookDefinition.java
This is a pull request related to #1692.
> Allow to add embeddings name

- .gitignore
- examples/java-calculator-testng/.gitignore
- java/src/main/java/cucumber/runtime/java/JavaBackend.java
- java/src/main/java/cucumber/runtime/java/ObjectFactoryLoader.java
- java/src/test/java/cucumber/runtime/java/JavaBackendTest.java
- junit/src/test/java/io/cucumber/junit/AssertionsTest.java
- testng/.gitignore
It is now possible to provide a custom ObjectFactory implementation that implements the new interface `io.cucumber.core.backend.ObjectFactory`.
With the change of applying a ServiceLoader to load the ObjectFactory it was not possible to create a custom ObjectFactory of type `io.cucumber.core.backend.ObjectFactory`. The disambiguation between the default factories (loaded through the ServiceLoader) and the custom implementation was only possible using `cucumber.properties` and by implementing a custom factory of type `cucumber.api.java.ObjectFactory`.
With this PR it is possible to use a custom ObjectFactory of the deprecated type `cucumber.api.java.ObjectFactory`. The class name of the type has to be specified in the `cucumber.properties` file, e.g.:
``` …
```
> [Core] Add property to select io.cucumber.core.backend.ObjectFactory implementation 

- core/src/main/java/io/cucumber/core/api/Scenario.java
- core/src/main/java/io/cucumber/core/event/EmbedEvent.java
- core/src/main/java/io/cucumber/core/plugin/HTMLFormatter.java
- core/src/main/java/io/cucumber/core/plugin/JSONFormatter.java
- core/src/main/java/io/cucumber/core/runner/Scenario.java
- core/src/main/resources/io/cucumber/core/plugin/html/formatter.js
- core/src/test/java/io/cucumber/core/plugin/HTMLFormatterTest.java
- core/src/test/java/io/cucumber/core/plugin/JSONFormatterTest.java
- core/src/test/java/io/cucumber/core/runner/TestHelper.java
This is pull request for #1692 for v5.
New test for JSONFormatter was added. Existing tests for HTML formaer were updated.
> [Core] Add name to embedding

- cdi2/pom.xml
- core/pom.xml
- guice/pom.xml
- kotlin-java8/pom.xml
Trying to build Java 11 project using cucumber and discovered a few projects are missing Automatic-Module-Name in the Manifest.mf file.
MANIFEST.MF update only
Getting a pure JPMS build and test working.
Built locally and testing as 4.7.1-SNAPSHOT
> [All] Add missing JPMS config

- core/pom.xml
- core/src/test/java/io/cucumber/core/feature/CucumberFeatureTest.java
- core/src/test/java/io/cucumber/core/feature/FeatureIdentifierTest.java
- core/src/test/java/io/cucumber/core/feature/FeaturePathTest.java
- core/src/test/java/io/cucumber/core/feature/GluePathTest.java
- core/src/test/java/io/cucumber/core/options/CucumberOptionsAnnotationParserTest.java
- core/src/test/java/io/cucumber/core/runner/AmbiguousStepDefinitionMatchsTest.java
- core/src/test/java/io/cucumber/core/runner/CoreStepDefinitionTest.java
- core/src/test/java/io/cucumber/core/runner/StepDefinitionMatchTest.java
- core/src/test/java/io/cucumber/core/runtime/BackendServiceLoaderTest.java
- guice/pom.xml
- guice/src/test/java/io/cucumber/guice/GuiceFactoryTest.java
- java/pom.xml
- java8/pom.xml
- java8/src/test/java/io/cucumber/java8/Java8LambdaStepDefinitionTest.java
- junit/pom.xml
- junit/src/test/java/io/cucumber/junit/CucumberTest.java
- needle/pom.xml
- spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
- weld/src/test/java/io/cucumber/weld/WeldFactoryTest.java
assertThrows replacing ExpectedException
Only the quick wins done, some outstanding to be convert in future PR
mvn clean install passed
> [All] Replace ExpectedException with assertThrows

- .travis.yml
Was disabled on the master-v5 branch; Now that that's merged we should enforce it again.
> [Build] Enable Semver check

- core/src/main/java/io/cucumber/core/plugin/DefaultSummaryPrinter.java
- core/src/main/java/io/cucumber/core/plugin/RerunFormatter.java
- core/src/main/java/io/cucumber/core/plugin/TimelineFormatter.java
- core/src/main/java/io/cucumber/core/plugin/UndefinedStepsTracker.java
- core/src/main/java/io/cucumber/core/plugin/UnusedStepsSummaryPrinter.java
- core/src/main/java/io/cucumber/core/plugin/UsageFormatter.java
- core/src/test/java/io/cucumber/core/plugin/UnusedStepsSummaryPrinterTest.java
Consistently handle events in plugins, after the initial push towards using lambdas where possible.
Also fixes an issue with the UnusedStepSummaryPrinter which failed to take into account that steps are registered at each scenario invocation. Fixed and improved test to verify.
Replace EventHandler instances with method references and apply consistent naming after the event handled.
Consistency.
JUnit test suite.
> [Core] Fix UnusedStepSummaryPrinter and consistently handle plugin events

- spring/README.md
I try for almost 2-3 days to use the spring injection of bean in my cucumber scenarios, but the documentation was leading me in the wrong direction.
I added examples in the documentation of Spring so that others don't waste their times.
I really thinks that this change can improve readability of your documentation.
I only did a change in documentation, so tests are not needed I think.
No change other than a documentation with exemples
> [Spring] Add examples to the documentation

- core/pom.xml
Whilst build using Java 11 and getting the Module-Info.java correct this was highlighted by the latest maven-jar-plugin. The mainClass listed doesn't match
> [Core] Fix mainClass in manifest

- deltaspike/README.md
- deltaspike/pom.xml
- deltaspike/src/main/java/io/cucumber/deltaspike/DeltaSpikeObjectFactory.java
- deltaspike/src/main/resources/META-INF/services/io.cucumber.core.backend.ObjectFactory
- deltaspike/src/test/java/io/cucumber/deltaspike/Belly.java
- deltaspike/src/test/java/io/cucumber/deltaspike/BellyStepdefs.java
- deltaspike/src/test/java/io/cucumber/deltaspike/DeltaSpikeObjectFactoryTest.java
- deltaspike/src/test/java/io/cucumber/deltaspike/RunCukesTest.java
- deltaspike/src/test/java/io/cucumber/deltaspike/UnusedGlue.java
- deltaspike/src/test/resources/META-INF/beans.xml
- deltaspike/src/test/resources/io/cucumber/deltaspike/cukes.feature
- pom.xml
objectfactory for cdi with deltaspike
Deltaspike abstract underlining cdi-container. so it is possible to change cdi-impl. only by replace the dependencies.
No longer to modules for cdi, only one with can replace the old one (weld and openejb) and in the same time support for another cdi-impl (OpenWebBeans).
Add Testcases and profiles to change cdi-impl.
> [DeltaSpike] Add ObjectFactory for Apache DeltaSpike

- junit/src/main/java/io/cucumber/junit/Cucumber.java
- junit/src/main/java/io/cucumber/junit/FeatureRunner.java
- junit/src/main/java/io/cucumber/junit/FileNameCompatibleNames.java
- junit/src/main/java/io/cucumber/junit/JUnitReporter.java
- junit/src/main/java/io/cucumber/junit/PickleRunners.java
- junit/src/test/java/io/cucumber/junit/CucumberTest.java
- junit/src/test/java/io/cucumber/junit/FeatureRunnerTest.java
- junit/src/test/java/io/cucumber/junit/JUnitReporterWithStepNotificationsTest.java
Fixes a number of issues w.r.t. JUnit test events:
1. Only fires events for atomic tests (i.e. pickles).
2. Ensures pickle started/finished events are fired even when duplicate
step definitions are encountered.
> [JUnit] Always fire TestStarted/Finished for pickle

- CHANGELOG.md
Based on discussion in https://github.com/cucumber/cucumber-eclipse/issues/373 ticket, added a brief note under 4.5.0 release.
> Note about snapshot version of cucumber-eclipse plugin for 4.5.0 & above

- core/pom.xml
- core/src/main/java/io/cucumber/core/plugin/JUnitFormatter.java
- core/src/main/java/io/cucumber/core/plugin/TestNGFormatter.java
- core/src/test/java/io/cucumber/core/plugin/JUnitFormatterTest.java
- core/src/test/java/io/cucumber/core/plugin/TestNGFormatterTest.java
- core/src/test/java/io/cucumber/core/runner/TestHelper.java
- core/src/test/resources/io/cucumber/core/plugin/JUnitFormatterTest_1.report.xml
- core/src/test/resources/io/cucumber/core/plugin/JUnitFormatterTest_1_strict.report.xml
- core/src/test/resources/io/cucumber/core/plugin/JUnitFormatterTest_2.report.xml
- core/src/test/resources/io/cucumber/core/plugin/JUnitFormatterTest_3.report.xml
- core/src/test/resources/io/cucumber/core/plugin/surefire-test-report-3.0.xsd
Cucumber JUnits xml format doesn't pass XSD validation in the
Jenkins XUnit plugin because it is missing the errors attribute.
Additionally time should be presented using numbers with both decimal
and thousands separators.
From: https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd
Via: https://maven.apache.org/surefire/maven-surefire-plugin/
Closes #1777
> [Core] Fix JUnit report xml attributes

- core/pom.xml
- core/src/main/java/io/cucumber/core/options/CucumberOptionsAnnotationParser.java
- core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
- core/src/main/java/io/cucumber/core/options/OptionsFileParser.java
- core/src/main/java/io/cucumber/core/options/RuntimeOptions.java
- core/src/main/java/io/cucumber/core/options/RuntimeOptionsBuilder.java
- core/src/main/java/io/cucumber/core/options/RuntimeOptionsParser.java
- core/src/test/java/io/cucumber/core/options/RerunFileTest.java
- core/src/test/java/io/cucumber/core/options/RuntimeOptionsTest.java
- docstring/pom.xml
- docstring/src/test/java/io/cucumber/docstring/DocStringTypeRegistryTest.java
- guice/pom.xml
- java/pom.xml
- java8/pom.xml
- junit/pom.xml
- needle/pom.xml
- pom.xml
A typical setup to rerun tests uses two Cucumber runners, where the
second runner uses the rerun file produced by the first to rerun
tests. E.g:
- `@CucumberOptions(plugin = "return:path/to/rerun.txt")`
- `@CucumberOptions(features = "path/to/rerun.txt")`
Then from the cli the entire suite is invoked with some tags:
```
mvn verify -Dcucumber.options="@smoke"
```
The expectation is that the first runner executes all features tagged
with `@smoke`. And that the second runner will rerun all failed features
tagged with `@smoke`. However because `@smoke` removes all line filters
the line filters from the rerun file were also removed.
By treating rerun files and feature files as distinct elements in the
`RuntimeOptions` builder we can properly reflect this nuance.
Fixes: #1785
> [Core] Do not clobber line filters from rerun file

- core/src/main/java/io/cucumber/core/cli/Main.java
- core/src/main/java/io/cucumber/core/options/PluginOption.java
- core/src/main/java/io/cucumber/core/options/RuntimeOptions.java
- core/src/main/java/io/cucumber/core/options/RuntimeOptionsBuilder.java
- core/src/main/java/io/cucumber/core/plugin/DefaultSummaryPrinter.java
- core/src/test/java/io/cucumber/core/options/CucumberOptionsAnnotationParserTest.java
- core/src/test/java/io/cucumber/core/options/RuntimeOptionsTest.java
- examples/java-calculator-testng/src/test/java/io/cucumber/examples/testng/ShoppingStepdefs.java
- java/src/main/java/io/cucumber/java/JavaSnippet.java
- java8/src/main/java/io/cucumber/java8/Java8Snippet.java
- junit/src/main/java/io/cucumber/junit/Cucumber.java
- testng/src/main/java/io/cucumber/testng/TestNGCucumberRunner.java
Cucumber can be ran through the CLI, JUnit and TestNG. The latter two can also be run through Maven, Gradle, IDEA and Eclipse. Each of these runners has different ways and needs to output information. To be a good CLI citizen Cucumber should integrate with these runners to ensure only the necessary information is printed.
This is achieved by using the hooks provided by each frameworks to log undefined steps. This information is then always logged to formatted xml files in the XUnit format. However when not running in strict mode (i.e. the test is skipped) Surefire and Gradle will not print or log this information.
This makes Cucumber harder to use. By always enabling the summary printer we can avoid this.
Manually checked combinations of JUnit, TestNG, IDEA, Eclipse, Maven and Gradle. The …
> [JUnit/TestNG] Always print snippets and summary

- core/src/test/java/io/cucumber/core/plugin/URLOutputStreamTest.java
- docstring/src/test/java/io/cucumber/docstring/DocStringTypeRegistryDocStringConverterTest.java
- guice/src/test/java/io/cucumber/guice/GuiceFactoryTest.java
The following changes are needed to successfully run `mvn test` on Windows.
- exception messages have \r\n (CRLF) line separator, so the tests must account for it
- files can't be deleted while they are still open, so we have to `close()` URLOutputStreams
`mvn test` run successfully. Windows 10 latest, JDK 1.8, mvn 3.6.2
> Fix tests on Windows

- core/src/main/java/io/cucumber/core/feature/CucumberFeature.java
- core/src/main/java/io/cucumber/core/feature/FeatureBuilder.java
- core/src/test/java/io/cucumber/core/feature/FeatureBuilderTest.java
- pom.xml
Build tools will typically copy the source files to a `build` or
`target` directory duplicating all feature files in the project. When
the root of the project is used as the feature path cucumber will
discover both sets of feature files (https://github.com/cucumber/cucumber-jvm/issues/165).
By including the file name we can distinguish between accidental
duplication and intentional duplication.
We could make this scenario an error but given the complexities of https://github.com/cucumber/cucumber-jvm/issues/259
this is best left as a separate issue.
> [Core] Include name in duplicate feature detection

- examples/java-calculator-junit5/src/test/java/io/cucumber/examples/junit5/calculator/RunCucumberTest.java
- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Cucumber.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolver.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolverTest.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/RunCucumberTest.java
Maven Surefire and Gradle do not yet support discovery of non-class
based tests[1][2]. As a workaround you can either use the `@Cucumber`
annotation or the JUnit Platform Console Launcher.
Cucumber will scan the package of a class annotated with `@Cucumber`
for feature files.
```java
package com.example.app;
import io.cucumber.junit.platform.engine.Cucumber;
@Cucumber
public class RunCucumberTest {
}
```
1. gradle/gradle#4773
2. https://issues.apache.org/jira/browse/SUREFIRE-1724
> [JUnit] Add JUnit Platform @Cucumber annotation

- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/PickleDescriptor.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/FeatureResolverTest.java
The JUnit Platform supports tag expressions. This allows users to select
groups of tests to execute. By not including the `@` symbol in the
`TestTag` it is possible to select both example below using the JUnit
tag expression `smoke` rather then `smoke & @smoke`.
```java
@Test
@Tag("Smoke")
void test(){}
```
```gherkin
@Smoke
Scenario: Smoke test
```
Additionally Maven interprets strings delimited by `@` symbols as
string interpolation[2]. This makes using the `@` symbol problematic in
tag expressions.
1. https://junit.org/junit5/docs/current/user-guide/#running-tests-tag-expressions
2. https://maven.apache.org/shared/maven-filtering/
> [JUnit] Do not include @ in TestTags

- core/README.md
- core/src/main/java/io/cucumber/core/runtime/ObjectFactoryServiceLoader.java
When multiple object factories are available on the classpath Cucumber
would print out a warning and fall back to the default object factory.
With the introduction of `cucumber.object-factory` the user can specify
exactly which object factory should be used. There should be no need for
a soft failure any more.
> [Core] Throw exception when multiple object factories are found

- core/src/main/java/io/cucumber/core/cli/Main.java
- junit/src/main/java/io/cucumber/junit/Cucumber.java
- pom.xml
- testng/src/main/java/io/cucumber/testng/TestNGCucumberRunner.java
Aside from the common `PASSED`, `SKIPPED` and `FAILED` states Cucumber also
uses `PENDING`, `UNDEFINED`, `AMBIGUOUS`. This makes mapping a test execution
state to a `OK` or `NOK` test run state complicated. By defaulting to
`--strict` only `PASSED`, `SKIPPED` are considered `OK`. This makes it easier
to integrate tooling with Cucumber.
However before we can default to `--strict` all usage should be `--strict`.
This PR will print a warning when Cucumber is not ran in `--strict` mode.
Part of #1788
> [Core] Print warning when using --non-strict

- core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
Currently cucumber.options is used to control cucumbers execution when run
through `mvn test`. This is no longer required with the introduction of property
based runtime options in #1741.
Part of #1779
> [Core] Deprecate `cucumber.options`

- core/src/main/java/io/cucumber/core/options/PluginOption.java
- core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java
- core/src/main/java/io/cucumber/core/runner/PickleStepDefinitionMatch.java
- core/src/main/java/io/cucumber/core/runner/Runner.java
- core/src/test/java/io/cucumber/core/plugin/CanonicalEventOrderTest.java
- core/src/test/java/io/cucumber/core/plugin/TeamCityPluginTest.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesExamples.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesFeature.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesRule.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesScenarioOutline.java
- gherkin-vintage/src/main/java/io/cucumber/core/gherkin/vintage/GherkinVintageExamples.java
- gherkin-vintage/src/main/java/io/cucumber/core/gherkin/vintage/GherkinVintageFeature.java
- gherkin-vintage/src/main/java/io/cucumber/core/gherkin/vintage/GherkinVintagePickle.java
- gherkin-vintage/src/main/java/io/cucumber/core/gherkin/vintage/GherkinVintageScenarioOutline.java
- gherkin/src/main/java/io/cucumber/core/gherkin/Container.java
- java8/src/main/java/io/cucumber/java8/AbstractGlueDefinition.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/TestCaseResultObserverTest.java
- junit/src/test/java/io/cucumber/junit/JUnitReporterWithStepNotificationsTest.java
- plugin/src/main/java/io/cucumber/plugin/event/SnippetsSuggestedEvent.java
- testng/src/test/java/io/cucumber/testng/TestCaseResultListenerTest.java
This plugin inserts markers that can be picked up by IDEA and
Teamcity. These in turn can then use this information to display a
test tree and show the output grouped by scenario.
This is plugin is nessesary because Intelij uses reflection
to extract more information from the plugin system then what would
normally be available. By substituting the CucumberJvm[1-5]SMFormatter
with this plugin we avoid runtime errors when our internals inevitably change.
Unfortunately the teamcity format is poorly documented[1]. Reverse
engingeering[2][3] the format from the plugin yields some information
but the exact function is rather opaque.
1. https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity
2. https://github.com/JetBrains/intellij-community/tree/master/plugins/cucumb …
> [Core] Implement TeamCity output format plugin

- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolver.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolverTest.java
Support `line` query parameter in `UriSelector`. 
Allows the use of a `line` query parameter when using the `UriSelector`:
- `classpath:/com/example/example.feature?line=20`
- `file:/path/to/com/example/example.feature?line=20`
This can be used by IDE creators and users to select a file in a feature file
and easily convert it to something the `CucumberTestEngine` can discover
and execute.
Any `TestDescriptor` that matches the line *and* its descendents will be
included in the discovery result. Note that this differs from the `FeaturePath`
specification. When using `classpath:/com/example/example.feature:20` only
pickles are matched. The query parameter also allows the selection of
scenario (outlines), rules, example sections and whole features.
The the dot-feature-colon-line-number format …
> [JUnit] Support `line` query parameter in `UriSelector`

- core/README.md
- core/src/main/java/io/cucumber/core/resource/ClasspathScanner.java
In practice the class path may be rather dirty and not all available classes can be loaded. Because Cucumber will by default scan in the root package it guaranteed to run into class loading errors. By logging these at debug level rather then throwing an exception Cucumber will most probably continue to work as expected. 
To debug occurrences of missing glue you can enable debug logging via: 
```
-Djava.util.logging.config.file=path/to/logging.properties
```
```properties
handlers=java.util.logging.ConsoleHandler
.level=FINE
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
``` 
Fixes: #1843
> [Core] Log class load errors while class scanning

- core/src/main/resources/io/cucumber/core/version.properties
Expose the gherkin version in `version.properties`, so it can be picked up from the classpath by other code.
A bit more context in https://github.com/cucumber/cucumber/issues/779#issuecomment-561220566, but I am specifically targeting the IDEA autocompletion support for Rule/Example grammar.
I am opening this now for more of a steer, as I can see that with #1804 and others we now have multiple Gherkin versions so this would no longer be valid, and I'm not sure what the best way to achieve this kind of feature detection would be now - or if it's the right thing to do at all.
(Sorry, meant to open this as a draft)
> [Core] Include default gherkin version in version.properties

- junit/src/main/java/io/cucumber/junit/FeatureRunner.java
- junit/src/main/java/io/cucumber/junit/PickleRunners.java
Fix execution issues if JUnit v4.13 is used at runtime instead of v4.12. Even if we do not update to v4.12, and cucumber users force update to v4.13.
Just the compile fixes due to additional constructors being added in JUnit v4.13.
Something to do on the commute to work.
1. pom update to v4.13
2. mvn clean install (FAILS)
3. fix runtime issues
4. mvn clean install (PASSES)
5. revert pom to v4.12
6. mvn clean install (PASSES)
> [JUnit] Fix execution when JUnit v4.13 is used

- Makefile
- archetype/README.md
- archetype/pom.xml
- archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetype/src/main/resources/archetype-resources/pom.xml
- archetype/src/main/resources/archetype-resources/src/test/java/RunCucumberTest.java
- archetype/src/main/resources/archetype-resources/src/test/java/StepDefinitions.java
- archetype/src/test/resources/projects/should-generate-project/archetype.properties
- archetype/src/test/resources/projects/should-generate-project/goal.txt
- archetype/src/test/resources/projects/should-generate-project/reference/pom.xml
- archetype/src/test/resources/projects/should-generate-project/reference/src/test/java/com/example/RunCucumberTest.java
- archetype/src/test/resources/projects/should-generate-project/reference/src/test/java/com/example/StepDefinitions.java
- pom.xml
The maven archetype lives in its own project[1] which makes it
cumbersome to keep it up-to-date with on going releases. As
each release of Cucumber-JVM results in a release of the archetype
it is sensible to keep both project together.
The module uses resource filtering[2] to replace the `{project.version}`
in the archetypes `pom.xml`. This ensures no manual version updates
are needed.
1. https://github.com/cucumber/cucumber-archetype
2. http://maven.apache.org/plugins/maven-resources-plugin
> [Archetype] Add Maven Archetype module to project

- CHANGELOG.md
- java/src/main/java/io/cucumber/java/AbstractDatatableElementTransformerDefinition.java
- java/src/test/java/io/cucumber/java/JavaDataTableTypeDefinitionTest.java
- java/src/test/java/io/cucumber/java/JavaDefaultDataTableCellTransformerDefinitionTest.java
- java/src/test/java/io/cucumber/java/JavaDefaultDataTableEntryTransformerDefinitionTest.java
- java8/src/main/java/io/cucumber/java8/AbstractDatatableElementTransformerDefinition.java
- java8/src/test/java/io/cucumber/java8/LambdaStepDefinitions.java
- java8/src/test/resources/io/cucumber/java8/lambda-step-definitions.feature
- pom.xml
When using
```
@DataTableType(replaceWithEmptyString={"[blank]"})
public List convertDataTable(DataTable dataTable) {
return new ArrayList();
}
```
In combination with a table containing empty (now null cells)
```
| test |
|      |
```
An NPE would be thrown while checking the null cell against the
replacement pattern.
Fixes #1864
> [Java] Fix NPE in AbstractDatatableElementTransformerDefinition

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/resource/ClasspathSupport.java
Replace windows path separator in sub package name
Closes #1868
> [Core] Replace windows path separator in sub package name

- .m2/travis-ci-toolchains.xml
- .travis.yml
- CHANGELOG.md
- archetype/pom.xml
- core/src/main/java/io/cucumber/core/backend/Located.java
- junit-platform-engine/pom.xml
- junit-platform-engine/src/main/java9/module-info.java
- openejb/pom.xml
- pom.xml
Adds module-info for Cucumber Junit Platform Engine implementation.
This allows Java to ensure that all dependencies are available at
boot time.
To ensure backwards compatibility down to Java 8 we are using
multi-release jar files which will contain both Java 8 and
Java 9 class files.
To ensure the right JDK (OpenJDK 11) is used to build the project
the Maven Toolchains plugin will verify that this JDK is used.
This does require adding a `toolchains.xml` file to the `~/.m2/`
folder.
Example:
```xml
<?xml version="1.0" encoding="UTF8"?>
<toolchains>
<toolchain>
<type>jdk</type>
<provides>
<version>11</version>
<vendor>openjdk</vendor>
</provides>
<configuration>
<jdkHome>/path/to/openjdk11</jdkHome>
</configuration>
</toolchain>
</toolchains>
```
> [JUnit] Add module-info for cucumber-junit-platform-engine

- .travis.yml
- CHANGELOG.md
- core/src/main/java/io/cucumber/core/backend/CucumberBackendException.java
- core/src/main/java/io/cucumber/core/backend/CucumberInvocationTargetException.java
- core/src/main/java/io/cucumber/core/runner/PickleStepDefinitionMatch.java
- core/src/test/java/io/cucumber/core/runner/StepDefinitionMatchTest.java
- pom.xml
Exceptions thrown by parameter, datatable and docstring definitions
are swallowed leaving a stack trace ending with a rather puzzling
`CucumberInvocationTargetException`.
> [Core] Print root cause of exceptions in glue definition

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/resource/ClasspathSupport.java
- core/src/test/java/io/cucumber/core/resource/ResourceScannerTest.java
`classpathResourceUri` used `URI.create` which assumes that the URI
to parse is a valid URI. This assumption doesnt hold when
transforming paths into URIs. Instead the URI constructor should be
used which does escaped reserved characters.
Closes #1872
> [Core] Escape spaces in resource name

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/feature/FeatureParser.java
- core/src/main/java/io/cucumber/core/plugin/JUnitFormatter.java
- core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java
- core/src/main/java/io/cucumber/core/plugin/TestNGFormatter.java
- core/src/main/java/io/cucumber/core/plugin/TimelineFormatter.java
- core/src/main/java/io/cucumber/core/runtime/FeaturePathFeatureSupplier.java
- core/src/test/java/io/cucumber/core/feature/TestFeatureParser.java
- core/src/test/java/io/cucumber/core/runtime/FeatureBuilderTest.java
- gherkin-messages/pom.xml
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesFeatureParser.java
- gherkin-messages/src/test/java/io/cucumber/core/gherkin/messages/FeatureParserTest.java
- gherkin-messages/src/test/resources/io/cucumber/core/gherkin/messages/no-pickles.feature
- gherkin-vintage/src/main/java/io/cucumber/core/gherkin/vintage/GherkinVintageFeatureParser.java
- gherkin-vintage/src/test/java/io/cucumber/core/gherkin/vintage/FeatureParserTest.java
- gherkin-vintage/src/test/resources/io/cucumber/core/gherkin/vintage/no-pickles.feature
- gherkin/src/main/java/io/cucumber/core/gherkin/FeatureParser.java
- java/src/test/java/io/cucumber/java/TestFeatureParser.java
- java8/src/test/java/io/cucumber/java8/TestFeatureParser.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- junit/src/test/java/io/cucumber/junit/TestFeatureParser.java
- junit/src/test/java/io/cucumber/junit/TestPickleBuilder.java
- pom.xml
Fix NPE when parsing empty feature file
> [Core] Fix NPE when parsing empty feature file

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/backend/TestCaseState.java
- core/src/main/java/io/cucumber/core/runner/TestCaseState.java
- core/src/test/java/io/cucumber/core/runner/TestCaseStateResultTest.java
- java/src/main/java/io/cucumber/java/Scenario.java
- java8/src/main/java/io/cucumber/java8/Scenario.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/TestCaseResultObserver.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/TestCaseResultObserverTest.java
- testng/src/main/java/io/cucumber/testng/TestCaseResultObserver.java
- testng/src/test/java/io/cucumber/testng/TestCaseResultObserverTest.java
Currently `TestCaseState` defaults to `Status.UNDEFINED` when no steps have
been executed. This is odd because the implementation otherwise collects the
most severe result. So the logical expectation would be that it would return
`Status.PASSED`
```java
@Override
public Status getStatus() {
if (stepResults.isEmpty()) {
return Status.UNDEFINED;
}
Result mostSevereResult = max(stepResults, comparing(Result::getStatus));
return Status.valueOf(mostSevereResult.getStatus().name());
}
```
As a result the `TestCaseResultObserver` in `junit-platform-engine` and
`testng` needs to check if an undefined scenario was empty or not. This means
our abstraction is rather leaky.
```java
if (status.is(UNDEFINED)) {
if (suggestions.isEmpty()) {
// Empty scenario
return;
}
throw new …
```
> [Core] TestCaseState should be PASSED by default

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/cli/Main.java
- core/src/main/java/io/cucumber/core/options/RuntimeOptions.java
- core/src/main/java/io/cucumber/core/options/RuntimeOptionsBuilder.java
- core/src/main/resources/io/cucumber/core/options/USAGE.txt
- core/src/test/java/io/cucumber/core/options/RuntimeOptionsTest.java
- picocontainer/pom.xml
The Cucumber CLI is rather complex to use. To work correctly it needs both
a `--glue` parameter in the form of a package name and a location of a feature
file in form of a classpath uri or path. As a result people often configure
Cucumber incorrectly and are left wondering why their features or glue can not
be found.
This can be simplified as shown by the Cucumber Platform Engine which defaults
to the classpath root and the JUnit and TestNG runners which default to the
package of the runner class.
So it makes sense to do the same with the CLI.
Assuming the following project layout the CLI can discover and execute
all features without needing additional arguments.
```
├── pom.xml
├── src
│   ├── main
│   │   └── java
│   │       └── com/example/Application.java
│   └── test
│       ├── …
```
> [Core] CLI should search classpath root by default

- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/UndefinedStepException.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/TestCaseResultObserverTest.java
- junit/src/main/java/io/cucumber/junit/UndefinedStepException.java
- junit/src/test/java/io/cucumber/junit/JUnitReporterWithStepNotificationsTest.java
- testng/src/main/java/io/cucumber/testng/UndefinedStepException.java
- testng/src/test/java/io/cucumber/testng/TestCaseResultObserverTest.java
The frequently seen snippet generator message contains a typo:
>[ERROR]   The step "I am a new customer" is undefined. You can implement it using _**tne**_ snippet(s) below:
This PR replaces `tne` with `the` wherever the above message appears in the code.
> [All] Fix typo in snippet generator message

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/options/Constants.java
- core/src/main/java/io/cucumber/core/resource/PathScanner.java
- core/src/test/java/io/cucumber/core/runtime/FeaturePathFeatureSupplierTest.java
- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Constants.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineExecutionContext.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineOptions.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/PickleDescriptor.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/CucumberTestEngineTest.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolverTest.java
- junit-platform-engine/src/test/resources/io/cucumber/junit/platform/engine/disabled.feature
- junit-platform-engine/src/test/resources/junit-platform.properties
The JUnit Platform supports skipping tests. For example in JUnit Jupiter a
test can be annotated with `@Disabled`. This test will be marked as skipped.
Cucumber scenarios do not have annotations nor is there any support to disable
specific scenarios. A typical work around with Cucumber JUnit 4 integration was
to set a permanent tag filter for `not @Disabled` in `@CucumberOptions`.
This wasn't possible with the JUnit Platform yet. By adding the
`cucumber.filter.tags` property it becomes possible to recreate JUnit Jupiter's
`@Disabled` functionality.
By setting `cucumber.filter.tags=not @Disabled` property any scenarios tagged
with `@Disabled` will be skipped.
Note that contrary to JUnit 4 skipped scenarios are not removed from the test
hierarchy. This is entirely intentional and a result …
> [JUnit Platform] Support skipping scenarios with cucumber.filter.tags

- core/pom.xml
- docstring/pom.xml
- examples/java-calculator-junit5/pom.xml
- examples/java-calculator/pom.xml
- java/pom.xml
- pom.xml
The `cucumber-jvm` parent pom included `jackson-databind` in its dependency
management section. Because this is a test only dependency it was marked as
test scoped.
While not intended to function as a bill of materials people were and perhaps
still are using `cucumber-jvm` in this fashion. Removing `jackson-databind`
from the dependency management ensures that `cucumber-jvm` only manages
cucumber and test related dependencies.
While not safe, this does provide a modicum of safety.
> [All] Remove Jackson from `cucumber-jvm` parent pom

- java8/src/main/java/io/cucumber/java8/AbstractGlueDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DataTableCellDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DataTableDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DataTableEntryDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DataTableRowDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DocStringTypeDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8StepDefinition.java
- java8/src/main/java/io/cucumber/java8/LambdaTypeResolver.java
Because of https://github.com/cucumber/cucumber-jvm/issues/1817 `cucumber-java8` can't resolve the argument types of step definitions,  parameter types and data table types. This results in a number of rather obscure behaviours. By adding a clear error message can avoid these behaviours.
> [Java8] Show error message when used on Java 12+

- spring/src/main/java/io/cucumber/spring/SpringFactory.java
- spring/src/main/java/io/cucumber/spring/TestContextAdaptor.java
- spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
- spring/src/test/java/io/cucumber/spring/TestContextAdaptorTest.java
When neither a glue class with a spring context configuration could be found
nor a `cucumber.xml` file exists `cucumber-spring` will fall back to a
`GenericApplicationContext` to facilitate dependency injection.
The current implementation tries to reuse this application context between
scenarios. This requires refreshing the context which can only be done once.
So it's not possible to reuse the `GenericApplicationContext` and a new one
should be created for each scenario.
https://stackoverflow.com/questions/60445228/cucumber-5-0-0-and-springboot-multiple-scenarios-in-one-feature-file
Because `cucumber.xml` and the `GenericApplicationContext` are fallback methods it is very hard to test these individually.  Had to test these manually using: …
> [Spring] Do not reuse generic application context between scenarios

- java8/pom.xml
Upgrade net.jodah:typetools from 0.6.1 to 0.6.2, which includes Automatic-Module-Name, that can be used for jpms.
Dependency update for java8 pom
Getting Java Modules working for cucumber, so doing pr's for downstream projects.
mvn clean install
n/a/
> [Java8] update to net.jodah:typetools:0.6.2

- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesStep.java
- gherkin-messages/src/test/java/io/cucumber/core/gherkin/messages/FeatureParserTest.java
- gherkin-messages/src/test/resources/io/cucumber/core/gherkin/messages/empty-table.feature
- gherkin-vintage/src/main/java/io/cucumber/core/gherkin/vintage/GherkinVintageDataTableArgument.java
- gherkin-vintage/src/main/java/io/cucumber/core/gherkin/vintage/GherkinVintageStep.java
- gherkin-vintage/src/test/java/io/cucumber/core/gherkin/vintage/FeatureParserTest.java
- gherkin-vintage/src/test/resources/io/cucumber/core/gherkin/vintage/empty-table.feature
Parsing the feature below results in an NPE because Gherkin v5 uses the location
of the first cell as the location of the table. Because there is no cell, there
is no location. In this case we fall back to using the line of the step + 1.
```gherkin
Feature: Empty table
Scenario: This is valid Gherkin
Given an empty list
|
```
Fixes: https://github.com/cucumber/cucumber-jvm/issues/1912
> [Gherkin] Fix NPE on empty table

- java/src/main/java/io/cucumber/java/GlueAdaptor.java
- java/src/main/java/io/cucumber/java/JavaParameterTypeDefinition.java
- java/src/main/java/io/cucumber/java/ParameterType.java
- java/src/test/java/io/cucumber/java/GlueAdaptorTest.java
- java/src/test/java/io/cucumber/java/JavaParameterTypeDefinitionTest.java
Parameter types are registered with a regex. When a step definition is written
as a regular expression `cucumber-expressions` use the regex in the capture
group as a type hint.
When the type hint provided by the regex and the type hint provided by the
method (i.e. the types of its arguments) disagree about the type
`cucumber-expressions` prefers the hint provided by the regex.
When parameter types are declared with very simple regexes this may cause a
problem. For example:
```java
import io.cucumber.java.ParameterType;
import io.cucumber.java.en.Given;
public class StepDefinitions {
private static class TypeA {}
@ParameterType("\\w+")
public TypeA typeA(String a) {
return new TypeA();
}
@Given("a cucumber expression of {typeA}")
public void an_object_of_type_a(TypeA a) {
// works fine!
} …
```
> [Java] Add @ParameterType(useRegexpMatchAsStrongTypeHint=true/false)

- testng/src/main/java/io/cucumber/testng/TestNGCucumberRunner.java
- testng/src/test/java/io/cucumber/testng/TestNGCucumberRunnerTest.java
When a TestNG suite with `parallel="methods"` is executed TestNG will invoke
all `@DataProvider` annotated methods. Because these data providers also emit
the `TestRunStarted` event this event is emitted twice concurrently. These
events collide in the `CanonicalOrderEventPublisher` resulting in a concurrent
modification that inserts a null element rather then either of the events.
By moving the start of the test execution to the constructor we ensure that
test execution is always started serially. Additionally this ensures that it is
impossible to emit a `TestRunFinished` event without also emitting a
`TestRunStarted` event.
This comes at the cost of starting the execution as soon as the `@BeforeClass`
method is invoked. This will result in some apparent overhead as TestNG is
still …
> [TestNG] Fix concurrent modification of events

- core/src/main/java/io/cucumber/core/plugin/UrlOutputStream.java
- core/src/test/java/io/cucumber/core/plugin/UrlOutputStreamTest.java
Chunked upload requires a connection to be kept alive for the duration
of the test execution. This is practically not feasible. So rather then
using chunked upload the output is written to a temporary file and then
uploaded all at once.
> [Core] UrlOutputStream uploads all data in one pass

- spring/README.md
- spring/src/main/java/io/cucumber/spring/SpringFactory.java
- spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
- spring/src/test/java/io/cucumber/spring/annotationconfig/RunCucumberContextConfigurationTest.java
- spring/src/test/java/io/cucumber/spring/contextcaching/ContextCachingSteps.java
- spring/src/test/java/io/cucumber/spring/contextcaching/RunCucumberTest.java
- spring/src/test/java/io/cucumber/spring/contextconfig/BellyStepDefinitions.java
- spring/src/test/java/io/cucumber/spring/contextconfig/RunCucumberTest.java
- spring/src/test/java/io/cucumber/spring/contexthierarchyconfig/WithContextHierarchyAnnotation.java
- spring/src/test/java/io/cucumber/spring/dirtiescontextconfig/DirtiesContextBellyStepDefinitions.java
- spring/src/test/java/io/cucumber/spring/dirtiescontextconfig/RunCucumberTest.java
- spring/src/test/java/io/cucumber/spring/metaconfig/dirties/DirtiesContextBellyMetaStepDefinitions.java
- spring/src/test/java/io/cucumber/spring/metaconfig/dirties/RunCucumberTest.java
- spring/src/test/java/io/cucumber/spring/metaconfig/general/BellyMetaStepDefinitions.java
- spring/src/test/java/io/cucumber/spring/metaconfig/general/RunCucumberTest.java
- spring/src/test/java/io/cucumber/spring/threading/ThreadingStepDefinitions.java
- spring/src/test/java/io/cucumber/spring/webappconfig/RunCucumberTest.java
- spring/src/test/java/io/cucumber/spring/webappconfig/SpringInjectionStepDefinitions.java
The prefered way to use `cucumber-spring` is to annotate a class
with both `@CucumberContextConfiguration` and a Spring context
configuration annotation such as `@ContextConfiguration`,
`@SpringBootTest`, ect.
Cucumber currently supports the discovery of context
configuration on any step defintion class. This requires a
significant amount of code and intimate knowledge of the
Spring Framework.
By restricting this too only classes annotated with
`@CucumberContextConfiguration` we can remove this complexity and
simply pass the annotated class to Spring `TestContextManager`
framework.
If no context configuration is available Cucumber currently also
support reading the application context from a magical
`cucumber.xml` file or should none exist an empty application
context.
Both these fallback …
> [Spring] Deprecate cucumber.xml and implied context configuration

- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Constants.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolver.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/PickleDescriptor.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/FeatureResolverTest.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/MapConfigurationParameters.java
- junit-platform-engine/src/test/resources/io/cucumber/junit/platform/engine/feature-with-outline.feature
Using exclusive resources it is possible to control which scenarios will
not run concurrently with other scenarios that use the same resource.
Cucumber tags can be mapped to exclusive resources. A resource can be\
either locked with a read-write-lock, or a read lock.
For example:
```gherkin
Feature: Exclusive resources
@my-tag-ab-rw
Scenario: first example
Given this reads and writes resource a
And this reads and writes resource b
When it is executed 
Then it will not be executed concurrently with the second example
@my-tag-a-r
Scenario: second example
Given this reads resource a
When it is executed
Then it will not be executed concurrently with the first example
```
With this configuration:
```
cucumber.execution.exclusive-resources.my-tag-ab-rw.read-write=resource-a,b …
```
> [JUnit Platform] Map tags to exclusive resources

- java8/README.md
The `README.md` for `cucumber-java8` informs the user:
To use add the `cucumber-java` dependency
...whereas it should say...
To use add the `cucumber-java8` dependency
That's all this PR fixes :)
> [Java8] Fix dependency name typo

- java/src/main/java/io/cucumber/java/AbstractGlueDefinition.java
- java/src/main/java/io/cucumber/java/Invoker.java
- java/src/main/java/io/cucumber/java/JavaDataTableTypeDefinition.java
- java/src/main/java/io/cucumber/java/JavaDefaultDataTableCellTransformerDefinition.java
- java/src/main/java/io/cucumber/java/JavaDefaultDataTableEntryTransformerDefinition.java
- java/src/main/java/io/cucumber/java/JavaDocStringTypeDefinition.java
- java/src/main/java/io/cucumber/java/JavaHookDefinition.java
- java/src/main/java/io/cucumber/java/JavaParameterTypeDefinition.java
- java/src/main/java/io/cucumber/java/JavaStepDefinition.java
- java/src/test/java/io/cucumber/java/JavaDataTableTypeDefinitionTest.java
Allows glue annotations to be used on static methods. This allows for
example `@DataTableType` to be used on the type it creates.
```
public class TestBean {
private String stringOne;
private String stringTwo;
[...]
@DataTableType
public static TestBean makeTestBean(Map<String, String> row) {
return new TestBean(
row.get("ItemOne"),
row.get("ItemTwo")
);
}
}
```
Fixes #1950
> [Java] Invoke static methods without instantiating target object

- core/pom.xml
- core/src/main/java/io/cucumber/core/plugin/JsonFormatter.java
- core/src/main/java/io/cucumber/core/stepexpression/StepExpressionFactory.java
- core/src/test/java/io/cucumber/core/stepexpression/StepExpressionFactoryTest.java
Consumers of the json output expect all fields to be present. To avoid
breaking consumers we include all fields in the dummy feature that is
generated when cucumber fails to execute.
> [Core] Include all fields in JsonFormatters failure feature

- core/src/main/java/io/cucumber/core/options/CucumberOptionsAnnotationParser.java
Passing multiple tags through `@CucumberOptions` has confusing
semantics. Using a single tag expressions clears up any confusion and
harmonizes `@CucumberOptions` with `cucumber.filter.tags`.
For example:
```java
@CucumberOptions(tags="(@cucumber or @pickle) and not @salad")
```
```properties
cucumber.filter.tags="(@cucumber or @pickle) and not @salad"
```
Partial fix for: #1948
> [Core] Deprecate multiple tag arguments in @CucumberOptions

- core/src/test/java/io/cucumber/core/plugin/DefaultSummaryPrinterTest.java
Fix for the test DefaultSummaryPrinterTest which assumed LF only line endings but fails on Windows
Used System.lineSeparator() to determine the line ending to use in the expectation.
The test fails on Windows.
The change is in a test.
The change is local to one unit test.
- [ x] Bug fix (non-breaking change which fixes an issue).
https://github.com/cucumber/cucumber-jvm/issues/1956
- [x ] I've added tests for my code.
> [Core] fix for DefaultSummaryPrinterTest on Windows

- spring/README.md
With the recent deprecation of the use of `cucumber.xml` I migrated a project over to use the new CucumberContextConfiguration. In doing so I found a small gap in the docs - it's assumed that the config class annotated with `@ CucumberContextConfiguration` will be on the glue path. In my project I set the `cucumber.glue` option to point at a particular package, and since  my new CucumberContextConfiguration class wasn't initially on the glue path I was getting the following error:
```
io.cucumber.core.backend.CucumberBackendException: Error creating bean with name 'com.example.foobar.glue.Steps': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.foobar.glue.Steps]: No default constructor found; nested …
```
> [Spring] Note that CucumberContextConfiguration is glue

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
- core/src/test/java/io/cucumber/core/options/CucumberPropertiesParserTest.java
The feature option can be used with either a rerun file or a feature path. For
example when used as a property:
```
cucumber.feature=path/to/features
cucumber.feature=@path/to/rerun.txt
```
Cucumber options consist of a hierarchy of options. When the feature options is
used with a rerun file; tag and name filters from the previous level should be
removed. This ensures that all scenarios in the rerun file and only the
scenarios in the rerun file should be executed (unless the selection is filtered
more at this or the next level).
When used with a feature argument without a line filter this should not be the case.
However `builder::addRerun` would be invoked anyway.
When parsing `cucumber.feature` for rerun files, when no rerun files are present an
empty collection is returned. Because …
> [Core] cucumber.feature preserves tags when used with a feature argument

- core/src/main/java/io/cucumber/core/plugin/UsageFormatter.java
- core/src/test/java/io/cucumber/core/plugin/UsageFormatterTest.java
Updated durationJsonSerializer to use toNanos() instead of getNano(). This was causing the durations to only show the nanosecond portion of the duration, dropping the second portion. The result is all durations in the report indicate times less than a second for all step defnition executions.
#1988 Durations in the Usage report are always less than 1 second, even when the known times for the steps are over 1 second, so the report is invalid.
As listed above, I changed the getNano() call to toNanos() to get the correct value. Updated the test to use a number of nanoseconds greater than 1 second and verify the correct result.
n/a
> [Core] Correct issue with usage report durations >= 1 second

- CHANGELOG.md
I noticed the CHANGELOG compare links are "broken" since the v6.x RC releases.
This PR just fix the CHANGELOG so that the links are correct but maybe there's a change to be made in the releases scripts as well.
I didn't check yet.
> Fix CHANGELOG compare links

- junit/src/main/java/io/cucumber/junit/Cucumber.java
- junit/src/main/java/io/cucumber/junit/FeatureRunner.java
- junit/src/main/java/io/cucumber/junit/FileNameCompatibleNames.java
- junit/src/main/java/io/cucumber/junit/PickleRunners.java
- junit/src/test/java/io/cucumber/junit/CucumberTest.java
- junit/src/test/java/io/cucumber/junit/FeatureRunnerTest.java
- junit/src/test/java/io/cucumber/junit/PickleRunnerWithNoStepDescriptionsTest.java
- junit/src/test/java/io/cucumber/junit/PickleRunnerWithStepDescriptionsTest.java
- junit/src/test/resources/io/cucumber/junit/single-duplicate.feature
- testng/src/test/java/io/cucumber/testng/StubBackendProviderService.java
- testng/src/test/resources/io/cucumber/testng/feature-with-outline.feature
Individual examples do not have a unique name. And while a unique name is not
required by Junit, various integrations such as sbt-junit assume this the case.
By appending ` [#n]` to a scenario name it becomes unique again. So JUnit 4s
output becomes:
```
A feature with scenario outlines
A scenario outline #1
A scenario outline #2
A scenario outline #3
A scenario outline #4
```
The `#n` was taken from JUnit 5 which renders examples as:
```
A feature with scenario outlines
A scenario outline
With some other text
Example #1
Example #2
With some text
Example #1
Example #2
```
Fixes: https://github.com/cucumber/cucumber-jvm-scala/issues/102
> [JUnit] Make duplicate pickle names unique

- CHANGELOG.md
- core/README.md
- core/src/main/java/io/cucumber/core/options/Constants.java
- core/src/main/resources/io/cucumber/core/options/USAGE.txt
- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Constants.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineOptions.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/PickleDescriptor.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/CucumberTestEngineTest.java
A typical way to run a single Cucumber test from the command line is to use a
filter. The Cucumber Engine already supported `cucumber.filter.tags` but did
not yet support `cucumber.filter.name`.
This filter can be used in `junit-platform.properties`, the CLI (e.g.
`mvn test -Dcucumber.filter.name="^Hello (World|Cucumber)$"` and in any way
properties can be used with the JUnit Platform.
> [Junit Platform] Support cucumber.filter.name

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/backend/ScenarioScoped.java
- core/src/main/java/io/cucumber/core/runner/CachingGlue.java
- core/src/main/java/io/cucumber/core/runner/CoreDefaultDataTableEntryTransformerDefinition.java
- core/src/main/java/io/cucumber/core/runner/CoreHookDefinition.java
- core/src/test/java/io/cucumber/core/runner/CachingGlueTest.java
- java8/src/main/java/io/cucumber/java8/AbstractGlueDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DataTableCellDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DataTableDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DataTableEntryDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DataTableRowDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DefaultDataTableCellTransformerDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DefaultDataTableEntryTransformerDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DefaultParameterTypeDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8DocStringTypeDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8HookDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8ParameterTypeDefinition.java
- java8/src/main/java/io/cucumber/java8/Java8StepDefinition.java
Glue definitions in Java8 retain a reference to the test execution context.
Glue definitions in turn are used in events. Events in turn may be stored for
the entire duration of Cucumbers execution. So when many scenarios are executed
this may results in significant memory usage.
By removing the reference to the test execution context after the scenario is
executed we can still use step definitions in events without the associated
memory consumption.
Fixes: #2066
> [Java8] Allow test execution context to be garbage collected

- compatibility/src/test/java/io/cucumber/compatibility/matchers/AComparableMessage.java
- core/src/main/java/io/cucumber/core/backend/JavaMethodReference.java
- core/src/main/java/io/cucumber/core/backend/Located.java
- core/src/main/java/io/cucumber/core/backend/SourceReference.java
- core/src/main/java/io/cucumber/core/backend/StackTraceElementReference.java
- core/src/main/java/io/cucumber/core/runner/CachingGlue.java
- core/src/main/java/io/cucumber/core/runner/CoreHookDefinition.java
- core/src/main/java/io/cucumber/core/runner/CoreStepDefinition.java
- core/src/test/java/io/cucumber/core/runner/CachingGlueTest.java
- core/src/test/java/io/cucumber/core/runner/StubStepDefinition.java
- core/src/test/java/io/cucumber/core/runtime/RuntimeTest.java
- java/src/main/java/io/cucumber/java/AbstractGlueDefinition.java
- java8/src/main/java/io/cucumber/java8/AbstractGlueDefinition.java
- pom.xml
Cucumber JVM can not reference files by URI. So it should use either java
methods or stack trace elements as a source reference instead.
For example:
```json
{
"hook": {
"id": "a1839ec6-f75d-4029-9b75-4b8203d8b2e8",
"sourceReference": {
"javaMethod": {
"className": "io.cucumber.compatibility.attachments.Attachments",
"methodName": "before",
"methodParameterTypes": [
"io.cucumber.java.Scenario"
]
}
}
}
}
```
See: https://github.com/cucumber/cucumber/issues/1119
Fixes: https://github.com/cucumber/cucumber-jvm/issues/2058
> Include SourceReferences in message output

- .travis.yml
- CHANGELOG.md
- cdi2/src/test/resources/cucumber.properties
- core/src/main/java/io/cucumber/core/options/Constants.java
- core/src/test/java/io/cucumber/core/plugin/NoPublishFormatterTest.java
- deltaspike/src/test/resources/cucumber.properties
- guice/src/test/resources/cucumber.properties
- jakarta-cdi/src/test/resources/cucumber.properties
- java/src/test/resources/cucumber.properties
- java8/src/test/resources/cucumber.properties
- junit-platform-engine/src/test/resources/junit-platform.properties
- junit/src/test/resources/cucumber.properties
- kotlin-java8/src/test/resources/cucumber.properties
- needle/src/test/resources/cucumber.properties
- openejb/src/test/resources/cucumber.properties
- picocontainer/src/test/resources/cucumber.properties
- spring/src/test/resources/cucumber.properties
- testng/src/test/resources/cucumber.properties
- weld/src/test/resources/cucumber.properties
This changes the publish-related environment variables (and corresponding JVM system properties) from:
* `CUCUMBER_PLUGIN_PUBLISH_ENABLED`
* `CUCUMBER_PLUGIN_PUBLISH_TOKEN`
* `CUCUMBER_PLUGIN_PUBLISH_URL`
* `CUCUMBER_PLUGIN_PUBLISH_QUIET`
to:
* `CUCUMBER_PUBLISH_ENABLED`
* `CUCUMBER_PUBLISH_TOKEN`
* `CUCUMBER_PUBLISH_URL`
* `CUCUMBER_PUBLISH_QUIET`
The reasons for doing this are:
* The environment variables should be identical across Cucumber implementations
* Cucumber-JVM is the only implementation that has renamed "formatter" to "plugin", and "plugin" is confusing on Cucumber.js and Cucumber-Ruby
* The names are shorter
This is related to https://github.com/cucumber/cucumber-ruby/pull/1452#discussion_r470004804
> Remove 'plugin' from publish-related env vars/system props.

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/plugin/NoPublishFormatter.java
- core/src/test/java/io/cucumber/core/plugin/NoPublishFormatterTest.java
The old instructions for activating publishing allowed too many things to go wrong:
* Many users don't know how to set environment variables. They'll set them in Windows system settings not realising a reboot is required to make it take effect
* Adding `publish = true` to `@CucumberOptions` will have no effect if Cucumber is run from IDEA's native runner (green triangles in the gutter)
For this reason the top recommendation is now to set `cucumber.publish.enabled=true` in `src/test/resources/cucumber.properties`. This should be picked up regardless of how people run Cucumber.
I've also removed the recommendation to use `src/test/resources/junit-platform.properties` since it will be ignored when using the IDEA runner.
> Improve publish instructions

- core/src/main/java/io/cucumber/core/runner/CachingGlue.java
- core/src/test/java/io/cucumber/core/runner/CachingGlueTest.java
The beforestep and afterstep message details were not displayed in ndjson report. 
A link to an issue or a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Refer to https://github.com/cucumber/cucumber-jvm/issues/2058#issuecomment-667712556
A clear and concise description of what happens.
Add any other context or screenshots about the pull request here.
> [Core] Emit step hook messages

- core/src/main/java/io/cucumber/core/plugin/PublishFormatter.java
- core/src/main/java/io/cucumber/core/plugin/UrlOutputStream.java
- core/src/test/java/io/cucumber/core/plugin/UrlOutputStreamTest.java
- core/src/test/java/io/cucumber/core/runner/CachingGlueTest.java
- pom.xml
The `https://messages.cucumber.io` service responds with [413 Payload Too Large](https://httpstatuses.com/413) for message files larger than [6 Mb](https://jun711.github.io/aws/handling-aws-api-gateway-and-lambda-413-error/). This was discovered during a [chat with one of our users](https://cucumberbdd.slack.com/archives/C60TKS3SL/p1597955993030800).
We've adopted the solution outlined in [Option 2 in this blog post](https://theburningmonk.com/2020/04/hit-the-6mb-lambda-payload-limit-heres-what-you-can-do/). A `GET https://messages.cucumber.io/api/reports` request will now respond with `202 Accepted` and a `Location` header pointing to S3.
This is not a proper redirect, so we're handling this in the code by issuing a new `PUT` request if the status is `202` and the `Location` header is …
> Issue a PUT request after a GET request responding with 202 and a Location header

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/options/BooleanString.java
- core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
- core/src/test/java/io/cucumber/core/options/BooleanStringTest.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineOptions.java
- pom.xml
This fixes #2095
The value of a system property/enviromnent variable will resolve to `true` unless it's empty, `false`, `no` or `0`.
> Advanced boolean parsing. Fixes #2095

- RELEASING.md
- scripts/remove-empty-sections-changelog.awk
- scripts/update-changelog.sh
While releasing Cucumber-JVM 6.6.0, we ran into some issues:
- We (wrongly) assumed that setting the version is done by editing it in the root `pom.xml`, which made the release process because versions in root pom and submodules pom do not match
- We manually reverted some files and got issues with the `update-changelog.sh` script
- We were not sure that credentials for pushing artifacts to sonatype would automatically work
Overall the overall release process went smoothly. Anyway we think we can improve it even further.
> Improve release instructions

- CHANGELOG.md
- core/README.md
- core/src/main/java/io/cucumber/core/options/CucumberOptionsAnnotationParser.java
- core/src/test/java/io/cucumber/core/options/CucumberOptionsAnnotationParserTest.java
When using `cucumber.properties`
```
cucumber.snippet-type=camelcase
```
In combination with:
```
@RunWith(Cucumber.class)
@CucumberOptions
public class RunCucumberTest {
}
```
The default snippet type from `@CucumberOptions` would override the value set
by `cucumber.properties`.
> [Core] CucumberOptions default snippet type should not override properties

- CHANGELOG.md
- pom.xml
This follows  [cucumber#1168](https://github.com/cucumber/cucumber/pull/1168)
There is a security issue involved which was fixed by `cucumber-ruby-meta` 2.0.2, this change ensures we use the fixed version.
> Update creta-meta.version to v2.0.2

- CHANGELOG.md
- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/TestDescriptorOnLine.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolverTest.java
- pom.xml
There was no good way to discover and execute a single test when using a file
based test system like Cucumber. Recently JUnit added support for file position
in the `FileSelector` and `ClasspathResourceSelector`.
See: https://github.com/junit-team/junit5/issues/2146
This implements a filter that prunes all scenarios that do not match the
`FilePosition` from the discovery selector. This feature itself is not new. It
was already implemented for the `UriSelector`.
This feature will benefit the implementation of [IDEA-227508](https://youtrack.jetbrains.com/issue/IDEA-227508). If you would like to use this feature in the future please up up-vote it.
TODO:
> [JUnit Platform] Support discovery selectors with FilePosition

- Makefile
Although `docker run` should also pull automatically, we have had several people mentioning the fact they had to pull by themselves, otherwise the release script was failing.
This PR adds an explicit `docker pull` command before the `docker run`.
This was tested succesfully when releasing Cucumber-Scala.
> [Build] Explicit docker pull before docker run

- core/src/test/java/io/cucumber/core/options/CommandlineOptionsParserTest.java
- core/src/test/java/io/cucumber/core/plugin/BannerTest.java
- core/src/test/java/io/cucumber/core/plugin/NoPublishFormatterTest.java
- core/src/test/java/io/cucumber/core/plugin/UrlReporterTest.java
Fixing the encoding related problems in tests of #2104 
BannerTest, NoPublishFormatterTest, UrlReporterTest:
Using UTF-8 encoding in tests instead of relying on default encoding of the system, because otherwise the non-ascii characters are destroyed. 
CommandLineOptionsParserTest:
Removed the line endings from the comparision, so moving to the same behaviour as other non-failing tests of the same class.
> [Core] Fix platform dependent unit tests

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/plugin/UrlOutputStream.java
- core/src/test/java/io/cucumber/core/plugin/UrlOutputStreamTest.java
The `URLOutputStream` should not send headers on 2nd 202 pseudo redirect. See https://github.com/cucumber/cucumber-ruby/pull/1475 for details.
> Do not send headers after following redirection

- .mvn/jvm.config
- compatibility/src/test/resources/.gitattributes
- core/src/test/java/io/cucumber/core/resource/ResourceScannerTest.java
This should fix all remaining problems with building under windows #2104
- Disabled scanForResourcesDirectorySymlink test on windows, because it suffers from the same problem as the already disabled scanForResourcesPathSymlink test
To make build work out of the box on windows the following two changes were done:
- Set maven configuration, such that maven is always called with the file encoding set to UTF-8. This is needed, because in the generated I18N sourcefiles use UTF-8 based filenames, which are otherwise not correctly passed to the compiler. 
- Ensure, that git does not do end-of-line conversion on the resource files in the compatibility module. If it does, the feature file …
> [Compatibility] Fix platform dependent tests

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/plugin/PluginFactory.java
- core/src/test/java/io/cucumber/core/plugin/PluginFactoryTest.java
Cucumber v6 introduced a new html formatter. This formatter writes to a file
rather then a directory[1]. However a typical use to ensure all files and up
in a single folder would be `plugin=json:target/cucumber/report.json, html:target/cucumber`.
So depending on the order this results in Cucumber being unable to either
create the `target/cucumber` as file for the html report or `target/cucumber`
as a directory for the json report.
The improved error message should point this out.
Fixes: #2108
Additionally the PluginFactory tests were rewritten to make them follow the
arrange-act-test pattern.
1. https://github.com/cucumber/cucumber-jvm/blob/main/release-notes/v6.0.0.md#improved-html-formatter
> [Core] Improve error message when plugin paths collide

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/plugin/HtmlFormatter.java
- core/src/test/java/io/cucumber/core/plugin/CanonicalEventOrderTest.java
- core/src/test/java/io/cucumber/core/plugin/HtmlFormatterTest.java
Cucumber-JVM will emit all step, hook and parameter type definition for each
scenario. This results in a deluge of messages that effectively grows with
the square of the number of scenarios (more scenarios, result in more step
definitions).
Executing some 500 scenarios can result in a html report anywhere between
150 and 300 MiB. The step, hook, and parameter type definitions are not used
by the html report and can be filtered out. This reduces the report size to
some 15 MiB. While still large this is much more manageable.
Further reductions will have to come from:
1. Improvements to `cucumber/react`
2. Fixing Cucumber JVM to only define steps, hooks and parameter types once.
See: https://github.com/cucumber/cucumber/issues/1232https://github.com/cucumber/cucumber/issues/1232
> [Core] Significantly reduce the size of the html report

- CHANGELOG.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineExecutionContext.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolverTest.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/nofeatures/NoFeatures.java
Both Surefire and Gradle assume that tests are contained within a class and
use `ClassSelector` to discover tests in these classes. Cucumber uses plain
text files. By using a class annotated with `@Cucumber` we work around this
behaviour. Cucumber will then scan the package and sub-packages of the
annotated class for feature files.
When using this system, in case of misconfiguration it is not immediately clear
if the test engine is not picked up or if the location of the feature files and
annotated class do not line up.
While we can not generically log a warning in case a discovery selector did not
find any features, we can log a warning in this special case. It is clear that
the intend was to put feature files in the package. Otherwise the annotated
class could/should be removed to …
> [JUnit Platform] Warn if feature files could not be found

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/plugin/Stats.java
- core/src/test/java/io/cucumber/core/plugin/StatsTest.java
The summary printer concatenated the url and scenario name without an
additional space. This made it impossible to click the urls.
Fixes: https://github.com/cucumber/cucumber-jvm/issues/2184
> [Core] Add space between scenario url and name

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/options/PluginOption.java
- core/src/main/java/io/cucumber/core/options/RuntimeOptions.java
- core/src/test/java/io/cucumber/core/options/BooleanStringTest.java
- core/src/test/java/io/cucumber/core/options/PluginOptionTest.java
- core/src/test/java/io/cucumber/core/options/RuntimeOptionsTest.java
It is possible to declare duplicate plugins. Either through `@CucumberOptions`,
or `cucumber.plugin`, ect or a combination thereof. This can be used to ensure
certain plugins are always active during a build in CI.
Merging duplicate plugin options should ensure that plugins are not
instantiated twice with the same output.
Fixes: https://github.com/cucumber/cucumber-jvm/issues/2190
> [Core] Merge duplicate plugin options

- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolverTest.java
`UniqueId.getEngine` is not guaranteed to return `cucumber`. Another engine may
launch a discovery request for Cucumber. The engine id in this case would be
`[engine:suite][engine:cucumber]`.
> [JUnit Platform Engine] Check unique id prefix rather then engine id

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/runtime/BackendServiceLoader.java
- core/src/main/java/io/cucumber/core/runtime/ObjectFactoryServiceLoader.java
- core/src/main/java/io/cucumber/core/runtime/Runtime.java
- core/src/test/java/io/cucumber/core/runtime/BackendServiceLoaderTest.java
- core/src/test/java/io/cucumber/core/runtime/SingletonRunnerSupplierTest.java
- core/src/test/java/io/cucumber/core/runtime/ThreadLocalRunnerSupplierTest.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineExecutionContext.java
- junit/src/main/java/io/cucumber/junit/Cucumber.java
- junit/src/test/java/io/cucumber/junit/FeatureRunnerTest.java
- testng/src/main/java/io/cucumber/testng/TestNGCucumberRunner.java
> [Core] Pass class loader to ServiceLoader.load invocations

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/resource/ClasspathScanner.java
- core/src/main/java/io/cucumber/core/resource/ClasspathSupport.java
- core/src/main/java/io/cucumber/core/resource/JarUriFileSystemService.java
- core/src/main/java/io/cucumber/core/resource/PathScanner.java
- core/src/test/java/io/cucumber/core/resource/ClasspathScannerTest.java
- core/src/test/java/io/cucumber/core/resource/ResourceScannerTest.java
- java/src/main/java/io/cucumber/java/MethodScanner.java
> [Core] Log warning when classes could not be loaded

- core/src/main/java/io/cucumber/core/plugin/DefaultSummaryPrinter.java
- core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java
- core/src/main/java/io/cucumber/core/runner/Runner.java
- core/src/main/java/io/cucumber/core/runtime/TestCaseResultObserver.java
- core/src/test/java/io/cucumber/core/plugin/CanonicalEventOrderTest.java
- core/src/test/java/io/cucumber/core/plugin/DefaultSummaryPrinterTest.java
- core/src/test/java/io/cucumber/core/plugin/TeamCityPluginTest.java
- core/src/test/java/io/cucumber/core/snippets/TestSnippet.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/UndefinedStepException.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/TestCaseResultObserverTest.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/UndefinedStepExceptionTest.java
- junit/src/main/java/io/cucumber/junit/JUnitReporter.java
- junit/src/main/java/io/cucumber/junit/UndefinedStepException.java
- junit/src/test/java/io/cucumber/junit/JUnitReporterWithStepNotificationsTest.java
- plugin/src/main/java/io/cucumber/plugin/event/SnippetsSuggestedEvent.java
- testng/src/main/java/io/cucumber/testng/UndefinedStepException.java
- testng/src/test/java/io/cucumber/testng/TestCaseResultObserverTest.java
- testng/src/test/java/io/cucumber/testng/UndefinedStepExceptionTest.java
The various ways to execute Cucumber report undefined steps inconsistently.
Partially because different tools have different reporting needs. Nevertheless:
When reporting per step or scenario the suggestion should include snippets for all
undefined steps in that scenario. This applies to:
- JUnit4
- TestNG
- JUnit5
- Teamcity Plugin 
When reporting per test run the suggestion should include snippets for all
undefined steps in the execution. This applies to:
- CLI
When printing snippets they should be copy-pasted into an IDE without further
editing. This means individual snippets or groups of snippets should not be
separated by spacers, text or anything else.
Fixes: #2024
> [Core] Improve undefined step reporting

- core/src/test/java/io/cucumber/core/plugin/PluginFactoryTest.java
https://github.com/cucumber/cucumber-jvm/issues/2252
Used `getCanonicalPath()` in test as it's used in the tested class
> [Core] Use canonical path in tests

- .github/workflows/build.yml
- cdi2/pom.xml
- jakarta-cdi/pom.xml
@mpkorstanje this is an alternate maven configuration that lets you run the tests with both openwebbeans and weld.
It is also possible to enable just one implmentation with the profiles `cdi2-openwebbeans` and `cdi2-weld` like before.
The only issue is that the default profile will break the tests in the IDE.
I use eclipse and to be able to run unit tests I have to activate the `cdi2-openwebbeans` or `cdi2-weld` profile in the project configuration.
I let you judge if you like it.
> [Cdi2/Jakarta Cdi] Run tests for OpenWebBeans and Weld in CI

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java
- core/src/test/java/io/cucumber/core/plugin/TeamCityPluginTest.java
The teamcity plugin communicates test results to IntelliJ IDEA using teamcity
service messages[1]. Currently the teamcity plugin marks pending steps as
skipped rather then failed. This is inconsistent with the changes from #1960
in which pending steps are considered a test failure.
1: https://www.jetbrains.com/help/teamcity/service-messages.html
> [Core] Mark pending steps as failed in teamcity plugin

- CHANGELOG.md
- core/README.md
- core/src/main/java/io/cucumber/core/cli/CommandlineOptions.java
- core/src/main/java/io/cucumber/core/options/CommandlineOptionsParser.java
- core/src/main/java/io/cucumber/core/options/Constants.java
- core/src/main/java/io/cucumber/core/options/CucumberOptionsAnnotationParser.java
- core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
- core/src/main/resources/io/cucumber/core/options/USAGE.txt
- core/src/test/java/io/cucumber/core/options/CommandlineOptionsParserTest.java
- core/src/test/java/io/cucumber/core/options/CucumberOptions.java
- core/src/test/java/io/cucumber/core/options/CucumberOptionsAnnotationParserTest.java
- core/src/test/java/io/cucumber/core/plugin/StatsTest.java
- core/src/test/java/io/cucumber/core/runtime/ExitStatusTest.java
- core/src/test/java/io/cucumber/core/runtime/RuntimeTest.java
- junit/src/main/java/io/cucumber/junit/CucumberOptions.java
- junit/src/main/java/io/cucumber/junit/JUnitCucumberOptionsProvider.java
- junit/src/test/java/io/cucumber/junit/JUnitReporterWithStepNotificationsTest.java
- testng/src/main/java/io/cucumber/testng/CucumberOptions.java
- testng/src/main/java/io/cucumber/testng/TestNGCucumberOptionsProvider.java
- testng/src/test/java/io/cucumber/testng/TestNGCucumberRunnerTest.java
Cucumber executes scenarios in strict mode by default.
Fixes: #1788
> [Core] Remove --strict and --no-strict options

- core/src/main/resources/io/cucumber/core/options/USAGE.txt
--add-plugin is no longer a valid synonym for --plugin; it was removed in https://github.com/cucumber/cucumber-jvm/commit/839dba7ccc734428d95a628c3886356ed9ed1677 .  But the USAGE still listed it as a synonym.
> [Core] Remove --add-plugin alternate name from USAGE.txt

- compatibility/src/test/java/io/cucumber/compatibility/CompatibilityTest.java
- core/src/main/java/io/cucumber/core/plugin/PrettyFormatter.java
- core/src/test/java/io/cucumber/core/plugin/PrettyFormatterTest.java
- relates to issue #2320 
- updates `PrettyFormatter.printStep` to process the `DataTable` if one is present in the step object
- uses DataTableFormatter exposed in cucumber-common v4 / [this PR](https://github.com/cucumber/common/pull/1624)
- at the moment just figuring out a broken `StepExpressionFactoryTest` that's popped up elsewhere in the core module while QA testing (appears to be from bumping common to v4)
- opened up the PR as a draft in the meantime, in case of feedback/a different approach is needed
> [Core] Pretty formatter to print step DataTables

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/runtime/Runtime.java
- junit/src/main/java/io/cucumber/junit/Cucumber.java
- testng/src/main/java/io/cucumber/testng/TestNGCucumberRunner.java
We can not exclude the possibility that an event is published to the event bus
after test execution has completed. For example because the test framework may
have decided that a test case has timed out and is now terminating test
execution.
As such events from the pending testcase on the synchronized bus may race with
the events from the unsynchronized bus. This in turn may break the `LinkedList`
in the `CanonicalOrderEventPublisher`.
Fixes: #2288 (mabye??)
> [Core] Synchronize event bus before use

- CHANGELOG.md
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesExample.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesExamples.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesFeature.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesRule.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesScenario.java
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesScenarioOutline.java
- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Constants.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineOptions.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DefaultNamingStrategy.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolver.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/NamingStrategy.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/FeatureResolverTest.java
- plugin/src/main/java/io/cucumber/plugin/event/Node.java
- plugin/src/test/java/io/cucumber/plugin/event/NodeTest.java
When using:
```
cucumber.junit-platform.naming-strategy=long
```
Cucumber will output the node names as:
```
[root]
Basic Arithmetic
Basic Arithmetic - Addition
Basic Arithmetic - Another Addition
Basic Arithmetic - Many additions
Basic Arithmetic - Many additions - Single digits
Basic Arithmetic - Many additions - Single digits - Example #1
Basic Arithmetic - Many additions - Single digits - Example #2
Basic Arithmetic - Many additions - Double digits
Basic Arithmetic - Many additions - Double digits - Example #1
Basic Arithmetic - Many additions - Double digits - Example #2
Dates with different date formats
Dates with different date formats - Determine past date
Shopping
Shopping - Give correct change
```
Useful when dealing with tools such as Surefire and Gradle that do not include
the …
> [JUnit Platform] Optionally use long names

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/runner/TestCaseState.java
- core/src/test/java/io/cucumber/core/runner/TestCaseStateTest.java
- java/src/main/java/io/cucumber/java/Scenario.java
- java8/src/main/java/io/cucumber/java8/Scenario.java
To obtain the original `<uri>:<line-number>` identifier use
`scenario.getUri() + ":" + scenario.getLine()`.
Closes: #2254
> [Core] Make Scenario.getId() return the actual scenario id

- core/src/main/java/io/cucumber/core/plugin/PrettyFormatter.java
- core/src/test/java/io/cucumber/core/plugin/PrettyFormatterTest.java
When dealing with undefined steps, or steps that do not have a location the
pretty formatter prints a null value. This print should be omitted.
```
Scenario: a few cukes               # io/cucumber/skeleton/belly.feature:3
Given I have 42 cukes in my belly # io.cucumber.skeleton.StepDefinitions.I_have_cukes_in_my_belly(int)
When I wait 1 hour                # null
Then my belly should growl        # null
```
> [Core] pretty formatter should not print null locations

- .github/workflows/build.yml
- java8/pom.xml
Because of https://github.com/jdcasey/directory-maven-plugin/issues/16 Cucumber JVM can not be build with Maven > 3.8. However Ubuntu Latest used by Github actions now includes Maven 3.8.2. This is a temporary fix until we can build with the provided Maven version again.
> [Build] Build with with Maven wrapper in CI

- core/src/main/java/io/cucumber/core/plugin/UsageFormatter.java
- core/src/test/java/io/cucumber/core/plugin/UsageFormatterTest.java
The usage formatter is re(ab)using the json formatter from messages. While it
is technically feasible to come up with a solution that does not do this it
would be better to redesign the formatter with a table-like human-readable
output in mind. As such we can defer this decision to a later point in time.
Fixes: https://github.com/cucumber/cucumber-jvm/issues/2381
> [Core] Fix usage formatter serialization

- archetype/pom.xml
When a type is not explicitly provided, the bundled Maven version used by
InteliJ IDEA explicitly looks for a jar type dependency. Making this explicit
allows the dependency to be resolved correctly.
> [Archetype] Fix dependency resolution in InteliJ IDEA

- .github/workflows/build.yml
As a workaround for https://github.com/jdcasey/directory-maven-plugin/issues/16
the build in CI was done with the Maven wrapper. With the release of v1.0 of
the `directory-maven-plugin` this work around is no longer needed
> [Build] Do not download Maven Wrapper in CI

- examples/calculator-java-junit5/pom.xml
- junit-platform-engine/README.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Constants.java
JUnit 5 can filter test cases by name or tag as part of its
discover/select/execute model. Cucumber can also filter scenarios based on
their name or tags. To ensure this functionality does not interfere with
JUnit 5s model by hiding scenarios from discovery this is implemented through
`Node.shouldBeSkipped`.
As a result when using `cucumber.filter.*` for each skipped scenario JUnit 5
will explicitly report that:
```
'cucumber.filter.tags=@foo' did not match this scenario
```
while Cucumber will quietly skip the scenario in the reports.
> [JUnit Platform] Discourage use of Cucumber filters

- CHANGELOG.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineExecutionContext.java
> [JUnit Platform] Delay plugin creation until test execution

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/plugin/UrlOutputStream.java
- core/src/test/java/io/cucumber/core/plugin/UrlOutputStreamTest.java
> [Core] Display curl-like error message for more url output stream problems

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/options/Constants.java
- core/src/main/java/io/cucumber/core/options/CurlOption.java
- core/src/main/java/io/cucumber/core/plugin/PublishFormatter.java
- core/src/main/java/io/cucumber/core/plugin/UrlOutputStream.java
- core/src/test/java/io/cucumber/core/options/CurlOptionTest.java
Users looking to publish cucumber reports behind a proxy can add to
`cucumber.properties`:
```
cucumber.publish.proxy=https://proxy.example.com:3129
```
Note: The publish-plugin only reads properties from the `cucumber.properties`,
the environment, system properties. And not `junit-platform.properties`. 
Fixes: #2285
> [Core] Support proxy for publish plugin

- java/pom.xml
- java/src/main/groovy/generate-annotations.groovy
- java8/pom.xml
- java8/src/main/groovy/generate-interfaces.groovy
- pom.xml
I've been unable to compile the project using `asdf`'s `openjdk-11`, getting "Unsupported class file major version 60" errors.
Switching to `groovy-maven-plugin` fixes the problem. (I discovered this when I configured code generation in https://github.com/cucumber/ci-environment/blob/main/java/pom.xml a few weeks ago).
With this change, the project now builds with `openjdk-16` as well. We should update the GitHub Actions to use a matrix including more JDK versions.
> Replace maven-antrun-plugin with groovy-maven-plugin

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/stepexpression/DocStringArgument.java
- core/src/main/java/io/cucumber/core/stepexpression/StepExpression.java
- docstring/src/main/java/io/cucumber/docstring/DocStringTypeRegistry.java
- docstring/src/main/java/io/cucumber/docstring/DocStringTypeRegistryDocStringConverter.java
- docstring/src/test/java/io/cucumber/docstring/DocStringTypeRegistryDocStringConverterTest.java
- java/src/main/java/io/cucumber/java/DocStringType.java
> [Core] Look up docstring converter by type as fallback

- CHANGELOG.md
- core/src/main/java/io/cucumber/core/runtime/CucumberExecutionContext.java
> [Core] Fix Uncaught TypeError: e.git is undefined

- core/src/main/java/io/cucumber/core/plugin/PluginFactory.java
https://github.com/cucumber/cucumber-jvm/issues/2108
Variables file and canonicalFile should be the file on the file system. Native code throws Exception when opening file.
canonicalFile is possible.
> [Core] Use canonical file name to create FileOutputStream for plugins

- core/pom.xml
- gherkin-messages/pom.xml
- java/pom.xml
- java8/pom.xml
With Maven 3.8.5 as used in CI only direct dependencies can be shaded. So to
build correctly Gherkin has to be included as a direct dependency. This however
confuses revapi because it does not seem to account for shading. And has been
disabled for now.
> [Build] Explicitly include Gherkin as a dependency for shading

- .github/workflows/build.yml
- pom.xml
Spotless reformats the code to the default when building locally. This should
not run in CI. Then we can't check if the code was properly formatted.
Additionally CI should only run each job once rather then once for a push
or for a merge request.
> [Build] Disable spotless apply in ci

- CHANGELOG.md
- spring/src/main/java/io/cucumber/spring/CucumberScenarioScope.java
- spring/src/main/java/io/cucumber/spring/CucumberTestContext.java
- spring/src/main/java/io/cucumber/spring/SpringFactory.java
- spring/src/main/java/io/cucumber/spring/TestContextAdaptor.java
- spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
The `TestContextAdaptor` would start the scenario scope once at the start of
each test, then another one to run the after test method hooks. Refactored
code to make the order of operations more obvious.
Also prevented scenario scopes from being registered more then once. Though
because `CucumberScenarioScope` delegates everything to `CucumberTestContext`
this effectively only reduces the log spam a bit at debug level.
Fixes: #2516
> [Spring] Start and stop test context once per scenario 

- CHANGELOG.md
- junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureOrigin.java
- junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolverTest.java
- junit-platform-engine/src/test/resources/io/cucumber/junit/platform/engine/with space.feature
* Add a file with a space in test cases.
* Replace URI.getSchemeSpecificPart by URI.getRawSchemeSpecificPart to
keep space encoded.
Fixes #2520 
> [JUnit Platform] Support feature files with space in filename

- CHANGELOG.md
- gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesFeatureParser.java
`Collectors.toUnmodifiableList` was introduced since java 10. Which is slightly too modern for us to use.
Fixes #2530
----
> [Core] Remove usage of Collectors.toUnmodifiableList

- core/src/main/java/io/cucumber/core/plugin/PrettyFormatter.java
- core/src/test/java/io/cucumber/core/plugin/PrettyFormatterTest.java
- Added a test case (should_print_encoded_characters) that prints URL encoded characters to the scenario in the form of a table .
- Adjusting of PrettyFormater .. instead of using String.format(..) - just appending
1. the scenario indentation
2. the line to be printed
3. systems line-separator
.. to the StringBuilder.
Fixes issues 2544
> Fix problem with PrettyFormatter printing URL encoded strings

- CHANGELOG.md
- guice/src/main/java/io/cucumber/guice/GuiceBackend.java
- guice/src/test/java/io/cucumber/guice/GuiceBackendTest.java
- java/src/main/java/io/cucumber/java/JavaBackend.java
- java/src/test/java/io/cucumber/java/JavaBackendTest.java
- java8/src/main/java/io/cucumber/java8/Java8Backend.java
- java8/src/test/java/io/cucumber/java8/Java8BackendTest.java
- spring/pom.xml
- spring/src/main/java/io/cucumber/spring/SpringBackend.java
- spring/src/test/java/io/cucumber/spring/SpringBackendTest.java
Users may provide glue paths where one is a strict subset of hte other.
For example:
```
com.example
com.example.app
```
Cucumber would scan both packages (and sub packages), and for each process the
classes it discovered. This would result in the classes from the `app` package
being processed twice.
Fixes: #2581
> [Java] Process glue classes distinctly

- CHANGELOG.md
- spring/src/main/java/io/cucumber/spring/TestContextAdaptor.java
- spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
> [Spring] Do not invoke after test method if test failed to start

- cucumber-junit-platform-engine/README.md
Clarify that Cucumber does not guarantee a maximum number of threads.
Closes: #2512
> [JUnit Platform] Update parallel execution documentation

- CHANGELOG.md
- datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistry.java
- datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTest.java
Aims to fix https://github.com/cucumber/cucumber-jvm/issues/2611
Added a `TableCellTransformer` for `Boolean` and `boolean` which replacable.
N/A
N/A
> [Datatable] Support boolean parsing in Datatables

- .github/workflows/test-java.yml
- CHANGELOG.md
Consistently added just behind --batch-mode, as that normally disables color
Always color Maven output in GitHub workflows with -Dstyle.color=always
Makes it easier to spot any issues, even with the default imperfect red/green color scheme.
Pushed as a branch rather than through a fork; or would you have preferred me to use a fork still?
> Always color Maven output in GitHub workflows with -Dstyle.color=always

- CHANGELOG.md
- cucumber-core/pom.xml
Like everyone else Cucumber needs to write Json and does so using Jackson. To avoid conflicts with other versions of Jackson, Cucumber shades its own version. Unfortunately this shading isn't done perfectly and the files in `META-INF/services` are not updated to match.
By excluding the services declared by Jackson we can avoid this problem altogether, though it may come back in the future if/when Jackson decides to use its own services outside of `ObjectMapper.findAndRegisterModules`. Hopefully, the shade plugin has been fixed by then.
Fixes: #2620
> Remove Jackson services from META-INF

- release-notes/v7.0.0.md
As well as how to migrate automatically. 
As [discussed via Slack](https://cucumberbdd.slack.com/archives/C6RLMP3C4/p1664789917517839)
> Add section on possible Cucumber-Java8 deprecation

- cucumber-core/src/main/java/io/cucumber/core/runtime/Runtime.java
- cucumber-core/src/test/java/io/cucumber/core/runtime/RuntimeTest.java
With v7.6.0 in 3bc80b964971f9a61f6d22d6fe772499edbb8933 before all and after
all hooks were introduced. This moved parsing of features into the execution
context. This resulted in any parse errors being swallowed with the assumption
that they would have been captured by the execution context already.
Fixes: #2631
> [Core] Don't swallow parse errors on the CLI

- cucumber-spring/README.md
- cucumber-spring/src/main/java/io/cucumber/spring/CucumberTestContext.java
Documented that scenario scope is proxied.
Closes: #2647
> [Spring] Document scenario scope is proxied

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/options/PluginOption.java
This bans the use of the incompatible plugins 
```
io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm
io.qameta.allure.cucumber6jvm.AllureCucumber6Jvm
```
This will prevent users from making the mistake of using the wrong plugin
version with Cucumber. This avoids questions and noise all around.
----
> [Core] Mark Allure 5 and 6 plugins as incompatible

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/runtime/Runtime.java
- cucumber-core/src/test/java/io/cucumber/core/backend/StubPendingException.java
- cucumber-core/src/test/java/io/cucumber/core/runtime/RuntimeTest.java
- pom.xml
The runtime would collect exceptions thrown upon emitting the TestRunFinished
event. The assumption was that these were collected in the test context.
Though this is impossible. The test context is collecting exceptions to include
in the report. So it sits inside the test run started and finished events.
> [Core] Emit exceptions on failure to handle test run finished events

- CHANGELOG.md
- cucumber-spring/src/main/java/io/cucumber/spring/TestContextAdaptor.java
- cucumber-spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
- cucumber-spring/src/test/java/io/cucumber/spring/TestTestContextAdaptorTest.java
To make writing tests with Spring easier Spring provides a
`TestContextManager`. This classes provides call backs for various
`TestExecutionListeners`.
These are then used by various extensions such as
the `MockitoTestExecutionListener` which injects `@MockBeans` into test
instances. When all methods are not invoked this leads to problems such as
(#2654,#2655,#2656)
While this was initially (#1470) not a problem, it appears that various
listener implementations have started to assume that all methods would be
invoked.
Closes: #2655
Fixes: #2654, #2572
> [Spring] Invoke all TestContextManager methods

- CHANGELOG.md
- cucumber-spring/src/main/java/io/cucumber/spring/TestContextAdaptor.java
- cucumber-spring/src/test/java/io/cucumber/spring/TestTestContextAdaptorTest.java
In #2661 classes annotated with `@CucumberContextConfiguration` were created as beans directly from the bean factory. This allowed them to be prepared as test instances by JUnit. However, we did not tell the factory that it should autowire constructor dependencies resulting in #2663.
Additionally, because beans were created directly from the bean factory, they were not added to the application context. This meant that while dependencies could be injected into them, they could not be injected into other objects.
Fixes: #2663
> [Spring] Inject CucumberContextConfiguration constructor dependencies

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/runner/TestAbortedExceptions.java
- cucumber-core/src/test/java/io/cucumber/core/runner/TestAbortedExceptionsTest.java
Refactored `TestAbortedExceptions` `Predicate` creation.
Performance gain (`Predicate` creation is about 50'000 times faster).
Fixes #2666 
Nothing.
> Improved TestStep creation performance

- CHANGELOG.md
- cucumber-deltaspike/pom.xml
- cucumber-deltaspike/src/test/java/io/cucumber/deltaspike/Belly.java
- cucumber-deltaspike/src/test/resources/META-INF/beans.xml
It appeared that DeltaSpike wouldn't work on Java 17. This could be resolved by upgrading to CDI 2.0.
Closes #2650.
> [DeltaSpike] Un-deprecate Deltaspike

- CHANGELOG.md
- cucumber-junit-platform-engine/README.md
With JUnit 5.9.2 we pull in junit-team/junit5#3044 which makes it possible to limit the maximum number of threads used while executing in parallel.
Closes: #2677
> [JUnit Platform] Document fixed.max-pool-size property

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/options/Constants.java
- cucumber-core/src/main/java/io/cucumber/core/options/CucumberPropertiesParser.java
- cucumber-core/src/test/java/io/cucumber/core/options/CucumberPropertiesParserTest.java
In #1779 we deprecated and removed cucumber.options. Unfortunately there are a slew of outdated tutorials still in existence. And this outdated knowledge creates a slow trickle of questions on StackOverflow. It would be nice if we can stop this waste of everyone's time.
Fixes: #2673
> [Core] Warn when cucumber.options is used

- .gitignore
- CHANGELOG.md
- cucumber-spring/src/main/java/io/cucumber/spring/SpringFactory.java
- cucumber-spring/src/main/java/io/cucumber/spring/TestContextAdaptor.java
- cucumber-spring/src/test/java/io/cucumber/spring/TestTestContextAdaptorTest.java
- cucumber-spring/src/test/resources/io/cucumber/spring/springbootparallel.feature
As suggestion from #help channel, I'm trying to put TestContextManager initiation to the synchronized block inside start method of TestContextAdaptor to resolve the racing problem of spring boot 3 cucumber test.
Fixes https://github.com/cucumber/cucumber-jvm/issues/2686
----
> [Spring] Instantiate TestContextManager synchronously

- CHANGELOG.md
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CachingFeatureParser.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolver.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureDescriptor.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/NodeDescriptor.java
- cucumber-junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolverTest.java
The JUnit Platform allows Scenarios and Examples to be selected by their
unique id. This id is stable between test executions and can be used to rerun
failing Scenarios and Examples.
For practical reasons each unique id is processed individually[+] and results
in a feature file being parsed. The parsed feature is then compiled into
pickles. Both are mapped to a hierarchy of JUnit 5 test descriptors. These are
then merged. The merge process will discard any duplicate nodes.
Each time a feature file is parsed the parser will assign unique identifiers
to all ast nodes and pickles. As a result the merged hierarchy of junit test
descriptors contained pickles that belonged to a different feature file.
This poses a problem for tools such as the junit-xml-formatter that depend on
the identifiers …
> [JUnit Platform Engine] Cache parsed features

- CHANGELOG.md
- cucumber-junit-platform-engine/README.md
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Constants.java
> [JUnit Platform Engine] Add constant for fixed.max-pool-size property

- CHANGELOG.md
- cucumber-picocontainer/src/main/java/io/cucumber/picocontainer/PicoFactory.java
- cucumber-picocontainer/src/test/java/io/cucumber/picocontainer/DisposableCucumberBelly.java
- cucumber-picocontainer/src/test/java/io/cucumber/picocontainer/PicoFactoryTest.java
- cucumber-picocontainer/src/test/java/io/cucumber/picocontainer/StepDefinitionsWithTransitiveDependencies.java
Improved picontainer performance by reusing the library initialization (basically: clear the cache on `stop()`).
Solves #2724 .
The issue cannot be resolved in the picocontainer library itself (https://github.com/picocontainer/picocontainer/issues/11) because the library seems not maintained anymore.
> [Pico] Improved performance

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/runner/CachingGlue.java
- cucumber-core/src/test/java/io/cucumber/core/runner/CachingGlueTest.java
The `ParameterType` emited on the event bus contains now the `SourceReference`.
Fixes #2719
N/A
> [Core] Add ParameterType message source reference

- CHANGELOG.md
- cucumber-picocontainer/src/main/java/io/cucumber/picocontainer/PicoFactory.java
- cucumber-picocontainer/src/test/java/io/cucumber/picocontainer/StepDefinitionsWithTransitiveDependencies.java
Classes registration in picoccontainer have changed from order top->down to bottom-up, which is required when one class in the hierarchy implements `Disposable`.
Fixes #2762
N/A
> [Pico] Fixed UnsatisfiableDependencyException with Component dependencies 

- CHANGELOG.md
- cucumber-picocontainer/src/main/java/io/cucumber/picocontainer/PicoFactory.java
- cucumber-picocontainer/src/test/java/io/cucumber/picocontainer/DisposableCucumberBelly.java
- cucumber-picocontainer/src/test/java/io/cucumber/picocontainer/StepDefinitions.java
Corrected the pico-container lifecycle: the start, stop and dispose methods are now called for every test scenarios.
The code is the same as before #2725 (so it's safer in terms of lifecycle), except that the pico container is recycled in the `start()` method when it already exists. 
When a second call to `start()` is done (e.g. for the 2nd scenario), the container component instances are all in disposed state and the container lifecycle is in disposed state. The recycling operation consists in removing all container component instances (i.e. flushing the cache) and resetting the container lifecycle.
Fixes #2771
I tested the new version on a project with ~480 test scenarios and saw no performance difference when compared to …
> [Pico] Fixed missing calls to start, stop and dispose handles

- cucumber-core/src/test/java/io/cucumber/core/eventbus/RandomUuidGeneratorTest.java
- cucumber-core/src/test/java/io/cucumber/core/exception/UnrecoverableExceptionsTest.java
- cucumber-core/src/test/java/io/cucumber/core/options/RuntimeOptionsBuilderTest.java
- cucumber-core/src/test/java/io/cucumber/core/options/UuidGeneratorParserTest.java
- cucumber-core/src/test/java/io/cucumber/core/runner/CachingGlueTest.java
- cucumber-core/src/test/java/io/cucumber/core/runner/HookTestStepTest.java
- cucumber-core/src/test/java/io/cucumber/core/runner/PickleStepTestStepTest.java
- cucumber-core/src/test/java/io/cucumber/core/runner/ThrowableCollectorTest.java
- cucumber-core/src/test/java/io/cucumber/core/runtime/ObjectFactoryServiceLoaderTest.java
- cucumber-core/src/test/java/io/cucumber/core/runtime/ServiceLoaderTestClassLoader.java
- cucumber-core/src/test/java/io/cucumber/core/runtime/UuidGeneratorServiceLoaderTest.java
- cucumber-gherkin/src/test/java/io/cucumber/core/gherkin/FeatureParserTest.java
- cucumber-java8/src/test/java/io/cucumber/java8/Java8BackendTest.java
- cucumber-picocontainer/src/test/java/io/cucumber/picocontainer/StepDefinitions.java
- cucumber-spring/src/test/java/io/cucumber/spring/Issue1970Test.java
- cucumber-spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
- cucumber-spring/src/test/java/io/cucumber/spring/annotationconfig/AnnotationContextConfiguration.java
- cucumber-spring/src/test/java/io/cucumber/spring/cucumbercontextconfigannotation/WithInheritedAnnotation.java
- cucumber-spring/src/test/java/io/cucumber/spring/cucumbercontextconfigannotation/WithMetaAnnotation.java
- cucumber-spring/src/test/java/io/cucumber/spring/threading/ThreadingStepDefinitions.java
- datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTest.java
- datatable/src/test/java/io/cucumber/datatable/NoConverterDefinedTest.java
- datatable/src/test/java/io/cucumber/datatable/TableDifferTest.java
- docstring/src/test/java/io/cucumber/docstring/DocStringTypeRegistryTest.java
- examples/calculator-java-cli/src/test/java/io/cucumber/examples/calculator/ShoppingStepDefinitions.java
- pom.xml
Enabled check style on test classes and fixed the violations.
> [All] Apply checkstyle on test classes

- CHANGELOG.md
- cucumber-core/pom.xml
Cucumber-JVM uses Jackson Databind to write json. Because Jackson is a very common dependency, to ensure we do not interfere with the system under test, we shade it.
Unfortunately the Shade plugin occasionally gets updates and now includes multi-releases. These were not included in the relocation pattern and result in duplicate classes when Cucumber itself is shaded.
As `cucumber-core` is not a multi-release jar, we can exclude the multi- release files altogether.
Fixes: #2786
> Exclude Multi-Release files from Jackson while shading

- .mvn/wrapper/maven-wrapper.properties
No breaking changes and brought over this pull request, the only thing is adding an entry on the `maven-wrapper.properties `  `distributionSha256Sum` 
To be able to validate the content of the downloaded binary with a given sha256sum and to be sure that nothing is missing or it or not corrupted
It's about adding a new entry for `distributionSha256Sum` on `maven-wrapper.properties`
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to- …
> Add Sha256sum to validate the maven binary used for the building the project

- cucumber-junit-platform-engine/README.md
Documented how to run a single feature or scenario when using the JUnit Platform.
- https://stackoverflow.com/questions/77201970
- https://github.com/junit-team/junit5/issues/3366#event-10522665519
- :book: Documentation
> [JUnit Platform] Document how to run a single feature or scenario

- CHANGELOG.md
- cucumber-guice/src/main/java/io/cucumber/guice/GuiceFactory.java
- cucumber-guice/src/main/java/io/cucumber/guice/InjectorSourceFactory.java
- cucumber-guice/src/test/java/io/cucumber/guice/GuiceFactoryTest.java
- cucumber-guice/src/test/java/io/cucumber/guice/InjectorSourceFactoryTest.java
> [Guice] Inject static fields prior to before all hooks

- cucumber-core/src/test/java/io/cucumber/core/plugin/MessageFormatterTest.java
Created this PR to fix 1 flaky test - [test](https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/test/java/io/cucumber/core/plugin/MessageFormatterTest.java#L22).
----
1. **How were these test identified as flaky?**
This test was identified as flaky by using an open-source research tool named [NonDex](https://github.com/TestingResearchIllinois/NonDex) which is responsible for finding and diagnosing non-deterministic runtime exceptions in Java programs.
2. **What was the error?**
When the test convert bytes to json string `String ndjson = new String(bytes.toByteArray(), UTF_8);`, the order of keys (i.e. seconds, nano, testRunStarted, testRunFinished, etc) is not guaranteed. Thus, when we compare this String …
> Fix test failure by comparing json instead of strings

- CHANGELOG.md
- cucumber-junit-platform-engine/README.md
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Constants.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineDescriptor.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberTestEngine.java
- cucumber-junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/CucumberTestEngineTest.java
Maven Surefire and Gradle do not (yet?) fully support the JUnit Platform API[1]. To work around this problem the `cucumber.features` can be used.
However, because Maven Surefire and Gradle only attempt to discover class based tests, they do expect a class source. As a result of this missing source, Maven Surefire will not report on the executed tests while Gradle reports the tests as having been executed by an "Unknown Class".
By having the Cucumber TestEngine pretend to have a ClassSource when `cucumber.features` is used both these problems go away.
1. https://github.com/cucumber/cucumber-jvm/pull/2498
> [JUnit Platform Engine] Improve Maven and Gradle compatibility

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/eventbus/IncrementingUuidGenerator.java
- cucumber-core/src/test/java/io/cucumber/core/eventbus/IncrementingUuidGeneratorTest.java
Corrected a test-case which fails rarely but sometimes.
Added possibility to give a specific classloader identifier.
Fixes #2851
The comments in #2851 describe the problem and solution.
> Improved support for multiple classloaders in IncrementingUuidGenerator

- cucumber-archetype/src/main/resources/archetype-resources/src/test/java/RunCucumberTest.java
- cucumber-archetype/src/test/resources/projects/should-generate-project/reference/src/test/java/com/example/RunCucumberTest.java
- cucumber-cdi2/src/test/java/io/cucumber/cdi2/example/RunCucumberTest.java
- cucumber-deltaspike/src/test/java/io/cucumber/deltaspike/RunCucumberTest.java
- cucumber-guice/src/test/java/io/cucumber/guice/integration/RunCucumberTest.java
- cucumber-jakarta-cdi/src/test/java/io/cucumber/jakarta/cdi/example/RunCucumberTest.java
- cucumber-jakarta-openejb/src/test/java/io/cucumber/jakarta/openejb/RunCucumberTest.java
- cucumber-java/src/test/java/io/cucumber/java/annotation/RunCucumberTest.java
- cucumber-java/src/test/java/io/cucumber/java/defaultstransformer/RunCucumberTest.java
- cucumber-java8/src/test/java/io/cucumber/java8/RunCucumberTest.java
- cucumber-junit-platform-engine/README.md
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Cucumber.java
- cucumber-kotlin-java8/src/test/kotlin/io/cucumber/kotlin/RunCucumberTest.kt
- cucumber-openejb/src/test/java/io/cucumber/openejb/RunCucumberTest.java
- cucumber-spring/README.md
- examples/calculator-java-junit5/src/test/java/io/cucumber/examples/calculator/RunCucumberTest.java
- examples/spring-java-junit5/src/test/java/io/cucumber/examples/spring/application/RunCucumberTest.java
- release-notes/v7.0.0.md
`@SelectClasspathResource` is intended to be used for single resources whereas `@SelectPackages` is intended for packages containing those resources.
Currently, it doesn't matter because Cucumber is smart enough to scan everything given a directory. But we may want to change that in the future when we use JUnits `EngineDiscoveryRequestResolver` API (https://github.com/cucumber/cucumber-jvm/pull/2835).
- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without
> [JUnit Platform Engine] @SelectPackages not @SelectClasspathResource

- CHANGELOG.md
- cucumber-bom/pom.xml
- cucumber-core/src/main/java/io/cucumber/core/runner/TestStep.java
- cucumber-core/src/main/java/io/cucumber/core/runtime/CucumberExecutionContext.java
Before
After
Depends on https://github.com/cucumber/messages/pull/213
Depends on https://github.com/cucumber/cucumber-junit-xml-formatter/pull/30
With https://github.com/cucumber/react-components/pull/345 the html formatter started to support rendering stack traces. Unfortunately this also broke the regular rendering of stacktrace. And fixing this required including the stack trace the xml report aswell so that when the `Convertor` in messages was fixed to always include the stacktrace, we wouldn't render the stacktrace in the xml formatter twice.
> [Core] Include stack traces in html report

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/TeamCityPluginTest.java
Hi, this closes [#2798](https://github.com/cucumber/cucumber-jvm/issues/2798). changes:
The TeamCityPlugin for IntelliJ IDEA now uses the hook's method name for the name of the hook itself.
For example, if we have a hook with the method name `com.example.HookDefinition.beforeHook()`, the generated name will be `Before(beforeHook)`.
If we have a hook with the method name `com.example.HookDefinition.<init>(HookDefinition.java:12)`, the generated name will be `Before(HookDefinition)`.
If the hook's method can't be identified then fallback to simple hook name.
> [Core] Add hook method name to TeamCityPlugin

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/feature/FeatureWithLines.java
- cucumber-core/src/main/java/io/cucumber/core/filter/LinePredicate.java
- cucumber-core/src/test/java/io/cucumber/core/filter/LinePredicateTest.java
- cucumber-gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/CucumberQuery.java
- cucumber-gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesPickle.java
- cucumber-gherkin/src/main/java/io/cucumber/core/gherkin/Pickle.java
Given a feature file, it should be possible to provide the line of a Feature, Rule, Scenario, Example and Example. Cucumber should then run all pickles contained in these elements.
For example `example.feature:5:13` should run the cucumber, gherkin and pickle pickles. While `example.feature:10` runs the zukini and pickle pickles. And using either lines 1, 2 or 3 would run all pickles.
```feature
Feature: Example feature                      #  1
Rule: Example rule                          #  2
Scenario Outline: Example scenario        #  3
Given I have 4 <thing> in my belly     #  4
Examples: First                        #  5
| thing    |                         #  6
| cucumber |                         #  7
| gherkin  |                         #  8
Examples: Second …
```
> [Core] Allow feature with line syntax to target rules and examples

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/runner/PickleStepDefinitionMatch.java
- cucumber-core/src/test/java/io/cucumber/core/runner/StepDefinitionMatchTest.java
Add step location in case of datatable conversion error
The goal of this feature is to be able to identify easily the step when a dataTable conversion fail. 
Previous this PR in case of conversion error, we have this type of error: 
```
Step failed
java.lang.RuntimeException: This is an error
at com.deblock.cucumber.TestStep.convert(TestStep.java:58)
```
By we don't know which step fail. With the new version, the error looks like 
```
java.lang.RuntimeException: This is an error
at com.deblock.cucumber.TestStep.convert(TestStep.java:58)
at ✽.this is a test(file:///..../test.feature:4)
```
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-iss …
> Add step location in case of datatable conversion error

- CHANGELOG.md
- cucumber-spring/README.md
- cucumber-spring/src/main/java/io/cucumber/spring/CucumberContextConfiguration.java
Cucumber uses Spring Test Context Manager framework. This framework was written for JUnit and assumes that there is a "test instance". Cucumber however uses multiple step definition classes and so it has multiple test instances.
Originally `@CucumberContextConfiguration` was added to signal to Spring which class should be used to configure the application context from. But as people also expected mock beans and other features provided by Springs test execution listeners to work (#2661) the annotated instance was only instantiated but never initialized by Spring.
This changed the semantics somewhat as now features that depend on the bean being initialized stopped working (#2886). Unfortunately, there is little that can be done here. Spring expects that the instance provided to the Test …
> [Spring] Document CucumberContextConfiguration semantics

- .revapi/api-changes.json
- CHANGELOG.md
- cucumber-core/README.md
- cucumber-core/src/main/java/io/cucumber/core/eventbus/IncrementingUuidGenerator.java
- cucumber-core/src/main/java/io/cucumber/core/runner/CachingGlue.java
- cucumber-core/src/main/java/io/cucumber/core/runner/CoreHookDefinition.java
- cucumber-core/src/main/java/io/cucumber/core/runtime/UuidGeneratorServiceLoader.java
- cucumber-junit-platform-engine/README.md
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineExecutionContext.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java
- cucumber-junit/src/main/java/io/cucumber/junit/Cucumber.java
- cucumber-testng/src/main/java/io/cucumber/testng/TestNGCucumberRunner.java
- pom.xml
Made it  possible to actually use the custom UUID generators in test runners
With #2703 a faster UUID generator was introduced. And while the
configuration options were added, they were not actually used by 
`cucumber-junit`, `cucumber-junit-platform-engine` and
`cucumber-testng`.
> [Core] Support custom UUID generators in test runners

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/eventbus/IncrementingUuidGenerator.java
- cucumber-core/src/test/java/io/cucumber/core/eventbus/IncrementingUuidGeneratorTest.java
Even when not used, the `IncrementingUuidGenerator` is instantiated with each Cucumber execution. This somewhat fundamental to the way the `ServiceLoader` mechanism works.
Each time an incrementing generator is created, a new session is started for that generator. This means that after 255 executions all sessions are exhausted.
Unfortunately, when using the JUnit Platform, Maven issues a discovery request for each individual class. And Cucumber typically participates in discovery along with JUnit Jupiter. So after requests for 255 classes, Cucumber fails discovery as seen in #2930.
Fixes #2930, #2925
Lazily start IncrementingUuidGenerator sessions
@jkronegg best I could think of. Got any other ideas?
----
> Lazily start IncrementingUuidGenerator sessions

- cucumber-core/src/main/java/io/cucumber/core/plugin/RerunFormatter.java
Changed the type of container for `featureAndFailedLinesMapping` in `RerunFormatter.java` in order to fix the flaky test: 
`io.cucumber.core.plugin.RerunFormatterTest.should_one_entry_for_each_failing_feature`
The following container uses HashMap implementation for storing `URI => Collection<Integer>` mapping in the class `RerunFormatter` :
```java
private final Map<URI, Collection<Integer>> featureAndFailedLinesMapping = new HashMap<>();
```
Entries are added to it by the eventPublisher: `TestCaseFinished.class`<br>
In the test-case `RerunFormatterTest.should_one_entry_for_each_failing_feature`, before assertion, the `featureAndFailedLinesMapping` looks like:
```java
{
URI("classpath:path/first.feature")=[2],
URI("classpath:path/second.feature")=[2]
}
```
With string representation: …
> Fixed failing flaky test-case caused by usage of HashMap in class RerunFormatter

- cucumber-core/src/main/java/io/cucumber/core/plugin/Jackson.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/HtmlFormatterTest.java
Changed the way of asserting fields in class `HtmlFormatterTest.java`
The Assertion for `bytes` to contain the string:
```js
window.CUCUMBER_MESSAGES = [
{"testRunStarted":{"timestamp":{"seconds":10,"nanos":0}}},
{"testRunFinished":{"success":true,"timestamp":{"seconds":15,"nanos":0}}}
];"
```
is **flaky** in nature. Precisely, the value assigned to  `window.CUCUMBER_MESSAGES` is a *list of objects* in `js`, but apparently derived from a *List of HashMaps* in java. HashMaps being unordered, can sometimes return a result like:
```js
window.CUCUMBER_MESSAGES = [
{"testRunStarted":{"timestamp":{"nanos":0, "seconds":10}}}, # different order, same object/contents
{"testRunFinished":{"success":true,"timestamp":{"seconds":15,"nanos":0}}}
];"
```
The test may fail on a **different jvm** …
> Fix flaky test-cases in HtmlFormatterTest

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/plugin/PrettyFormatter.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/PrettyFormatterTest.java
- docstring/src/main/java/io/cucumber/docstring/DocString.java
- docstring/src/main/java/io/cucumber/docstring/DocStringFormatter.java
- docstring/src/test/java/io/cucumber/docstring/DocStringFormatterTest.java
- docstring/src/test/java/io/cucumber/docstring/DocStringTest.java
- docstring/src/test/java/io/cucumber/docstring/DocStringTypeRegistryDocStringConverterTest.java
The pretty formatter now also prints docstring step arguments, in addition to datatable step arguments
I use the pretty formatter to print out my test results, and I noticed that everything gets printed except for docstring step arguments. It felt like this was a missing or incomplete feature. Regardless, I want to have my formatted test results include the contents of the step docstrings.
I'm not sure what else needs to be done before this pull request can be merged. I don't know if this needs to be announced or if I should update anything in the documentation or changelog. If that's required, please let me know what other changes I should make, and I will make …
> Pretty-Print DocStringArgument Step Arguments

- README.md
- Center align README badges
- Change version badge color from blue to green
- Fix GitHub workflow badge
- Extended summary description and linked logo
[![#StandWithUkraine](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/StandWithUkraine.svg)](https://vshymanskyy.github.io/StandWithUkraine) [![OpenCollective](https://opencollective.com/cucumber/backers/badge.svg)](https://opencollective.com/cucumber) [![OpenCollective](https://opencollective.com/cucumber/sponsors/badge.svg)](https://opencollective.com/cucumber) [![Maven Central](https://img.shields.io/maven-central/v/io.cucumber/cucumber-java.svg?label=Maven%20Central)](https://central.sonatype.com/artifact/io.cucumber/cucumber-java) [![Build Status](https://github.com/cucumber/cucumber-jvm/workflows/Cucumber%20 …
> docs: Center align README badges

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/backend/CucumberInvocationTargetException.java
- cucumber-core/src/main/java/io/cucumber/core/runner/StackManipulation.java
- cucumber-core/src/test/java/io/cucumber/core/runner/StepDefinitionMatchTest.java
- cucumber-java/src/test/java/io/cucumber/java/JavaStepDefinitionTest.java
- cucumber-java8/src/test/java/io/cucumber/java8/Java8LambdaStepDefinitionMarksCorrectStackElementTest.java
The `CucumberInvocationTargetException` was originally designed to be used as a wrapper around `InvocationTargetException` to track the step definition that caused the exception. The cause of `InvocationTargetException` would then be rewritten to appear to have originated from the step definition. This would effectively hide the whole backend from view.
Unfortunately using DataTable.asList inside a step, this also invokes the backend. And because `CucumberInvocationTargetException` did not have cause, the cause of any exceptions would also be hidden.
By exposing the cause of the `InvocationTargetException` as the cause of the `CucumberInvocationTargetException` and removing any frames before the step definition was invoked we can clean this up somewhat.
```log …
```
> Include root cause when using DataTable.asList and friends

- CHANGELOG.md
- cucumber-junit-platform-engine/pom.xml
By setting the Engine-Version-cucumber attribute to the current version TestEngine.getVersion will return the correct version instead of development.
Fixes: ##2936
> [JUnit Platform Engine] Set Engine-Version-cucumber attribute

- CHANGELOG.md
- cucumber-archetype/README.md
- cucumber-archetype/pom.xml
- cucumber-archetype/src/main/resources/archetype-resources/pom.xml
- cucumber-archetype/src/main/resources/archetype-resources/src/test/java/StepDefinitions.java
- cucumber-archetype/src/test/resources/projects/should-generate-project/reference/pom.xml
- cucumber-archetype/src/test/resources/projects/should-generate-project/reference/src/test/java/com/example/StepDefinitions.java
As a JUnit Platform Engine, Cucumber does not need JUnit Jupiter. It was included as a dependency to allow users to use Assertions. This is better done with AssertJ.
> [Archetype] Replace JUnit Jupiter with AssertJ

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/plugin/PrettyFormatter.java
- cucumber-core/src/test/java/io/cucumber/core/options/CommandlineOptionsParserTest.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/DefaultSummaryPrinterTest.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/IsEqualCompressingLineSeparators.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/JsonFormatterTest.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/PrettyFormatterTest.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/ProgressFormatterTest.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/RerunFormatterTest.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/StubException.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/TeamCityPluginTest.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/UnusedStepsSummaryPrinterTest.java
Renders the stack trace in the pretty formatter with the same indent as the step that failed it.
Before
```
[INFO] Running io.cucumber.skeleton.RunCucumberTest
Scenario: a few cukes               # io/cucumber/skeleton/belly.feature:3
Given I have 42 cukes in my belly # io.cucumber.skeleton.StepDefinitions.I_have_cukes_in_my_belly(int)
org.opentest4j.AssertionFailedError:
expected: "b"
but was: "a"
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at io.cucumber.skeleton.StepDefinitions.I_have_cukes_in_my_belly(StepDefinitions.java:12)
at ✽.I have 42 cukes in my belly(classpath:io/cucumber/skeleton/belly.feature:4)
```
After
```
[INFO] …
```
> [Core] Indent stacktrace in pretty formatter

- CHANGELOG.md
- cucumber-archetype/src/main/resources/archetype-resources/src/test/java/RunCucumberTest.java
- cucumber-archetype/src/test/resources/projects/should-generate-project/reference/src/test/java/com/example/RunCucumberTest.java
Add `@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example")` to the archetype.
Avoid:
```
WARNING: Failed to load class 'net.bytebuddy.dynamic.loading.ClassInjector$UsingJna$Dispatcher$Windows32BitFunctionMapper'.
...
java.lang.NoClassDefFoundError: com/sun/jna/FunctionMapper
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader …
```
> [Archetype] Set glue path by default

- CHANGELOG.md
- datatable/src/main/java/io/cucumber/datatable/DataTableTypeRegistryTableConverter.java
- datatable/src/test/java/io/cucumber/datatable/DataTableTypeRegistryTableConverterTest.java
> Convert parameterized objects with @DefaultDataTableEntryTransformer

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/plugin/TestSourcesModel.java
- cucumber-core/src/test/java/io/cucumber/core/plugin/JsonFormatterTest.java
When rules were added, the TestSourcesModel was not updated to account for these. As a result, the id for a given scenario was incomplete.
Also improved performance a tiny bit by reusing a pre-build regular expression.
> [Core] Fix incomplete id for scenarios under rules in json output

- CHANGELOG.md
- cucumber-bom/pom.xml
Fixes:  https://github.com/cucumber/cucumber-jvm/pull/3059 by https://github.com/cucumber/cucumber-json-formatter/pull/7
> Fix NPE for optional arguments when using the Cucumber JSON Formatter

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/runner/Runner.java
- cucumber-core/src/main/java/io/cucumber/core/snippets/SnippetGenerator.java
- cucumber-java/src/codegen/java/GenerateI18n.java
- cucumber-java/src/test/java/io/cucumber/java/JavaSnippetTest.java
- cucumber-java8/src/codegen/java/GenerateI18n.java
Step definition annotations and methods were not generated for the Emoji dialect because Emoji are not valid Java identifiers. By making a small exception in the script that generates these annotations we can instead use their symbol names.
So when using an Emoji feature file:
```feature
📚: 🙈🙉🙊
📕: 💃
😐🎸
```
This scenario can be made to pass with:
```java
public class StepDefinitions {
@NeutralFace("\uD83C\uDFB8")
public void guitar() {
}
}
```
Closes: https://github.com/cucumber/cucumber-jvm/issues/3061
Additionally, by removing the `’` from the Texan keywords we can also make the Texan dialect work. Like the `em` dialect `en-tx` is intended
to be humorous. I hope all Texans will look at it with that spirit.
> Generate annotations for Emoji dialect

- CHANGELOG.md
- cucumber-core/src/main/java/io/cucumber/core/plugin/RerunFormatter.java
Replace the `RerunFormatter` with the message based implementation.
This achieves several goals:
* Move the internal code base away from the events from the plugin module.
* Extract common parts of Cucumber into modules that can be shared.
Partially implement: https://github.com/cucumber/cucumber-jvm/issues/3001
- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)
> Use a message based RerunFormatter

- .github/workflows/test-java.yml
- CHANGELOG.md
- cucumber-junit-platform-engine/pom.xml
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberDiscoverySelectors.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberTestDescriptor.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureFileResolver.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureParserWithCaching.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureParserWithIssueReporting.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureParserWithSource.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureSource.java
- cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureWithSource.java
Creating a `FileSource` involves a call to `File.getCanonicalFile`. This call can be slow because it involves the file system. Especially if the file system is networked.
By using `FileSource.withPosition` we can reuse the canonical file from the feature for its nodes.
Fixes: #3010
> [JUnit Platform Engine] Use FileSource.withPosition
