cucumber/cucumber-jvm

History.md
making a pull request just to put this change on everyones radar. will be merged immediately.
=> added names to history updates

examples/java-gradle/build.gradle, examples/java-gradle/src/test/java/gradle/cucumber/RunCukesTest.java
Would not run out of the box because of:
- missing dependency 1.2.1 in maven-repo, uses 1.2.2 now
- Wrong Cucumber.Options import
Fixed use so --plugin is used instead of --format
=> Fix non running gradle example

core/src/test/java/cucumber/runtime/io/URLOutputStreamTest.java
* tests whether files are created when the parent directory does not exists
* removes duplicate test case
=> Additional unit-tests for #789

java/src/main/code_generator/I18n.java.txt
Pull request for issue #833 
Fixes #833
=> #833 Added @Documented to all step annotations

.travis.yml
I'm pretty sure this will work just fine.
=> Update to the newer, faster infrastructure

core/src/main/java/cucumber/runtime/formatter/JUnitFormatter.java, core/src/test/java/cucumber/runtime/TestHelper.java, core/src/test/java/cucumber/runtime/formatter/JUnitFormatterTest.java
Fixes [cucumber/cucumber-jvm#962](https://github.com/cucumber/cucumber-jvm/issues/962)
=> Mark scenario as skipped in junit reporter if PendingException is thrown in a hook

java/src/test/java/cucumber/runtime/java/test/SubstitutionStepdefs.java
=> Replace \n with %n so that tests work on Windows.

spring/src/test/java/cucumber/runtime/java/spring/SpringFactoryTest.java, spring/src/test/java/cucumber/runtime/java/spring/metaconfig/general/BellyMetaStepdefs.java, spring/src/test/java/cucumber/runtime/java/spring/metaconfig/general/MetaConfiguration.java, spring/src/test/java/cucumber/runtime/java/spring/metaconfig/general/RunCukesTest.java, spring/src/test/java/cucumber/runtime/java/spring/webappconfig/RunCukesTest.java
cucubmer-spring project some test was not run.
That's fixed.
=> cucumber-spring test fix

picocontainer/README.md, picocontainer/src/main/java/cucumber/runtime/java/picocontainer/PicoFactory.java, picocontainer/src/test/java/cucumber/runtime/java/picocontainer/DisposableCucumberBelly.java, picocontainer/src/test/java/cucumber/runtime/java/picocontainer/PicoFactoryTest.java, picocontainer/src/test/java/cucumber/runtime/java/picocontainer/StepDefs.java
Fix for item 3 discussed at #993
Includes #992
=> 993 add picocontainer lifecycle

junit/src/main/java/cucumber/runtime/junit/JUnitOptions.java
Argument --no-filename-compatible-names was not working. Looking at the code revealed a possible copy&paste error
=> JUnitOptions filename-compatible-names argument

.travis.yml, examples/android/android-test/pom.xml, examples/java-webbit-websockets-selenium/pom.xml, pom.xml
Use the [Android support](http://docs.travis-ci.com/user/languages/android/) to run the Android examples on Travis
Related issues
- #578 
- #824
=> Run the Android examples on Travis v2

examples/clojure_cukes/pom.xml, examples/groovy-calculator/pom.xml, examples/java-wicket/java-wicket-test/pom.xml, java8/pom.xml, kotlin-java8/pom.xml, pom.xml
Bump dependency versions
To keep up to date with new version of maven plugin and project dependencies.
By the Travis builds.
=> [Build] Bump dependency versions

CONTRIBUTING.md, guice/README.md
"cucumber-guice.properties" has already been updated to "cucumber.properties" (see #913).
However, ink to cukes.info/api/cucumber/jvm/javadoc/cucumber/api/guice/package-summary.html is no longer valid, and was therefore removed.
=> Update link to javadocs

examples/java-gradle/build.gradle
Update gradle dependecy group to io.cucumber
Checking the examples based on #1237
Should be updated everywhere
=> Update gradle dependency group

clojure/pom.xml, guice/pom.xml, junit/pom.xml, needle/pom.xml, openejb/pom.xml, osgi/pom.xml, rhino/pom.xml, scala/pom.xml, spring/pom.xml, weld/pom.xml
Remove provided scoped dependencies that are also transitive.
=> Remove provided scoped dependencies that are also transitive

CONTRIBUTING.md, README.md
Update README.md and CONTRIBUTING.md
Update links to documentation: info.cukes -> cucumber.io
Add links to the separate repos for JVM languages, which were removed from this repo.
Provide links to where the different JVM languages' repos are.
Updates in documentation only.
=> Update URLs to documentation and links to new repos for JVM languages

CONTRIBUTING.md, doc/genapi.sh
Updates to reflect removal of several jvm languages
Remove ScalaDoc and Yardoc from genapi.sh
Remove mention of Clojure from CONTRIBUTING.md
Several of the JVM languages (including Clojure, Scala, JRuby) were removed from this repo and moved to their own repos. However, they were still referenced in several places. Fixes #1257
=> Updates regarding removal of several jvm languages

junit/src/main/java/cucumber/runtime/junit/JUnitOptions.java
Print available JUnit Options when an unknown option is provided
Only a few JUnit options can be provided in the command line arguments or the CucumberOptions. For any other options a CucumberException is thrown stating that an "Unknown option" is used.
Found while testing PR for #147 
Running cucumber-java-skeleton project with all known and several unknown options.
=> Print JUnit Options when unknown option is provided

pom.xml
Upgrade tag expressions to 1.1.1
Fix build breaking on pax exam
=> Upgrade tag expressions to 1.1.1

junit/src/main/java/cucumber/api/junit/Cucumber.java
Add supported JUnit annotations to javadoc
The only supported annotations are @ClassRule, @BeforeClass and @AfterClass in the runner class. This should be mentioned in Cucumber. This is not documented in [Cucumber.java](https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/cucumber/api/junit/Cucumber.java).
As suggested in #1268
=> Add supported JUnit annotations to javadoc

core/src/main/java/cucumber/api/CucumberOptions.java, core/src/main/java/cucumber/runtime/RuntimeOptions.java, core/src/main/java/cucumber/runtime/RuntimeOptionsFactory.java, core/src/main/resources/cucumber/api/cli/USAGE.txt, examples/java-calculator-testng/src/test/java/cucumber/examples/java/calculator/RunCukesByCompositionTest.java
Reverts cucumber/cucumber-jvm#1260
=> Revert "Remove the deprecated -f/--format option"

RELEASING.md
Add updating cucumber-jvm version in the docs to the release process.
Fixes #1299
Provide link to docs project and where to update the version
Keep documentation up to date
N/A
=> Add updating version in docs to release process (Fix #1299)

pom.xml
=> Upgrade gherkin and cucumber expressions

java/src/main/java/cucumber/runtime/java/Java8Snippet.java, java/src/main/java/cucumber/runtime/java/JavaSnippet.java, java/src/test/java/cucumber/runtime/java/Java8SnippetTest.java, java/src/test/java/cucumber/runtime/java/JavaSnippetTest.java
Use fully classified name for PendingException.
See #1383
Updated tests and ran `mvn clean install`
=> [Core] Use fully classified name for PendingException

java/src/main/java/cucumber/runtime/java/AbstractJavaSnippet.java, java/src/test/java/cucumber/runtime/java/JavaSnippetTest.java
Improve DataTable hint and update tests
* Add missing comma between "Byte Short"
* Add type E
Fixes #1384
Updated tests accordingly and ran `mvn clean install`
=> [Core] Update DataTable hint

core/src/main/java/cucumber/api/TestStep.java, core/src/main/java/cucumber/runner/HookTestStep.java, core/src/main/java/cucumber/runner/PickleStepTestStep.java
Remove deprecated TestStep methods
=> [Core] Remove deprecated TestStep methods

spring/README.md
Rewrote a part of the spring readme for clarity.
Removed the reference to `@Scope("cucumber-glue")``. The existence of "cucumber-glue" is an implementation detail. Users should rely on the mechanisms provided by Spring i.e: `@DirtiesContext`.
Added an section on how to connect the Spring configuration to Cucumber step definitions.
=> [Spring] Update documentation

core/src/test/java/cucumber/runtime/model/CucumberFeatureTest.java
Errors in IntelliJ due to deprecated static import.
Change import so non deprecated version.
Continual improvement and test coverage
Build still passes
=> Replace deprecated org.mockito.Matchers

java/src/test/java/cucumber/runtime/java/JavaSnippetTest.java
Looked into why test fails and is marked as @Ignore.
Tracked down which method execution feedback unexpected response and comment test accordingly.
Added extra new line character so easier to understand executable statement just in case looking at stacktraces in future.
=> Explain why recognisesWordWithNumbers test is ignored

CHANGELOG.md, core/src/test/java/cucumber/runtime/formatter/PrettyFormatterTest.java, pom.xml
Upgrade cucumber expressions to 6.1.0
Closes #1393
=> [Core] Upgrade cucumber expressions to 6.1.0

pom.xml
Use cucumber-parent pom and remove duplication.
Open issues:
See  #1493
=> Use cucumber parent

core/src/main/java/cucumber/api/Scenario.java, core/src/main/java/cucumber/api/event/ConcurrentEventListener.java, core/src/main/java/cucumber/api/event/Event.java, core/src/main/java/cucumber/api/event/EventListener.java
Update EventListener Javadoc
Fixes: #1502
=> [Core] Update EventListener Javadoc

core/src/main/java/cucumber/runtime/io/FileResource.java
Fix class loading on Windows
Fixes: #1540
=> [Core] Fix class loading on Windows

core/src/main/java/cucumber/runtime/BackendModuleBackendSupplier.java, core/src/main/java/cucumber/runtime/ClassFinder.java, core/src/main/java/cucumber/runtime/Reflections.java, core/src/main/java/cucumber/runtime/RuntimeOptionsFactory.java, core/src/main/java/cucumber/runtime/io/ClasspathResourceIterable.java, core/src/main/java/cucumber/runtime/io/FileResource.java, core/src/main/java/cucumber/runtime/io/FileResourceLoader.java, core/src/main/java/cucumber/runtime/io/MultiLoader.java, core/src/main/java/cucumber/runtime/io/ResourceLoaderClassFinder.java, core/src/main/java/cucumber/runtime/io/ZipResource.java, core/src/main/java/cucumber/runtime/model/FeatureLoader.java, core/src/main/java/io/cucumber/core/model/Classpath.java, core/src/main/java/io/cucumber/core/model/FeatureIdentifier.java, core/src/main/java/io/cucumber/core/model/FeaturePath.java, core/src/main/java/io/cucumber/core/model/GluePath.java, core/src/test/java/TopLevelClass.java, core/src/test/java/cucumber/runtime/BackendModuleBackendSupplierTest.java, core/src/test/java/cucumber/runtime/RuntimeOptionsFactoryTest.java, core/src/test/java/io/cucumber/core/model/FeaturePathTest.java, core/src/test/java/io/cucumber/core/model/GluePathTest.java, java/src/main/java/cucumber/runtime/java/JavaBackend.java, java/src/main/java/cucumber/runtime/java/MethodScanner.java, java/src/main/java/cucumber/runtime/java/ObjectFactoryLoader.java
Fix illegal argument exception when using root package as glue
Fixes #1571.
=> [Core] Fix illegal argument exception when using root package as glue

core/src/main/java/cucumber/api/CucumberOptions.java, junit/src/main/java/cucumber/api/junit/Cucumber.java, testng/src/main/java/cucumber/api/testng/TestNGCucumberRunner.java
Improve CucumberOptions documentation
Fixes: #338
=> [Core] Improve CucumberOptions documentation

core/src/main/java/io/cucumber/core/api/event/EventListener.java, core/src/main/java/io/cucumber/core/api/options/CucumberOptions.java, core/src/main/java/io/cucumber/core/backend/Backend.java, core/src/main/java/io/cucumber/core/backend/HookDefinition.java, core/src/main/java/io/cucumber/core/backend/StepDefinition.java, core/src/main/java/io/cucumber/core/logging/Logger.java, core/src/main/java/io/cucumber/core/options/RuntimeOptions.java, guice/src/main/java/io/cucumber/guice/api/package-info.java
A few lines of javadoc. Already creating a pull to check for style, etc.
=> Added a few lines of JavaDoc that fail the build on development-v5.

README.md
=> Update README to fix typo

java/src/main/groovy/deprecated-annotation.java.gsp
=> [Java] Fix link to new steps in generated Java doc

java/src/main/java/cucumber/runtime/java/ParameterInfo.java, java/src/test/java/cucumber/runtime/java/JavaStepDefinitionTransposeTest.java
Replacing old annotation cucumber.api.Transpose with the new one (io.cucumber.java.Transpose) conduct to ClassCastException in cuncumber-core.
=> [Java] Fix ClassCastException on new Transpose annotation

.travis.yml, core/pom.xml, pom.xml
Cobertura does not work with Java 8.
=> [Build] Use Jacoco for code coverage

core/pom.xml, core/src/test/java/io/cucumber/core/plugin/CanonicalEventOrderTest.java, core/src/test/java/io/cucumber/core/plugin/TimelineFormatterTest.java
Replace AssertJ with JUnit5+Hamcrest. Only used in one test.
=> [Core] Replace AssertJ with JUnit5+Hamcrest

CHANGELOG.md
Add a note to the changelog on how to adopt the io.cucumber package changes.
=> Hint at how to adopt io.cucumber package changes

guice/src/main/java/io/cucumber/guice/package-info.java
use new package in this file
use cucumber-jvm 5+
=> [Guice] Update documentation

core/src/main/java/io/cucumber/core/api/Scenario.java
=> [Core] Fix typo in Scenario.getLine JavaDoc

spring/README.md
Documents what the `cucumber-glue` scope does.
Closes: #1668
=> [Spring] Document cucumber-glue scope

junit/src/main/java/io/cucumber/junit/FeatureRunner.java, junit/src/main/java/io/cucumber/junit/PickleRunners.java, pom.xml
Heard junit v4.13 was released, so tried building cucumber, fixes in separate PR as not 100% sure without testing more projects if we should upgrade to junit v4.13 yet.
Bump Dependency to junit v4.13
Still Bored
mvn clean install
=> [JUnit] Use JUnit 4.13

CHANGELOG.md, core/README.md, core/src/main/java/io/cucumber/core/options/Constants.java, core/src/main/java/io/cucumber/core/options/PickleOrderParser.java, core/src/main/resources/io/cucumber/core/options/USAGE.txt, junit-platform-engine/README.md
* Document property sources and names in core/README.md
* Document property sources and names in CLI USAGE.txt
* Support default value for cucumber.execution.order
Closes: #1717
=> [Core] Document supported properties

.m2/maven-version-rules.xml, cdi2/pom.xml, core/pom.xml, docstring/pom.xml, examples/java-calculator-junit5/pom.xml, examples/java-calculator/pom.xml, examples/java-wicket/java-wicket-main/pom.xml, examples/java-wicket/java-wicket-test/pom.xml, examples/spring-txn/pom.xml, guice/pom.xml, java/pom.xml, kotlin-java8/pom.xml, pom.xml, spring/pom.xml
Upgrades various dependencies. Notably:
- `junit-platform:1.6.1`
- `spring-*:5.2.4.RELEASE`
=> [All] Increase dependency versions

CHANGELOG.md, core/src/main/java/io/cucumber/core/backend/TestCaseState.java, core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java, core/src/main/java/io/cucumber/core/runner/TestCaseState.java, core/src/test/java/io/cucumber/core/plugin/HTMLFormatterTest.java, core/src/test/java/io/cucumber/core/plugin/JSONFormatterTest.java, core/src/test/java/io/cucumber/core/plugin/TeamCityPluginTest.java, core/src/test/java/io/cucumber/core/runner/TestCaseStateResultTest.java, core/src/test/java/io/cucumber/core/runner/TestHelper.java, examples/java-calculator-junit5/src/test/java/io/cucumber/examples/junit5/calculator/RpnCalculatorStepDefinitions.java, examples/java-calculator/src/test/java/io/cucumber/examples/java/RpnCalculatorSteps.java, examples/java8-calculator/src/test/java/io/cucumber/examples/java8/RpnCalculatorSteps.java, java/src/main/java/io/cucumber/java/Scenario.java, java8/src/main/java/io/cucumber/java8/Scenario.java, release-notes/v5.0.0.md
Deprecate Scenario.write ; Add Scenario.log
Deprecate Scenario.embed; Add Scenario.attach
Fixes #1893
=> [Java/Java8] Rename scenario methods

core/README.md, java8/README.md, junit-platform-engine/README.md, junit/README.md, needle/README.md, picocontainer/README.md, spring/README.md, testng/README.md
- Fixed a few typos across a number of the READMEs
- Fixed a few minor grammatical errors
- Fixed a few sentences for better readability
Nothing major; just a tidy up :)
=> Fix various typos in documentation

CHANGELOG.md, core/src/test/java/io/cucumber/core/runtime/FeaturePathFeatureSupplierTest.java, gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesFeature.java, gherkin-messages/src/main/java/io/cucumber/core/gherkin/messages/GherkinMessagesFeatureParser.java, gherkin-messages/src/test/java/io/cucumber/core/gherkin/messages/FeatureParserTest.java, junit-platform-engine/src/test/resources/io/cucumber/junit/platform/engine/empty-feature.feature, junit/src/test/resources/io/cucumber/junit/empty-feature.feature, testng/src/test/resources/io/cucumber/testng/empty-feature.feature
A feature without pickles is a valid feature file and should not throw
any exceptions when executed.
An empty feature file is also a valid feature file but we should throw
an exception when explicitly asked to execute it. It was probably a
mistake.
=> [Core] Execute features files without pickles

Makefile, java/README.md
The Java readme is missing some of the basics about parameter types that need to be explained before explaining transformers
=> [Java] Improve README.md

renovate.json
Renovate update, don't limit pr's being raised, also automatically label pr for quick filtering.
Rate Limit 0
Label dependencies
=> Renovate Config

CHANGELOG.md, core/src/main/java/io/cucumber/core/plugin/HtmlFormatter.java, core/src/main/java/io/cucumber/core/plugin/JsonFormatter.java, core/src/main/java/io/cucumber/core/plugin/MessageFormatter.java, core/src/test/java/io/cucumber/core/plugin/UrlOutputStreamTest.java, pom.xml, release-notes/v6.0.0.md
Fixes: https://github.com/cucumber/cucumber-jvm/issues/2020
Fixes: https://github.com/cucumber/cucumber/issues/1045
=> [Core] Always use UTF8 encoding

core/src/main/java/io/cucumber/core/resource/PathScanner.java, core/src/test/java/io/cucumber/core/resource/ResourceScannerTest.java, core/src/test/resource-symlink
Fixes #2042
I've added option for `walkFileTree` method to follow symlinks and added tests for `PathScanner` that involve symlinks
Add any other context or screenshots about the pull request here.
=> [Core] Follow symlinks when loading feature files

CHANGELOG.md, pom.xml
See the [published security advisory](https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp) for details.
=> Update dependency junit:junit to v4.13.1

junit-platform-engine/README.md
Review and edit of the JUnit Platform Engine documentation, as requested by @mpkorstanje 
* Fix typos
* Edits for clarity / consistency
* Add information where needed
=> Update JUnit Platform Engine documentation

java/README.md
Based on links provided in docs issue https://github.com/cucumber/docs.cucumber.io/issues/459, I noticed some typos and decided to to a review & edit of this readme, resulting in this PR.
Fixed a few typos.
Made some minor edits to clarify (in my opinion)
Improving this doc slightly so we can point to it directly from the (website) docs.
=> Fix typos, minor edits

.revapi/api-changes.json, core/src/test/java/io/cucumber/core/plugin/StatsTest.java, pom.xml
Replaces annoying xml configuration with a json file.
=> [Build] Replace revapi.ignore with revapi.difference

plugin/src/main/java/io/cucumber/plugin/event/EventPublisher.java
Update EventPublisher javadoc to reflect changes in Scenario API.
=> Update EventPublisher javadoc

cdi2/pom.xml
Reverts cucumber/cucumber-jvm#2247
=> Revert "Update weld-se-core.version to v4 (major)"

CHANGELOG.md, core/src/main/java/io/cucumber/core/plugin/NoPublishFormatter.java, core/src/test/java/io/cucumber/core/plugin/NoPublishFormatterTest.java, release-notes/v6.5.0.md
Many users need help setting environment variables
This updates the banner to point to new docs added in cucumber/docs#636
=> Point to https://cucumber.io/docs/cucumber/environment-variables/

core/src/main/java/io/cucumber/core/resource/ClasspathSupport.java, core/src/main/java/io/cucumber/core/resource/JarUriFileSystemService.java
=> [Core] Explain classpath scanning when dealing with nested jars  

core/src/main/java/io/cucumber/core/resource/ClasspathSupport.java, spring/README.md, spring/src/main/java/io/cucumber/spring/SpringFactory.java, spring/src/test/java/io/cucumber/spring/SpringFactoryTest.java
=> [Spring] Document how to configure multiple test application contexts   

CHANGELOG.md
Missing an extra whitespace for the bullets hierarchy to be displayed as expected.
=> Fix CHANGELOG indentation

java/src/main/java/io/cucumber/java/AfterAll.java, java/src/main/java/io/cucumber/java/BeforeAll.java
A simple fix for the comment of BeforeAll and AfterAll annotation.
=> [Java] Fix java doc on BeforeAll and AfterAll

.github/workflows/build.yml
Implementation of  Update codecov #2407
=> Update codecov #2407

CHANGELOG.md, bom/pom.xml, core/pom.xml, core/src/main/java/io/cucumber/core/runtime/CucumberExecutionContext.java
=> [Core] Replace create-meta with ci-environment

core/src/main/java/io/cucumber/core/backend/DefaultObjectFactory.java, core/src/test/java/io/cucumber/core/backend/DefaultObjectFactoryTest.java
=> [Core] Correct typo in stacktrace

CHANGELOG.md, core/src/main/java/io/cucumber/core/runtime/CucumberExecutionContext.java
=> Fix NPE that happens if git is not detected

CHANGELOG.md, core/src/main/java/io/cucumber/core/plugin/NoPublishFormatter.java, core/src/test/java/io/cucumber/core/plugin/NoPublishFormatterTest.java
=> [Core] Fix Cucumber report spam

CHANGELOG.md, jakarta-openejb/pom.xml, jakarta-openejb/src/main/java/io/cucumber/jakarta/openejb/OpenEJBObjectFactory.java, jakarta-openejb/src/main/java/io/cucumber/jakarta/openejb/package-info.java, jakarta-openejb/src/main/resources/META-INF/services/io.cucumber.core.backend.ObjectFactory, jakarta-openejb/src/test/java/io/cucumber/jakarta/openejb/Belly.java, jakarta-openejb/src/test/java/io/cucumber/jakarta/openejb/BellyStepDefinitions.java, jakarta-openejb/src/test/java/io/cucumber/jakarta/openejb/OpenEJBObjectFactoryTest.java, jakarta-openejb/src/test/java/io/cucumber/jakarta/openejb/RunCucumberTest.java, jakarta-openejb/src/test/resources/META-INF/beans.xml, jakarta-openejb/src/test/resources/io/cucumber/jakarta/openejb/cukes.feature, jakarta-openejb/src/test/resources/junit-platform.properties, pom.xml
Adds a new module to `jakarta-openejb` handle jakarta.* namespace for TomEE 9.x
TomEE 9.x-M8 is out. We should support jakarta.* namespace in cucumber.
----
=> #2548 - Provide an openejb-jakarta artifact to handle TomEE 9.x

.github/workflows/test-java.yml
=> Always color all Maven steps, not just the ones using --batch-mode

CHANGELOG.md, examples/wicket-java-junit4/wicket-main/pom.xml, pom.xml
see https://maven.apache.org/guides/mini/guide-reproducible-builds.html
Reproducible Builds
----
=> Enable reproducible builds

CONTRIBUTING.md, README.md
=> Fix typo in README.md

cucumber-archetype/pom.xml
Add cucumber-bom as a dependency in cucumber-archetype
Getting Maven to build modules in the right order.
Ref: https://maven.apache.org/guides/mini/guide-multiple-modules.html
v :bug: Bug fix (non-breaking change which fixes a defect)
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_T …
=> Fix build order of Maven modules

.spotless/intellij-idea.importorder, CONTRIBUTING.md, cucumber-archetype/README.md, cucumber-bom/README.md, cucumber-core/README.md, cucumber-deltaspike/README.md, cucumber-java/README.md, cucumber-java8/README.md, cucumber-junit/README.md, cucumber-testng/README.md, datatable/README.md, pom.xml
Fixed several typos / grammar issues in various places
Make things slightly better than I found them
x :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
----
=> Fix various typos in documentation and code

cucumber-junit/src/main/java/io/cucumber/junit/CucumberOptions.java
=> [JUnit] Link tag expression documentation

cucumber-picocontainer/README.md
Missing angle bracket
Missing angle bracket
Just a missing character
- :bug: Bug fix
----
=> Update README of picocontainer

examples/spring-java-junit5/pom.xml
Keep spring version up to date on spring boot example
----
=> Upgrade spring boot version to  3.0.5 on examples

cucumber-core/src/main/java/io/cucumber/core/options/Constants.java
Fixed the incomplete sentence in Javadoc.
Fixes #2690
- :bank: Refactoring (improvement to documentation)
----
=> [Core] Fix unfinished sentence in Javadoc

CHANGELOG.md, cucumber-core/src/main/java/io/cucumber/core/runtime/CucumberExecutionContext.java, cucumber-core/src/main/java/io/cucumber/core/runtime/Runtime.java, cucumber-core/src/test/java/io/cucumber/core/runtime/RuntimeTest.java, cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineDescriptor.java, cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineExecutionContext.java, cucumber-junit/src/main/java/io/cucumber/junit/Cucumber.java
=> [JUnit] Fix swallowed exception

CHANGELOG.md, cucumber-core/src/main/java/io/cucumber/core/options/RuntimeOptions.java, cucumber-core/src/test/java/io/cucumber/core/options/CucumberPropertiesParserTest.java, cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/CucumberEngineOptions.java, cucumber-junit-platform-engine/src/test/java/io/cucumber/junit/platform/engine/CucumberEngineOptionsTest.java
Fix cucumber.publish.enabled=false
Also disables the advertisement banner in light of https://mattwynne.net/new-beginning
Fixes: #2747
=> Fix cucumber.publish.enabled=false

.github/workflows/release-github.yml, .github/workflows/release-java.yml, .github/workflows/test-java.yml
Reverts cucumber/cucumber-jvm#2790
=> Revert "Update actions/checkout action to v4"

CONTRIBUTING.md, README.md, cucumber-bom/README.md, cucumber-cdi2/README.md, cucumber-core/README.md, cucumber-core/pom.xml, cucumber-core/src/main/java/io/cucumber/core/options/PluginOption.java, cucumber-core/src/main/java/io/cucumber/core/plugin/TeamCityPlugin.java, cucumber-deltaspike/README.md, cucumber-guice/README.md, cucumber-jakarta-cdi/README.md, cucumber-java/README.md, cucumber-java8/README.md, cucumber-junit-platform-engine/README.md, cucumber-junit/README.md, cucumber-picocontainer/README.md, cucumber-spring/README.md, cucumber-testng/README.md, datatable/README.md, examples/README.md, mvnw, release-notes/v1-CHANGELOG.md, release-notes/v5.0.0.md
@mpkorstanje asked me to look at the README's a while ago. 
Made some small tweaks. 
One question in comment
----
=> Improve documentation and comments

.github/workflows/test-java.yml
Use the latest LTS for testing.
=> Test with Java 21

cucumber-junit-platform-engine/README.md
=> [JUnit Platform] Fix misisng import in README

cucumber-junit-platform-engine/README.md, cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/Constants.java, cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolver.java
Added an explanation of what this is a workaround for and how to do it properly.
Closes: #2852
=> [JUnit Platform Engine] Improve the cucumber.features warning

.github/FUNDING.yml
See discussion on https://github.com/cucumber/.github/pull/42
=> chore: add github sponsors to funding

cucumber-java/README.md
minor fix to correct path to datatable documentation
fix a broken link
----
=> fix: correct path to datatable repo

CHANGELOG.md, cucumber-archetype/src/main/resources/archetype-resources/src/test/java/StepDefinitions.java, cucumber-archetype/src/test/resources/projects/should-generate-project/reference/src/test/java/com/example/StepDefinitions.java
Fixed issue as described in Issue #2898  
This is my first Cucumber contribution so let me know if there's something to improve
----
=> Use import static for Assertions in archetype

cucumber-junit-platform-engine/README.md
=> [JUnit Platform Engine] Add architecture diagrams

cucumber-java/README.md
Update format of example gherkin data table in README file
Just a small update to align pipe symbol for gherkin data table example used in the README file
----
=> Update formatting of gherkin data table example in README

cucumber-java8/README.md
Update format of example gherkin data table in README file.
Same change as #2981 but for cucumber-java8
Just a small update to align pipe symbol for gherkin data table example used in the README file
----
=> Update README formatting of gherkin data table example

cucumber-junit-platform-engine/README.md
Resolve TODO in README.md
Resolve TODO in README.md
=> [junit-platform] Document how to run a single feature with Gradle
